baseurl = "https://www.wzyblog.top/"
languageCode = "en-us"
title = "Website of ZhiYuan Wang"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
hasCJKLanguage = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "链接"
    url = "/friendly_links/"
    weight = 5
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; ZhiYuan Wang 2018"

