---
title: 行测(4)——专业知识
author: 王致远
date: '2018-10-25'
slug: xingce-4
categories:
  - 找工作
tags:
  - 学习总结
---

# 1. 金融学

## 1.1 货币

货币是固定充当一般等价物的特殊商品。

五个职能：价值尺度、流通手段、支付手段（清偿债务）、贮藏手段、世界货币。

充当世界货币的条件：

1. 进出口贸易额占世界进出口贸易额比例很高；
2. 货币价值稳定；
3. 能够自由兑换；

我国是世界上最早使用纸币的国家。不兑现货币只有货币价值，没有币材价值。

存款货币：活期货币。活期存款账户可以开出支票流通。

### 货币制度

货币本位：一个国家的货币制度所规定的货币基本单位及其价值标准。

本位货币：具有无限的法偿资格，作为最后支付手段。

劣币驱逐良币：复本位制下，市价比法定价格高的金属货币在流通中逐渐减少。

信用货币制度：信用货币，由现金和银行存款构成；通过金融机构业务流通出去。中央银行通过货币政策调控信用货币，

## 1.2 信用、利息和利率

信用是以偿本付息为条件的价值运动的特殊形式。

商业信用和银行信用是基本的信用形式；银行信用居主导地位，商业信用是信用体系的基础。

### 商业信用

商业性用是以赊账方式出售商品（或提供劳务）时买卖双方之间相互提供的信用。

商业信用的工具是商业票据。

- 期票：**债务人**向债权人开出，承诺在一定时期支付账款的凭证；
- 汇票：**债权人**向债务人发出命令，要求债务人向第三方或持票人支付一定款项的凭证。

### 银行信用

银行或货币资本所有者向职能资本提供贷款而形成的借贷关系。是适应产业资本循环周转或再生产运动的需要而产生的。

银行信用的对象不是商品资本，而是货币资本。

**银行的三种业务：负债业务、资产业务和中间业务**

### 国家信用

国家直接向公众借贷，形式：发行公债券（长期）和国库券（短期）。

### 消费信用

消费信用是工商企业、银行或其他信用机构向缺乏货币购买力的消费者提供贷款的活动。消费信用的主要形式：赊账（信用卡）、分期付款和发放消费信贷。

### 信用工具

以书面形式发行和流通、借以保证债权人或投资人权利的凭证，是资金供应者和需求者之间继续进行资金融通时，用来证明债券的合法凭证。

信用工具也叫金融工具，是重要的金融资产，是金融市场上重要的交易对象。

信用工具的五大要素：

- 面值
- 到期日
- 期限
- 利率
- 利息支付方式

支票是活期存款存户对银行发出的一种支付通知，可代替货币发挥流通关于支付手段职能的信用流通工具，在节省现金方面存在巨大作用。

社会信用和股份信用工具：股票和公司债券。

股票持有者可以转让，但无权向企业要求退股。优先股的股息是固定的。

- 短期信用工具：国库券，商业票据（汇票、本票、支票）；
- 长期信用工具：有价证券，债券和股票。

商业信用工具和银行信用工具可在市场上直接流通；国家信用和社会股份信用不能作为流通手段和支付手段自由流通，但作为有价证券可以在证券市场买卖。

#### 信用工具的特征：

收益性：

- 名义收益：票面收益与本金比例；
- 即期收益：按市场价格卖出时所获得的收益；
- 实际收益：名义收益扣除物价变动；

风险性：投入的本金和利息收入遭到损失的可能性。

- 违约风险；
- 市场风险：利率变动、汇率变动、价格波动；
- 政治风险；
- 流动性风险；

### 利息

货币利息理论认为利息是借钱和出售证券的成本，同时又是贷款和购买证券的收益。作为一种货币现象，利息率的高低完全由货币的供求决定。

#### 利息在市场经济中的作用

1. 影响企业行为的功能
2. 影响居民资产选择行为的功能
3. 影响政府行为的功能（控制利率）

### 利率

一定时期内利息额同本金总额的比率。利率通常由中央银行控制。

单利终值

$$F=P(1+i*n)$$

$$F=P(1+i)^n$$

实际利率是名义利率扣除通货膨胀率。

浮动利率是指借贷业务发生时，由借贷双方共同确定，根据市场变化情况调整相应利率。

## 1.3 货币供求与货币政策

以商业银行为中介，借助于存款间接将同伙送到非银行部门手中，通货攻击数量完全取决于非银行部门的通货持有意愿。

- M0 = 流通中的货币；
- M1 = 现金+活期存款；
- M2 = M1+定期存款+储蓄存款+其他存款；
- M3 = M2+其他金融资产；

基础货币：流通中的现金和存款准备金。

基础货币=法定准备金+超额准备金+库存现金+手持现金

货币供应链=基础货币*货币乘数

国外净资产由外汇、黄金占款和中央银行在国际金融机构的净资产构成。

### 存款乘数

存款总额（原始存款与派生存款之和）与原始存款的倍数。派生存款由于银行之间的存贷活动引起的存款增加额。

**银行具有创造存款的能力**

$$存款乘数=\frac{1}{法定存款准备金率}$$

中央银行创造或消灭一单位的基础货币，能使货币供给量增加或减少的数额。

某一时点的货币供给量，由流通中的现金与存款准备金构成。**一定时期的货币供给量是由中央银行、商业银行与社会公众三部门共同决定的**

货币需求理论：费雪方程

$$MV=PT$$

- M：货币数量
- V：货币流通速度
- T：交易总量

凯恩斯货币需求理论

货币总需求等于货币的交易需求与投机需求之和。

#### 影响我国货币需求的因素：

- 收入，同方向
- 价格，同方向
- 利率，反方向
- 货币流通速度，反方向
- 金融资产选择
- 其他因素

### 货币政策

目标：稳定物价，经济增长，充分就业，平衡国际收支

货币政策工具：

1. 法定存款准备金率（成效慢）
2. 再贴现政策（调整再贴现率，主动权在商业银行）
3. 公开市场业务（调控急出货比，进而影响货币供应量和市场利率）

货币政策的中介目标：

1. 利率（银行间同业拆借利率，短期国库券利率）
2. 货币供应量；
3. 超额准备金或基础货币；
4. 通货膨胀率。

## 1.4 金融市场

金融资产也称为金融工具或有价证券。

金融市场的功能：

1. **货币资金融通**；
2. 优化资源配置；
3. 风险分散与风险管理；
4. 经济调节；
5. 定价；

金融市场主体：投资者、筹资者、套期保值者、套利者、调控和监管者。

- 存款性金融机构：商业银行、储蓄机构。信用合作社；
- 非存款性金融机构：投资基金、养老基金、保险公司；
- 中介机构：投资顾问、咨询公司、信用评级公司。

金融市场的客体：金融工具，具有流动性、收益性和风险性的特性。流动性与收益性呈反向相关。

金融市场按期限分，分为货币市场和资本市场：

- 货币市场：银行间同业拆借市场，银行间债券回购市场，票据市场，回购市场，货币市场基金；
- 资本市场：股票市场、债券市场；

按交易阶段分：

- 发行市场，一级市场；
- 流通市场，二级市场。

按交割时间分：

- 现货市场；
- 期货市场；

按交易场所划分：

- 场内交易
- 场外交易










