---
title: 《天龙八部》中的主角们
author: 王致远
date: '2018-11-05'
slug: tianlong-character
categories:
  - 读书
  - 电影
tags:
  - 思考
---

最近在看一个Up主叫“键行客”推的关于金庸小说介绍的系列视频，每段视频先用非常浅显的语言叙述故事梗概，后半部分有其对作品和人物的相关理解和思考。我认为思考和点评挺有水平的，值得反复品味，所以记下来。

首先从《天龙八部》这部书的书名说起。“天龙八部”是个佛教词语，是说人的八种苦，分别是：生、老、病、死、怨憎会（和恨的人或者讨厌的人在一起）、爱别离（爱某人却不得不分离）、求不得（想要的东西得不到）、五阴炽盛（欲望和贪嗔痴让内心烦躁）。而《天龙八部》这部书是金庸尝试将中式的《红楼梦》式悲剧和西方莎士比亚式悲剧融合在武侠场景；但相比《红楼梦》是时代和社会塑造贾府不可逃脱的悲剧，金庸笔下的悲剧多由世世代代的巧合产生，有更多的戏剧色彩，并且深受苦折磨的人们最终都找到了属于自己的解脱。

《天龙八部》中的三位男主人公便对应着贪嗔痴三种苦。大哥乔峰是嗔苦，二哥虚竹是痴苦，三弟段誉是贪苦。

### 乔峰

乔峰虽是丐帮的盖世英雄，但一直耿耿于怀自己是契丹人、谁是带头大哥、谁扮成自己杀了养父母和老师这些问题，一直在追寻这些问题的答案。在纠结于这些问题的过程中，虽然遇到了自己的爱人阿朱姑娘，但也亲手误杀了她，最终没能过上他许诺给阿朱的在草原上放牧的生活。“键行客”点评说，乔峰便犯了“嗔”苦，他不能忍受自己被人误解，因冲动杀害了很多人，包括自己最爱的人，终究没有得到幸福。但阿朱的死是刺进他心头的利剑，让他开始反省自己的过往。

想想当今社会，也有太多的人被仇恨、愤怒、怨恨、冲动所左右，既做出伤害别人（尤其是亲人和爱人）的事，同时也伤害了自己，并且离幸福越来越远。最近发生的重庆公交车坠江事件，就源于乘客和司机的嗔怒，使得除了他们两人外，还结束了13名其他乘客的生命。

一年前我也体会过极度的愤怒，那时的自己散发的气息都是难闻的，对自己的伤害也很大；这一年中我也时不时心中有怨，但不论是说话中伤他人，或是心中憋着埋怨，都对自己没有任何好的影响。相反，我逐渐学会从“利益”的角度看待复杂的关系，学会用“阴阳”的方法指导我处理事情和关系，那种怨也就能放下了。

### 虚竹

虚竹本是个平平凡凡的小和尚，也没什么太大理想，就是在少林寺认认真真修习佛学和武功。但是他天生有善良的心肠，在解开珍珑棋局那段故事中，他为了不让大家都被棋局所迷了心智，胡乱填了一子，在段延庆的帮助下解开了棋局，从而打开了他人生新的际遇，接受了无崖子传他的七十年功力，获得了逍遥派的内功；在救天山童姥的故事中，他以为童姥只是普通的小女孩，会有危难所以出手相救，从而被童姥教会了逍遥派的外功，成为绝顶高手之一。但他一直苦于佛家的条框，首先纠结于自己是少林派，不能再入逍遥派；之后又纠结于犯了杀生、饮酒、色欲等戒律。终于在少室山下英雄大会上，一日内经历了父母的相认和惨死彻悟了，上升到了更高的精神境界，将佛学与道学融会贯通，不在寺中也很坦然地修行。“键行客”点评说，虚竹从少林寺“毕业了”。

反观同样尝试解珍珑棋局的其他人，慕容复心中执着于“复兴大燕”的“大业”，被追求功名权力之心所迷，气度太小，在棋局中只能偏居一隅，无法逐鹿中原；段延庆倒是经历了由生入死，再向死而生，但在转变的过程中转向了恶业，做了太多恶事，再想改邪归正就难了（但帮助虚竹解开棋局的过程中，也是帮助自己重新回到正道）；段誉性格太慈爱柔弱，不愿舍弃自己的子，也就难成大业。而虚竹宅心仁厚，不计较自己的得失，从而在棋盘上不计较得失，但也正好就解开了棋局。

“键行客”通过珍珑棋局点评说，人如果想成就大业，就不能太过计较得失，只有心中放下得失心，踏踏实实做正事（例如虚竹踏踏实实学佛学，修内心），成功终究会不期而遇；相反得失心太重，反而会被人生的棋局所迷，一生也走不出这样的棋局。作为每个普通人，只要精修自己的技能，精心经营自己的人生，终能遇到自己的“梦姑”（伴侣）和“无崖子”（贵人）。

### 段誉

段誉和鸠摩智对应的都是“贪”毒，段誉贪美色，鸠摩智贪武功。而段誉一直痴迷的神仙姐姐和王语嫣，只不过是段誉心中自己美化后的心魔。段誉一直被这种心魔所左右着，不是真正的自由。原版的《天龙八部》结局是段誉和王语嫣过上了幸福的生活，像是王子和公主一般的童话。而新修版又加了一大段，说王语嫣看到了神仙姐姐的玉像，认为自己不可能跟玉像一样永葆青春，所以就将玉像打碎。这时段誉终于醒悟了，认清楚了真是的王语嫣，知道了自己原来幻想的都是心中那个美化后的人。最后和木婉清和钟灵在一起了，因为和她俩是真正经历过生死的。

对段誉这样的塑造非常的贴切，哪个少男少女在青春的懵懂期心里不曾有个TA，不曾有那样的情愫。然而那个近乎完美的人只是自己的想象。也许永远没有在一起，就把想象变成了回忆；也许在一起了，才发现想象塑造的形象破碎了。

### 总结

总体来说，《天龙八部》这部书都在讲各个人物的苦。有些人，比如萧远山，一生都在承受着苦，到头来发现生命的宝贵全都浪费在了无意义的事情上。所以，为了珍惜宝贵的生命，“放下”是要学会的。放下嗔，内心平静；放下痴，内心坦然；放下贪，内心清凉。