---
title: 行测(3)——材料分析题
author: 王致远
date: '2018-10-25'
slug: xingce-3
categories:
  - 找工作
tags:
  - 学习总结
---

## 注意

- 注意审题，严格对照清楚问的是谁，别计算错了对象；



## 例题

### 1. 已知今年水平，问去年（前年）水平

去年=今年/(1+增长率)

> 2015年蔬菜产量15.79万吨，下降3.4%；水果产量7.84万吨，增长7.4%；2014年蔬菜比水果约高多少万吨？

```{r}
15.79-7.84
```

约等于8，蔬菜是下降了，水果增长了，所以一定比8大，选9

```{r}
15.79/(1-0.034)-7.84/(1+0.074)
```

----

> 2015生产时钟完成产值162亿元，同比下降4.7%，降幅扩大1.3个百分点，问2015年产值与2013年相比约？

$$\frac{1-\frac{1}{(1-0.047)(1-0.034)}}{\frac{1}{(1-0.047)(1-0.034)}}$$

```{r}
(1-0.047)*(1-0.047+0.013)-1
```

下降8%

### 2. 平均数估算

> 十二五期间，粮食总产量

十二五是指2011~2015的五年。分别是4.34,4.43,4.14,4.21,4.16；选取中位数4.21作为平均数的估计；

```{r}
4.21*5
```

```{r}
4.34+4.43+4.14+4.21+4.16
```

### 4. 比率相比

直接相减，而不是像绝对数那样算

钟表行业利润率6.5%，轻工业利润率7.57%；

```{r}
6.5-7.57
```

### 5. 进出口问题

$$贸易顺差=出口额-进口额=进出口总额-2*进口额=2*出口额-进出口总额$$

### 6. 元素比例问题

> 博物馆占文物机构总数的43.5%，博物馆接待观众占总接待观众的85.2%。问每家博物馆接待观众人次是其他机构的多少倍？

分数上下将机构总数x和观众人数y约去了。

$$\frac{85.2\%/43.5\%}{(1-85.2\%)/(1-43.5\%)}$$

```{r}
0.852/0.435
(1-0.852)/(1-0.435)
```


