---
title: 观《海上钢琴师》
author: 王致远
date: '2018-10-03'
slug: the-legend-of-1900
categories:
  - 电影
tags:
  - 感受
---

## 背景

《海上钢琴师》这部电影我很早之前就已经听人推荐，知道是一部豆瓣评分很高（9.1分）的电影。导演是意大利人吉赛贝·托纳多雷，他还导演了《天堂电影院》和《西西里的美丽传说》。近期在网易云上听了一首《海上钢琴师》的背景音乐（The Crisis），觉得很喜欢，于是去看电影。

## 电影故事

故事是从男主角的好友（MAX）的叙述中展开。在1900年，一艘从欧洲开往美国的大轮船上，一个船上烧煤的工人捡到了一个小孩，取名叫TD·1900，TD被工人理解为Thanks Danny（工人自己的名字），于是收养在船上。这个孩子从小到大都没有下过这艘轮船，一直随着轮船往返于欧美之间，与船上的员工也都混得很熟悉，大家也都习惯了他的存在。一次偶然的机会，大家发现了这个孩子的音乐天赋。这个孩子成为这艘船上的钢琴师，他所演奏的音乐都是自己创作的，任由自己的脑海飞到世界各地，幻想那里的情况。他不仅为一等舱的贵族们演奏音乐，也会去三等舱为平民老百姓演奏，用精湛优美的钢琴音乐为他们消磨海上的无聊时。但他只在海上演奏，等船停靠在码头他便不再演奏。后来MAX作为小号手也加入随船乐队，1900与他成为好友。MAX一直劝1900下船去体验更大的世界，以他的才华来获得名誉和财富。但1900在某一次想下船上陆时，走到舷梯上，若有所思一阵子后，把帽子扔进海里，又回到了船上。中间穿插了几小事件，比如爵士乐的创始人来到船上与他“斗琴”；比如遇到一个拉着风琴给他讲海的声音的落魄男子；比如他用心观察每个乘客的外貌、穿着、动作，揣摩他们的心理，并用音乐表达出来；比如他在灌唱片时在舷窗外看到的那个姑娘，一见倾心，并小心翼翼地找到正在睡觉的她，亲吻她。之后，第二次世界大战爆发了，MAX也下了船，另谋生路了，他再也没听说这艘船和1900的消息。战争结束后，他偶然在卖掉小号时又听到了1900看到那个姑娘时演奏的曲子，了解到那艘船要被炸毁了，他坚信1900还在船上，多次冒险进去找他。最终播放了哪张唱片，找到了1900。1900拒绝了和他一起下船，而是选择和船一起毁灭。

## 效果

从效果上，这部电影最打动我的是它的镜头语言。很多镜头都很有味道，截屏下来甚至可以当作摄影作品，并且能读出导演想表达的意思。同时光影非常讲究，多用侧面的柔光，曝光较暗，很有高雅的质感。

## 场景

这部电影的经典场景我觉得有八个。

第一个是轮船接近纽约后，第一个看见自由女神像的人会大喊“America！”，然后人们一起欢呼起来。知乎里面有大神解读，这部电影不仅仅是在说1900这个人，还在讲欧洲古典文明在1900年期间被美国的现代工业文明所取代。人们从欧洲移民到美国，放弃了欧洲的旧文明，转而追求新文明的过程。

第二个是老工人决定收养下婴儿1900后，很多船员对他的冷嘲热讽。这个镜头一直在旋转，不断地在老工人和其他船员之间切换，能体现出老工人收养这个孩子的压力，内心的善良、无畏和自豪。

第三个是MAX刚到船上时，晕船晕得颠三倒四。在呕吐时遇到了第一次以青年形象出场的1900，穿着黑色燕尾服自如地在猛烈倾摆的船上行走（因为从小出生在船上，习惯了船的颠簸），非常的高贵典雅。1900让MAX打开固定钢琴的锁扣，钢琴随着船的倾摆开始在音乐大厅里滑动，1900邀请MAX坐下，跟着钢琴和音乐一起滑动，就像在跳华尔兹般自由。这是这部电影里我最喜欢的场景。背景音乐是[Magic Waltz](https://music.163.com/#/song?id=5027380)。

第四个是和爵士乐创始人（以下简称爵创）经典的“斗琴”。后来有些电影（包括周杰伦的《不能说的秘密》）借“斗琴”的桥段致敬这部电影。爵创第一首演奏了首很暧昧的曲子，旁白说他是在妓院学会的钢琴，为嫖客们演奏的，非常的不屑。1900演奏了一首简单、典雅、中正的宗教音乐。知乎大神说这里也是在反映逐渐没落的欧洲文明不屑于美国粗俗的工业文明。第二首爵创演奏了[The Crave](https://music.163.com/#/song?id=5027386)，1900心里没什么敌意，觉得这首好听，也演奏了这首。但他是在只听了一次的情况下就一音不落地，并且加了很多自由变奏的[The Crave](https://music.163.com/#/song?id=5027084)。这彻底激怒了爵创，演奏了一首快曲。1900以更快地一曲征服了所有人，钢琴的琴弦烫到点燃了香烟。

第五个是MAX邀请1900灌唱片。一开始他弹地自由但漫不经心，很快他注意到舷窗外的美丽姑娘。那个姑娘像是对着舷窗（可能从外面看是反射，从里面看是透射的）整理自己的妆容。1900不自觉得，手指下的音乐也变得非常优美，后面姑娘走开了，他的指尖也停滞了，姑娘又出现再另一扇舷窗，他的音乐也继续了。这一段能够感受到他的一见倾心，坠入爱河。音乐也十分经典。[Playing love](https://music.163.com/#/song?id=5027096).

第六个是他一个人在三等舱里想念那个姑娘，手指下弹奏简单、重复的几个音，很能体现出他的相思之情。[The crisis](https://music.163.com/#/song?id=5027083).

第七个是他等到大家都睡着了，到三等舱去找那个女孩。背景音乐也是The Crisis，他凝望着女孩的脸庞、眉眼、嘴唇，情不自禁地去亲吻女孩的嘴唇，那一瞬间觉得非常美好。后来在女孩要下船分别时，他也没能把那个唱片送给女孩。他决定毁掉那个唱片，因为那是他为她演奏的。

第八个是MAX不顾危险找到了1900劝他下船，他给MAX讲了自己生性自由，想要追求自由的艺术，并且决定自己死去的方式。外部的世界太大，诱惑太多，他无法在这样的环境下创作艺术。最终1900跟着船一起毁灭了。

## 对比

### 与《天堂电影院》

《海上》与《天堂》出自同一导演之手，在神韵上有些相似。比如电影中都有爱情，但不是整个篇幅，大概占1/4；也有亲情（多多对艾佛特，1900对丹尼）和友情（1900对MAX）。但两部电影说的事情却很相似：很有天赋的男主角，追求自己心中艺术的过程。但两个主角选择是完全不同的，《天堂》里的多多被艾佛特劝得离开了小城，去了更大的天地追求他的电影事业；1900一生都在船上度过，从出生到死亡，唯有一次最接近陆地时也选择了放弃，回到了船上。很难说哪一种选择是对的。多多在更大的平台上功成名就，1900在船上坚守自己纯洁的艺术。每个人内心对价值的认定不同，他们的选择只要遵循自己的意志就是好的。

### 与《不能说的秘密》

我是初中时就看过《不能说的秘密》，现在看了《海上钢琴师》才发现前者完全是致敬后者之作。第一个线索是“秘密”，“这是一个秘密”在两部电影里都不断被提到。第二个线索是都是在旧环境要被毁掉（琴房和轮船）时，拼命进去救朋友。第三个是“斗琴”。可能还有更多小细节。可以看出周杰伦也是非常喜欢《海上》这部电影。

## 总结

看完电影，我倒没有太被1900选择坚持艺术、留在船里的决定太感动。我是喜欢这部电影里上述的几个场景，特别是“晕船华尔兹”的场景，和电影的镜头语言与艺术表现力，的确是大师手笔。但其内涵，个人认为没有达到《天堂电影院》的高度。《天堂》的结尾，多多看艾佛特的剪拼的吻戏镜头，意味更长。