---
title: 谢益辉精彩博客（持续更新）
author: 王致远
date: '2018-10-04'
slug: yihui-excellent-post
categories: 
  - 博客
tags: 
  - 谢益辉
---

韩愈的《师说》中说：“古之学者必有师。师者，所以传道受业解惑也。”从小学到中学到大学，拥有老师似乎是理所当然的事。但一个人一旦脱离了校园环境，或是在校园环境中无法找到能够指引自己的老师（比如硕士阶段的我），便需要向外寻求能够在专业、技能，甚至是观念上能够指引自己的老师。好在互联网时代，人与人、人与社区之间的连接不再被距离或连接方式或连接成本所约束。博客、webinar（网络研讨会）就是非常好的找到老师、跟老师学习的途径。就如同古代佛学大师们开坛讲经一样，现在拥有一技之长或一家之言的人们开博客，不仅讲技术，也讲自己的观念，让思想能够广泛传播出去。

谢益辉是我很佩服的人，不仅仅是因为他创办了人大经济论坛（经管之家），策划了中国R语言会议，将吴喜之老师推动的R语言在中国的发展更加发扬光大，并且在R环境的横向运用（knitr、bookdown、blogdown、xaringan）上将R和Rstudio极大地拓宽，文学兴趣也很浓厚；还因为他能活成自己想要的样子，不为生计所累，不为财富欲所困，能够从事自己喜欢的工作，并且所做的工作影响、造福越来越多的人。

从某种角度上讲，我自认为和谢益辉大体是一类人：拥有一点现实的理想主义者、热爱技术、思维活跃而发散、兴趣驱动型、自我驱动型、喜爱创造力，还有都看过火影：)。但我的才华远远不如他。他博客中的很多观点对我都很有吸引力和启发性，我觉得他可以作为我的良师益友，哪怕他可能根本不认识我。这篇博客便是对我读过他的精彩博客的归纳，可以常看常新。

[《优秀到无法被忽视》](https://yihui.name/cn/2018/09/so-good-they-cannot-ignore-you/)中谈论了三个：激情（尤其是稳定的职业激情）、工匠精神（刻意联系和差异化竞争）、好工作（足够自主权的工作，需要通过漂亮的产出争取）。

[《科研新手之路线选择》](https://yihui.name/cn/2018/08/early-career/)中说怎么选择有影响力的研究方向：1.不用看远方，解决自身能感觉到的痛苦问题；2.所做的工作越基础，影响的人群越广。

[《在信息过载时代里注意力才是瓶颈》](https://yihui.name/cn/2018/08/attention/)中说“如果我们没有聚焦的能力，我们只能沦为浅薄的大多数。”这句很有启发性。

[《凉皮还是蒸面条》](https://yihui.name/cn/2018/08/cool-noodle/)中说“
果然人只要一贪便宜、走捷径就没好事。”这个观点我也很赞同。我之前就觉得，作为年轻人，不要害怕给自己挖坑，早早给自己挖坑，再努力去填上坑，水平和能力会快速提升。给自己挖坑其实也在给自己提供进步的机会。

[《利害》](https://yihui.name/cn/2018/08/pros-cons/)中说“就算你的出发点是好的，也可能最终办成坏事；就算出发点是坏的，也可能结果坏不到哪儿去。”我在一些场景下，也倾向于是个激进的人，坚信自己哪怕拿不准的想法是对的，排斥和自己不同的想法。这个缺点我要警惕起来。

[《如何把文章写流畅》](https://yihui.name/cn/2018/07/fluent-essay/)中说“修改可能是让文章流畅的原因之一，但我感觉最重要的因素还是胸中是否有一股不吐不快的气；如果有一股气顶着，文章铺开就会顺利一些。”我之前也有这样的观点，认为大多数文字都是能感觉到作者的气的，或孱弱，或雄壮，或严谨，或潇洒。可能字也如此，父亲说我的字练不好，是因为气不足，可能确实如此。此外此文还引用了《黑客与画家》中的文字“构思这种东西有一个特点，那就是它会导致更多的构思。...将一个构思束之高阁，甚至会限制新构思的产生。”

[《如何成为天才》](https://yihui.name/cn/2018/08/become-genius/)中引用了某作者关于如何成为天才的建议：

>You must clarify your goals, gain knowledge through spaced repetition, preserve health, work steadily, minimize stress, refuse interruption, and never resist sleep when tired.

还是很有启发性的。

[慢型思考](https://yihui.name/cn/2018/08/slow-thinker/)中说了一个经验性结论：如果想得到一个成熟的答案，用写的方式询问应该更靠谱。

[豪杰之人](https://yihui.name/cn/2018/08/hero/)中引用了苏轼《留侯论》的一段文字：

> 古之所谓豪杰之士，必有过人之节。人情有所不能忍者，匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒。此其所挟持者甚大，而其志甚远也。

[A Follow-Up Post on My Early Career Crisis Post (Finally)](https://yihui.name/en/2018/09/career-crisis-follow-up/) 这篇文章说了几个观点。

1. 自由与责任是相伴的，在享受多大自由的时候就应该警惕自己应该承担多大责任。作为领导者，如果意识到自己的员工/学生效率低下时，应该意识到做些改变，如果任务太难那么降低难度，如果没有意义那么转变方向。
2. 智勇多困于所溺。有天赋的人有可能更难承受付出努力的失败，或是在有多个选择时选择喜欢的，这两者有可能是阻碍。

对于有天赋的人，谢写了几点建议：

1. 激情是中性的。激情只有被目标小心地引导，才是巨大的力量；否则，就会让人疲于奔命，浪费能量。
2. 在某方面有天赋不是成功的充分条件，每个人的知识和时间都是有限的。
3. 学会做好重要的事，而不是自己喜欢的事。自己喜欢的事容易做好，但学习去做重要的事更有必要。
4. 你需要指出拖延的内在和外在原因，并从根本上解决拖延问题。

[The First Notebook War](https://yihui.name/en/2018/09/notebook-war/)讲了在Python的Jupyter大会上，邀请了一位嘉宾 Joel Grus，此人说他不喜欢Notebook，并列举了很多理由。有人形容这是“第一次Notebook大战”（不是Jupyter和R Notebook之战，而是Notebook和IDE之战）。之后谢根据 Joel Grus 所说的几个论点来一一解释，并将其映射到R世界里，看R是怎么解决问题的。**其核心观点是：R更善于数据分析，Python更善于软件工程。对于软件工程来说，Notebook绝对不是好工具，会培养很多坏习惯；但对数据分析来说，是个好的工具。**

- 新手们往往在以乱序执行Chunk的时候把程序搞乱，但只要培养起经常从头执行一遍的习惯就能避免该问题。
- Notebook的好处在于，人们能够近距离接触到代码和数据，及时得到反馈；并且程序（组）是可重复的。
- 在Jupyter里提到的一些问题，在R中能有效避免，因为Rstudio是一个“IDE+Notebook”的组合。
- Notebook是个临时做数据分析的环境，可能会很乱，不要把它给老板或顾客看。
- 如果想随时编译文档，那么使用xaringen的“无限月读”功能；
- 如果你想同时做软件工程和数据分析，那么就开发一个R包，而不是将代码堆在notebook中。

> people are often preoccupied with what they can do and don’t think about whether they should do it.

[Impact: Depth or Breadth?](https://yihui.name/en/2018/08/influence-depth-or-breadth/)中讨论了影响的深度和广度之间的抉择，谢提出了他的建议：先往深度走，广度只是时间的附加物。而且不要主动追求影响力，而是去解决痛点。所做的工作不要试图取悦所有人，尽力去取悦少数几个人（包括自己）。

[写教材](https://yihui.name/cn/2018/04/write-a-textbook/)文章中说：

> 如果你想掌握一门知识，那么最好的方式是去教这门课；如果你想成为一个好的讲师，那么就把一门课教两遍（总结并改进上一次的失败）。最好的学习方式是教学；能教给别人是理解知识的最低门槛。换句话说，如果你做不到能给别人解释清楚一件事，那你可能并不理解这件事。

确实很有启发。之前听说过一句话：如果你不能用简洁的话表达出来，说明你还没有完全理解它的意思。

> 我想，一般人不敢写书，一方面是心里没底或太谦虚，**另一方面也是因为不注意积累**。后一个原因是很可惜的。尤其是在学生期间，记了那么多笔记，考完试就扔掉，着实可惜。  
我推出 blogdown 的一个潜在目标就是让大家养成积累文字记录的习惯。

在用blogdown的不到一个月时间，确实好像慢慢培养了一种文字记录所思所感和工作经验、学习总结的习惯。相关的知识和解决方案都在自己的网站上记录，很放心也很满足。等自己多积累几年，说不定也可以写书了。