---
title: 申论
author: 王致远
date: '2018-10-29'
slug: shenlun
categories:
  - 找工作
tags:
  - 学习总结
---

# 1. 总论

考察对给定材料的分析、概括、提炼、加工。

在把握材料主旨和精神的基础上，形成并提出自己的观点、思路或解决方案，准确流畅地用文字形式表达出来。

## 小题：

- 概括、提炼；
- 分析：讲道理，摆事实；
- 加工：带文采属性；
- 解决实际问题能力：提出对策类；
- 阅读理解能力

**挖掘要点和整合要点是所有类型题目的基础。**

## 大作文：

- 政论文：综合分析；
- 策论文：提出和解决问题；

三个一致：

1. 中心思想；
2. 主题；
3. 写作文体；

大论文评价标准：文采，思想性。

# 2. 标准

## 小题

- 要点分；
- 结构分；有条理表达，遵循一定逻辑；
- 其他分；

最基本的标准：

1. 表达准确：找出关键词，捏成一句话表达；
2. 条理清晰；对要点分步、分层、分类整合；
3. 语言简洁；除了应用文不需要文采，字数不能超；

## 大作文

1. 语言流畅有文采；
2. 思想深刻有高度；

# 3. 答题

小题打草稿，大题写提纲

拿到试卷先读题目，按指定材料范围进行要点搜索，勾画要点。

通读材料要在写大作文之前，而不是拿到试卷后。

在指定材料的基础上适当扩充范围：

1. 指定材料前后的材料；
2. 权威表述：领导人讲话，文件，会议精神，大政方针
    - 规范语言：对照领导人语言和找出的要点，规范表述方式；
    - 提炼要点；
    - 判断依据；

## 要点概括与提炼

### 第一步：勾画要点：要做标记

- 问题W1
- 对策D1
- 意义Y1

### 第二步：罗列要点

在草稿纸上罗列，要保留序号、一目了然

罗列过程不用写要点文字，只写分类理由和序号。

### 第三步：整合要点

#### 分步

材料有明显的阶段性倾向

#### 分层

领导讲话的统领性要点，无法跟其他要点在同一层次进行分类，这个要点作为打层次，剩下的分类。统领性要点作为答案的总括句。

#### 分类

都在一个层面的，进行分类。

主体分类：

1. 政府；
2. 社会；
3. 学校；

维度分类：

1. 制度
2. 管理
3. 基础设施

整合最好在四类左右，注意每个大类的均衡。

### 第四步：书写成文

200字以上的题要简要阐述分类理由。

进一步整合：观察小点之间有没有逻辑关系，如果有，则用一句话表达出来。

**要点不要宏观和微观，要中观，或宏观+中观**

要点表述要有指向性，让判卷者知道你指向的是那段话。

### 第五步：删减字数

肯定是要费脑子的，如果很轻松，说明要点不全。

### 第六步：誊抄到答题纸上

不要在答题纸上直接作答，答案会很乱，被扣分。

## 大作文

1. 申论应当基于材料但高于材料；
2. 观点、思路侧重分析；解决方案侧重解决问题。由此分为政论文和策论文。

### 几个要点：

1. 大作文写作时间至少50分钟；
2. 结构要完整，由开头、分析、对策、结尾组成；
3. 必须是议论文。**论点论证论据缺一不可**。论据分为理论论据和事实论据。
4. 主题明确；
5. 条理清楚；

### 框架

#### 三段论

开头-分析段-三段并列的对策段-结尾

三段对策是并列关系

#### 起承转合

更容易写政论文，

- 起：提出问题；
- 承与转是对立或互补关系；
- 合：结合两者。

起承转合的优点：结构紧凑，浑然一体。

### 文体

#### 策论文

提出问题-分析问题-解决问题

5W1H

- 谁来做；
- 做事的方式；
- 做事的内容；
- 做到什么程度；
- 追求什么效果；

标题：开门见山，提纲挈领，在这个基础上美化标题。

开头：提出问题，问题只有一个，可以有多方面的表现。提出问题后需要写影响，证明文章的意义所在。

分析段：写意义和原因，重点是对原因的分析。

对策段：细化分解。

结尾段：拔高立意，站在全局来进行总结。积极向上，统一到党和国家、民族、人民事业上。

#### 政论文

政论文是提出观点。以下两种情况下政论文：

1. 题目中没有要求解决问题，但强调观点。
2. 务虚话题。

