---
title: 交通流问题文献综述(1)
author: 王致远
date: '2018-10-17'
slug: traffic-flow-literature-review-1
categories:
  - 论文
tags:
  - 学习总结
---

本篇文章服务于我的硕士毕业论文以及与之相关的准备投寄的小论文，也许可能也可以为未来在这方面更多的研究做积累。

# 英文文献

## 0. 开篇之作

### Analysis of freeway traffic time-series data by using Box-Jenkins techniques.

Ahmed, M.S., Cook, A.R., 1979. Analysis of freeway traffic time-series data by using Box-Jenkins techniques. Transportation Research Record 722, 1–9



## 1. Review 类

### 1.1 Short-term traffic forecasting: where we are and where we’re going.

#### 关键词：

- Short-term traffic;
- Prediction models;
- Intelligent Transportation System;
- Responsive alogorithms;
- Time series Analysis;
- Computational intelligence;

#### 从基于统计模型到数据驱动式算法的演变

At the same time, a novel research area, based on data driven empirical algorithms, has been systematically growing in parallel to the well-founded mathematical models that are based on macroscopic and microscopic theories of traffic flow (Wang and Papageorgiou, 2005; Yuan et al., 2012; Treiber and Kesting, 2012; Fowe and Chan, 2013; Kerner et al., 2013). This significant leap from analytical to data driven modeling has been marked by an overwhelming increase of Computational Intelligence (CI) – Data Mining (DM) approaches to analyzing the data. Researchers have moved from what can be considered as a classical statistical perspective (the ARIMA Family of models), to Neural and evolutionary computational approaches (Karlaftis and Vlahogianni, 2011)

#### 目前的研究局限

Short-term traffic forecasting based on data driven methods is one of the most dynamic and developing research arenas with enormous published literature. Interestingly, however, **most of the research has concentrated on ‘testing’ alternative modeling approaches on short-term traffic data**, possibly **because of the data’s ready availability and the relative ease of applying many of the available analytical approaches.** This concentration leaves a number of important questions and challenges unaddressed or, relatively to the rest of the literature, under researched.

#### 提出了下一个十年短时交通流领域的10个挑战：

Challenges:

1. Developing responsive algorithms and prediction schemes Transportation; 响应式算法和预测框架（例如交通拥堵或极端天气）
2. Freeway, arterial and network traffic predictions; 路网预测。数据驱动式算法研究时空相关性。
3. Short-term predictions: from volume to travel time; 从交通量到旅行时间
4. Data resolution, aggregation and quality; 数据粒度与聚合方法问题
5. Using new technologies for collecting and fusing data; 数据多源采集与融合问题
6. Temporal characteristics and spatial dependencies; 时间特征和空间依存度
7. Model selection and testing;
8. Compare models or combine forecasts;
9. Explanatory power, associations and causality Until; 可解释性、关联性和因果关系。随着响应式算法的发展，模型的可解释性越来越重要。特别是天气等外部变量的可解释性。与经典统计学的协同可以增强可解释性。
10. Realizing the full potential of artificial intelligence Artificial

#### 关于第7条模型选择和检验的深入

模型选择的判别标准：

The general approach followed in short-term traffic forecasting is to select the model that provides the most accurate predictions based on a collected dataset and **regardless of the traffic’s underlying statistical characteristics** (e.g. non-stationarity, volatility, nonlinearity and so on), or **whether certain modeling assumptions are violated or unrealistic** 
关于非平稳性和非线性性：

The selection of the proper modeling approach should be largely determined by the non-stationary and nonlinear features of the spatiotemporal evolution of traffic (Vlahogianni et al., 2006). Several classical or more advanced tests of non-stationarity and nonlinearity have been applied to traffic flow (Karlaftis and Vlahogianni, 2009 and Vlahogianni and Karlaftis, 2011, 2013). Recent evidence in disciplines such as econometrics and finance, has demonstrated the need to jointly consider non-stationarity and non-linearity in producing consistent short-term forecasting models.

对模型残差的检验

Most researchers place larger emphasis on discussing the findings and neglect the need to account for the quality of their model (in terms of **the properties of the error**), using even the most popular statistical diagnostics. This is of outmost importance in classical statistical modeling as a model of adequate structure should have white noise residuals (Washington et al., 2010). This implies that any ‘‘strong’’ properties in the error term – including serial correlation, volatility and so on – may indicate specification bias that can be attributed to omitted variables or misspecification of the functional form (inadequate complexity of the structure). In transportation time series applications, most artificial intelligence approaches (e.g. Neural Networks) rarely incorporate any **testing of the properties of the error and the model specification 模型诊断**. An exception is the work of Chen et al. (2012) that tested the properties of the errors of the autoregressive models developed for traffic flow forecasting. Vlahogianni and Karlaftis (2013) applied popular goodness-of-fit tests for serial dependence（自相关性）, normality（正态性）, homoscedasticity（同方差性） and non-linearity（非线性） on neural network time series models.


### 1.2 Short-term traffic forecasting: overview of objectives and methods

到2003年的研究进展

Vlahogianni, E.I., Golias, J.C., Karlaftis, M.G., 2004. Short-term traffic forecasting: overview of objectives and methods. Transportation Reviews 24 (5), 533–
557.

## 9. 待找原文

### 9.1 基于人工智能的短时交通流预测(综述性)

#### 引用

Van Lint, J., Van Hinsbergen, C., 2012. Short term traffic and travel time prediction models, in artificial intelligence applications to critical transportation issues. In: Transportation Research Circular. National Academies Press, Washington, DC.

### 9.2 交通流聚类

#### 链接

[springer](https://link.springer.com/article/10.1007%2Fs12205-012-1233-1#citeas)

#### 引用

Xia, J., Huang, W., Guo, J., 2012. A clustering approach to online freeway traffic state identification using ITS data. KSCE Journal of Civil Engineering 16 (3),426–432.

#### 摘要

Online traffic state identification plays an important role in achieving the potentials promised by Intelligent Transportation Systems (ITS) on various traffic applications, e.g., real time traffic monitoring systems. Traditional approaches have shown the limitations in either obtaining the necessary pre-determined information or having difficulties in their online implementation. This paper introduces an online agglomerative clustering procedure for freeway traffic state identification using ITS data, represented by three traffic condition variables of flow rate, speed, and occupancy. An optimal fit of the statistical characteristics is provided by maximizing the intra-cluster data point distances and minimizing inter-cluster data point distances through a joint utilization of the **Bayesian Information Criterion** and the **ratio of change of the dispersion measurements**. Test results show that the identified freeway traffic states through the proposed procedure are reasonable and consistent with the common understandings on freeway traffic operating conditions.

### 9.3 基于RBF神经网络的聚类

Park, B. (1998). “Clustering-based RBF neural network model for shortterm freeway traffic volume forecasting.” Proceedings of the 5th International Conference on Applications of Advanced Technologies in Transportation Engineering, Newport Beach, California, pp. 280–287.

### 9.4 交通流聚类

Xia, J. and Chen, M. (2007). “A nested clustering procedure for traffic condition classification.” Journal of Computed-Aided Civil and Infrastructure Engineering, Vol. 22, No. 6, pp. 430–437.

### 9.5 模型评价指标的适应性

Chandra, S.R., Al-Deek, H., 2008. Cross-correlation analysis and multivariate prediction of spatial time series of freeway traffic speeds. Transportation Research Record 2061, 64–76.

# 中文文献