---
title: 行测(1)——数量关系题
author: 王致远
date: '2018-10-23'
slug: xingce-1
categories:
  - 找工作
tags:
  - 学习总结
---

# 数字推理题

## 1. 多级数列

对相邻两项进行四则运算（**做差，做商，做和**），进行一次或两次运算。

若呈平稳递增趋势，可尝试使用倒三角法寻找规律。

有时做差和做商交替使用。

结果可能是等差或等比数列，也可能是质数数列。

## 2. 分组数列

- 奇数项和偶数项分别呈一定规律（有时候一组明显，一组不明显，不明显的依赖明显的）；
- 相邻分组数列（两两分组或三三分组）

## 3. 递推数列

加减乘除倍方

- 看趋势：从大的数字开始看；
- 做试探
- 修正项
    - 修正项是简单数列
    - 修正项与数列前项相关

数列中间出现一个莫名其妙的负数，可考虑递推做和或者分组作和。
    
## 4. 幂次数列

- 幂次数列的修正数列
- 幂次数列与等差数列或指数数列的和
- 幂次数列被正负交替数列修正

## 5. 分数数列

- 分组看待：分别观察分子分母规律；
- 约分：把非最简分数化为最简分数；
- 广义通分：将分母（或分子）化成相同的数；
- 有理化：当分子或分母含有根式时，将其有理化；
- 反约分：将分子或分母适当扩大倍数；
- 整数化分数。

# 数学运算题

## 1. 比值混合问题

> 售价15元/千克的白糖，取其中一部分加水溶解形成浓度为20%的糖水12kg，然后将剩余白糖全部加入溶解，变为25%，问购买白糖多少元钱？

知道单位价格，只需要算白糖一共多少克千克。

先取出白糖12*0.2=2.4千克，设剩余白糖x

$$\frac{x+2.4}{12+x}=0.25$$

解得x=0.8，一共3.2kg，总价3.2*15=48元。

### 十字交叉法

多的量和少的量保持平衡

部分量比值 | 总体量比值 | 交叉做差 | 实际量之比

- 第三列为前两列交叉做差所得
- 第三列比值与第四列比值相等
- 第一列做差等于第三列做和

上一问题可看作浓度为20%糖水和浓度为100%的糖水混合为浓度为25%。解得x=0.8.

## 2. 年份问题

> 某人出生于20世纪70年代，某年他发现从当年起连续10年自己的年龄均与当年年份数字之和相等（出生当年算0岁）。问他在一下哪一年时，年龄为9的整数倍？

首先算出他是哪年出生的。只有可能是从1990~1999年这十年满足，所以他是1971年人。所以是2007年。

**计算年份与生日时，不需要+1，直接做相加减即可。**

## 3. 日期问题

> 某办公室四人在工作日每天轮流打扫卫生，每周一打扫卫生的人给植物浇水。7月5日周五轮到小玲打扫卫生，下次小玲给植物浇水是哪天？

5个工作日，4个人打扫，则对每个人来说，值日的星期数每次减1。小玲是星期5,4,3,2,1. 则是3周多3天，共24天，则是7月29日。

> 某政府机关甲乙两部门发布消息，甲部门每隔两天，乙部门每个三天，节假日无休。问甲乙两部门一个自然月内最多几天同时发布？

甲每隔2天，则每3天发一次，乙每隔3天，则每4天发一次；公倍数为12，一个月最多3次。

## 4. 最小公倍数问题

> 200mL沐浴露每箱20瓶，500mL沐浴露每箱12瓶，分别定价14元和25元，货品卖完后收入相同，问200mL最少几箱？

$$20*14=280，12*25=300$$

则找280和300的最小公倍数，他们的最大公约数是20，则200mL应该多乘个15.所以有15箱。

## 5. 概率类问题

> 3道每道10分甲类题，2道每道20分乙类题，1道30分丙类题。参赛者随机选择部分试题并全部答对，最终得分70分，问未选择丙类题的概率是多少。

$$x+2y+3z=7$$

- 如果z=0，则x=3,y=2，只有一种情况；
- 如果z=1
    - 可以是y=2,x=0，只有一种情况；
    - 可以是x=2,y=1，有C32*C21=6种情况；
    
所以是1/8

## 6. 成本利润问题

$$成本=售价/(1+利润率)\\折扣=实际售价/定价$$

> 老王投资一件艺术品，上涨50%，为尽快出手，老王按市价8折出售，扣除成交价5%的交易费后，与买进时相比赚了7万元。

**题干中出现大量百分数，用赋值法**

假定进价100，利润50，定价150，八折后120，交易费6，实际售价114，净利润14，相当于7万，所以进价100相当于50万。


## 7. 排列组合问题

$$C_n^m=\frac{n!}{m!(n-m)!}$$

$$A_n^n=n!$$

$$A_n^m=\frac{n!}{(n-m)!}$$

#### 错位重排

> 某集团5个分公司分别派出1个人去总部培训参加培训，培训后再将5人随机分配到5个分公司，每个分公司只分配1人。问有且仅有一人在培训后返回原公司概率

总情况：5个人全排列，A55=120.

先选一个人到原公司，有5中情况；剩下4人错位重排，错位重排数为9，总情况45；

所以45/120=37.5%

**错位重排：将n各元素重新排列，使每个元素都不在原来位置上。**

D1=0，D2=1，D3=2，D4=9，D5=44

$$D_n=(n-1)(D_{n-2}+D_{n-1})$$

#### 捆绑法

先将相邻元素视作整体参与排序，然后考虑这个整体内部各元素间顺序

> 4对情侣排成对买演唱会门票，每对情侣必须在一起，共有多少种不同的排队顺序。

每对情侣捆绑在一起，全排列为24.每对情侣都有2种可能。所以为

$$24*2^4=384$$


####  插板法

>把12棵同样的松树和6棵同样的柏树重载道路两侧，每侧种9棵，妖气每侧的柏树数量相等且不相邻，且道路起点和重点两侧种植的都必须是松树。问多少种种植方法。

6棵松树，起点和终点都是松树，只考虑中间5个空，从5个空中选出3个种柏树。每一遍的种植方式为$C_5^3=10$，总种植方式为100.

## 8. 图形面积计算问题

充分利用相似三角形的性质：

1. 相似三角形对应角相等，对应边成比例。
2. 相似三角形的一切对应线段(对应高、对应中线、对应角平分线、外接圆半径、内切圆半径等）的比等于**相似比**。
3. 相似三角形周长的比等于相似比。
4. 相似三角形面积的比等于相似比的平方。

## 9. 生产线问题

三要素：时间，效率，工作量

当题目中值给出时间时，赋值总工作量，根据总量和时间求出效率，然后研究效率的分配方法。总工作量赋值成时间的最小公倍数。

当效率成倍数时，赋值效率。

> 甲组单独做需要10小时，乙组单独做需要15小时，现两组一起做，期间乙组休息了1小时40分钟，完成时甲组比乙组多做300个，问一共多少个？

甲、乙每小时分别完成总工作量1/10,1/15，甲在乙休息的1小时40分（合5/3小时）中完成了5/3\*1/10=1/6，则甲乙同时工作时共同完成5/6，则甲乙共同工作时间为5/6/(1/10+1/15)=5小时，在此过程中甲比乙多做5\*(1/10-1/15)=1/6，则全过程甲比乙多做1/3，合300个，所以一共900个。

> 工厂有5条效率不同的生产线，某项目如果任选3条生产线一起加工，最快需要6天，最慢需要12天；5条一起加工，需要5天。如果所有生产线产能扩大一倍，任选2条生产线一起加工最多需要多少天？

设工作总量为6和5的最小公倍数30.设生产效率从高到低为ABCDE。任选两条生产线，则选DE的加工时间最长。

A+B+C=5

A+B+C+D+E=6

则D+E=1，产能扩大一倍为2，则需要15天。

## 10. 空间点与平面关系问题

> 某次军事演习中，一架无人机对三个地面目标侦查。一直三目标点在地面上的连线为直角三角形，两个点之间最远距离为600.问无人机同时与三个点保持500米距离时，其飞行高度为多少米？

空间中到平面上三点距离都相等的点在三角形的外接圆圆心。直角三角形外接圆圆心在斜边中点。所以飞行高度为400。

## 11. 尾数计算问题

乘方尾数：底数只留个位数，指数除以4留余数，余数为0换成4.所得新数的位数即为原数的位数。

> 2012的2012次方尾数

底数末尾数字为2，指数2012能被4整除，只需计算2的4次方，尾数是6.

## 12. 因子分析

所谓因子，即是公约数。**加减法或乘法计算结果一定包含每部分的公共因子。除法计算时公共因子被消掉以降低计算难度。**

常见的因子分析是3因子或9因子判定

> 1005\*10061006-1006\*10051005=0

1005与10051005都是3的倍数，结果也一定是3的倍数。

## 13. 基本公式

平方差公式：

$$a^2-b^2=(a+b)(a-b)$$

裂项公式：

$$\frac{b}{m*(m+a)}=\frac{b}{a}(\frac{1}{m}-\frac{1}{m+a})$$

分母有理化：

$$\frac{1}{\sqrt{n+1}+\sqrt{n}}=\sqrt{n+1}-\sqrt{n}$$

## 14. 整体代换法

重复出现的部分看作一个整体，用字母代替；先不计算整体内部的细节，而是采用整体计算的方法

## 15. 定义新运算

## 16. 集合类问题

$$|A\cup B| = |A| + |B| - |A\cap B|$$

$$|A\cup B \cup C| = |A| + |B| + |C| - |A\cap B|-|B \cap C|-|A\cap C| + |A\cap B\cap C|$$

> 某班60人，参加物理竞赛30人，数学竞赛32人，两科都没参加20人。问同时参加物流和数学竞赛多少人。

设两科都参加x人。

$$32+30-x=60-20$$

> 某公司招聘员工，按规定每人至多报考两个职位，共42人报名。甲乙丙三个职位报考人数分别是22,16,25.其中同时报甲乙人数为8，同时报甲丙人数为6，问同时报乙丙人数为多少。

设同时报乙丙人数为x

$$42=22+16+25-8-6-x+0$$

#### 三集合概念型

$$满足集合总数=满足一个+满足两个+满足三个$$

$$满足两个=A\cap B+A\cap C+B\cap C-3A\cap B \cap C$$

$$满足三个=A\cap B \cap C$$

$$总数=A+B+C-满足两个 -2*满足三个$$

> 调查对象中179使用搜索引擎，146从官方网站，246人从社交网络获取，同时使用三种有115人，使用其中两种24人，另有52人三种都不使用，问共发出多少问卷。

$$179+146+246-24-2*115=总人数-52$$

## 17. 行程问题

$$路程=速度*时间$$

$$路程比例=速度比例*时间比例$$

- 时间相同，路程比等于速度比；
- 速度相同，路程比等于时间比；
- 路程相同，速度比等于时间反比。

等距离平均速度公式：

$$v=\frac{2v_1v_2}{v_1+v_2}$$

以不同速度两次通过某特定路程

等间隔发车时间公式，t1与t2经历路程相同

$$发车时间间隔=\frac{2t_1t_2}{t_1+t_2}$$

#### 火车过桥公式：

$$桥长+车长=火车速度*过桥时间$$

#### 相遇问题：

> 客车与货车分别从东西两站相向而行，客货车速度比为4:3，两车相遇后，客车速度减少10%，货车速度增加20%。当客车到达西站时，货车离东站还有17公里。问东西站相距多少公里？

**题干中出现比例特征，用赋值法简化计算**

V客=4，V货=3.相遇时客车路程为4份，货车为3份，总路程7份。相遇后，V客=3.6，V货=3.6.当客车到达西站时，路程为3份，此时货车距离车站还有1份距离，为17km，所以总路程为7*17.

#### 追及问题：

$$追及距离=(V_1-V_2)*追及时间$$

#### 队伍行进模型

队首到队尾：

$$队伍长度=(人速+队伍速度)*时间$$

队尾到队首：

$$队伍长度=(人速-队伍速度)*时间$$

> 一支600米长的行军队伍，队尾通信员用3分钟跑到队首，又在队伍休息时间以同样速度跑回队尾用2分24秒，如队伍和同心圆匀速前进，则同心圆从队首跑回队尾需要多久？

设通信员速度为v1，队伍速度为v2.

$$600=(v_1-v_2)*3\\600=v_1*2.4$$

解得v1为250，v2为50.则返回队尾时间维600/(250+50)=2分钟。


#### 直线型往返相遇

相遇n次，路程和为(2n-1)个全程


#### 流水行船问题

$$顺流航程=(船速+水速)*顺流时间\\逆流航程=(船速-水速)*逆流时间$$

> 一支装有动力桨的船，其单靠人工划船顺流而下的速度是水速3被。先船靠人工从A顺流到B，原路返回时只开动力桨，用时比来时少2/5.问在静水中动力桨是人工划船速度多少倍。

**涉及倍数关系，用赋值法**。设水速为1，则顺水速度为3，人工划船速度为2.

逆流时，顺水时间:逆水时间=1:(1-2/5)=5:3，则顺水速度:逆水速度=3:5，所以逆水速度为5，动力桨为6.比为6:2即3倍。


