---
title: 读《心流》（更新中）
author: 王致远
date: '2018-10-04'
slug: read-flow
categories:
  - 读书
tags:
  - 读书笔记
output:
  blogdown::html_page:
    toc: true
---

本书的一大目标就是发掘各种方法，以便把理性的细节转变成具有个人意义的游戏，导向最优体验。

# 0.序言

## 0.1 自造内心秩序之途

### 幸福源自内心的秩序

> 精神分裂症患者会不由自主地注意到所有不相干的刺激，接受所有资讯。而很悲惨的是，他们并没有控制任何事物进出意识的能力。

> 轻度的悲观使我们做事前三思而后行，但大部分时间乐观更好。

> 面对太多的，包括负面的信息，你必须找到一项能长久地凝聚自己注意力的活动。这样你面对众多信息时便有了轻重之别，乃至屏蔽若干信息。

> 幸福不是人生主题，而是附带现象。

> 幸福是你全身心地投入一桩事物，达到忘我的程度，并由此获得内心秩序和安宁时的状态。

> "好的生存状态"要兼括生理满足与精神系统中的秩序。

### 负熵与精神熵

> 写作是在情绪紊乱中塑造秩序的一种疗法。

> 能造就心流的活动，大多还需要当事者**自觉自愿，乐在其中**。

> 当挑战与技能匹配时，有了心流。当目标大大高过技能时，产生**焦虑**；当技能高过目标时，产生**厌倦**。**正是在技巧提高、目标上调的过程中，当事者感受到了成长的乐趣。**

### 自寻目标的时代

> 自得其乐：拥有自足目标的自我。

> 拒绝外部奖励的最有效的方法是建立“内奖”，即**选定你的目标，在追随目标的努力中，获得内心的秩序和成长的乐趣**，这就是内奖，就是自我奖励。

> 开始时靠目标证明努力的必要，到后来却变成靠努力证明目标的重要性。

> **一个人若能从独处中找到乐趣，必须有一套自己的心灵程序**，不需要靠文明生活的支持——亦不需要借助他人、工作、电视、剧场规划他的注意力，就能达到心流的状态。

### 机器人驱赶我们去游戏

> 人类创造出游戏，目的就是调整心情，变低迷为亢奋，变涣散为专注。

> 控制内心所发生的一切。

> 美育可以让一个人在其精神世界中愉快地领受一种秩序。

> 智勇多困于所溺。

# 第1章 心流，快乐的源泉

## 1.1 人何时最幸福

> 只有在不计较好坏、全身心投入生活的每一个细节时，才会觉得幸福，直接去找反而不会奏效。

> 每个人毕生都面临着不计其数的挑战，而每次挑战都是一个获得幸福的良机。

> 掌控生命殊非易事，但日积月累的最优体验会汇集成一种掌控感，是一种能自行决定生命内涵的参与感。

> 心流即一个人完全沉浸在某种活动中，无视其他事物存在的状态。

> 最优体验有赖于时时刻刻用意识控制周遭事物，而要达到这种境界，唯有靠个人的努力与创意。

> 这种为克服挑战而奋斗的阶段，就是一般人认为的一生中最愉快的时间。任何人只要能够控制精神能量，并将它专注于既定目标，就一定能有所成长、精益求精。借此不断练习自己的技巧，迎接更艰巨的挑战，使自己更加出类拔萃。

## 1.2 人类不满的根源

> 追求内心和谐，唯有从掌控意识着手。

> 不能享受现在，也因此与知足的快乐绝缘。

> 他们最大的长处就是，对自己的生活掌控自如。

## 1.3 文化编织的神话

> 任何文化的主要功能就是保护其子民不受混沌之扰，同时灌输一个信念：自我很重要，并且个人终究能成功。

> 盲目信任文化编织的神话，失败时会产生同样极端的幻灭感。

> 当人们相信进步是必然的，生活理应轻松愉快时，就很容易丧失面对困顿的勇气与决心。一旦他们发现从前相信的一切不尽可靠，往往会一股脑把所有信念抛弃。没有文化价值的支持，人们就陷入了焦虑与冷漠的泥淖。

> 内在秩序的缺失，表现在某些人所谓的存在焦虑或存在恐惧等主观状况上。基本上，它是一种对生存的恐惧，一种生命没有意义、不值得继续的感觉。

## 1.4 善用自己的体验

> 爱默生说：我们对生活有种种期许，却从未真正生活过。

> 弗洛伊德及其他心理学家指出，文明就是建立在压抑个人欲望基础上的。社会成员不论乐意与否，都被迫接受既定的习惯与技能，否则就不可能维持社会秩序和复杂的分工制度。个人社会化是必然的；社会化的真谛在于使个人依赖社会的控制，并对赏罚有既定的反应；社会化的最高境界就是使每个人都完全认同社会秩序，根本不想触犯任何规则。

> 人的每个欲望——从性欲到侵略，从寻求安全感到接受改变——几乎都成为政客、教会、企业及广告界控制社会的手段。

> 进食的快乐是为确保身体得到充足营养，性爱的快乐则是鼓励生殖的手段，它们实用的价值凌驾于一切之上。

> 跟随基因的反应，享受自然的乐趣，并没有什么不好，但我们应该认清事实真相，在必要的时候，按照自己的优先顺序，做自己的主人。

> 问题是最近盛行把内心的感觉当作发乎真性情的行为准绳。

> 如果我们不加诘问就服从基因和社会的控制，不啻就放弃了对意识的控制，成为非人性力量的玩物。如果无法抗拒食物或酒精的诱惑，或无时无刻不欲念缠身的人，就无法自由控制内在的心灵。

> 不能在必要时反抗基因指示的人往往很脆弱，他们非但不能根据个人的目标决定行动方向，反而被肉体的欲望牵着鼻子走。摆脱社会制约的首要任务就是控制本能的冲动，因为只要我们凡事跟着感觉走，一举一动就不难预测，别人就很容易利用我们的好意，达到他们自私的目的。

> 彻底社会化的人，只追求周遭他认定应该期望的东西——往往也是与天性密切结合的欲望。他可能会经历许多难能可贵的事，但因这些事与他的欲望不符，他就会完全忽略它们。

> 剥削我们的精力以逞其私欲，使我们沦为社会制度的附庸。

> 另建一套自己的目标，最重要的步骤就是时时刻刻挖掘每一事件中的回馈。

> 服从社会根据生物倾向而设计的“刺激-反应”模式，就是受外界所控制。

## 1.5 释放内在的生命

> 弗洛伊德指出，“本我”与“超我”是争夺心灵控制权的两大暴君，前者是基因的奴隶，后者则与社会沆瀣一气，两者都算“外界”。相对应的是“自我”，代表一个人在现实环境中的真正需要。

> 瑜伽徒的严格心理自律，禅宗信徒培养源源不断的自发性，目的都在于摆脱混沌的威胁和生理冲突的严重制约，从而释放内在的生命。

> 解放意识的知识或智慧不能积累。当知识应用于修正我们的习惯与欲望时，就慢如牛步，令人痛苦不堪了。

> 各派哲学都有专属于所创生环境的成分，这些额外的成分若不能从基本要素中剔除，通往自由的路上就不免要长出许多莠草。

> 每一时代，在时代更迭频繁时，甚至每隔几年，培养独立意识所需的条件就会改变，必须重新加以考虑和组合。

# 第2章 控制意识，改善体验的品质

> 历史上某些文化认为，一个人除非学会控制思想和感觉，否则不能算是一个完整的人。

## 2.1 意识的内涵

> 培养毅力应该从建立意识的秩序、控制感觉与思想着手。

> 唯有投注所有时间与心力，提升操纵内在体验的技巧，方能成为专家。

> 意识是我们能感觉到，而且有能力引导其方向的事件，诸如情绪、感觉、思想、企图等。

> 意图把注意力从其他事物导向目标，使精神集中于特定的刺激上。

> 先天遗传或后天得来的意图，会按目标的高低排定重要性。

## 2.2 意识的极限

> 思绪必须井然有序，否则就会混乱。这些活动都会耗费大量的注意力。

> 看电视时注意力、技能的运用、思路的清晰程度与精力都陷入最低潮。

> 控制意识最明显的指标就是能随心所欲地集中注意力，不因任何事情而分心。

> 注意力有无数种运用方法，可以使生活变得更丰富，但也可能更悲惨。

> 他们训练自己的注意力，学习处理易受忽略的信号。

> 应该把注意力视为一种“精神能量”。它是完成工作不可或缺的能量，在工作中会损耗。我们通过这种能量的应用，创造自我。

> 注意力是一种受我们控制、随我们使用的能量变化而改变，也是改善体验品质的最重要的工具。

## 2.3 关于自我

> 这个“自我”代表我们点滴建立起来的目标的先后次序。

> 注意力塑造自我，也被自我塑造。

> 所有过程乃是靠自我（即整个目标系统的心理互动）衔接的。

## 2.4 内在失序

> 内在失序，也就是资讯跟既定的意图发生冲突，或使我们分心，无法为实现意图而努力——是对意识极为不利的影响。

> 与个人目标相冲突的资讯侵入意识后，视目标的重要性与威胁的大小而定，某些程度的注意力必须腾出手来消除危机，用于处理其他事物的注意力就相对减少了。

## 2.5 意识井然有序

> 积极的反馈强化了自我，使我们能投入更多注意力，照顾内心与外在环境的平衡。

> 最优体验出现时，一个人可以投入全部的注意力，以求实现目标；没有失序现象需要整顿，自我也没有收到任何威胁，因此不需要分心防卫。

> 越来越完美的自我控制，产生一种痛快的感觉。你不断逼身体发挥所有的极限，直到全身隐隐作痛；然后你会满怀敬畏地回顾自我，回顾你所做的一切，那种佩服的感觉简直无法形容。它带给你一种狂喜，一种自我满足。只要在这种战役中战胜过自己，人生其他战场的挑战，也就变得容易多了。

## 2.6 自我的成长

> 复杂性是由两种广泛的心里过程造成的——“独特化”与“整合”。

> 每经历一次心流，个人就变得更加独特、更难预测，并拥有非凡的技能。

> 复杂性还有另一度空间——个独立部分的整合。

> 只有独特化（未经整合）的自我，虽然也能获得极高的成就，但有陷入自我中心的危险；同样，一个人的自我若是完全建立在整合上，固然也能有良好的人际关系和安全感，却缺乏独立的个性。

> 我们只有在不掺杂其他动机，为行动而行动时，才能学会做一个比原来的自己更复杂的人。

# 第3章 享乐与乐趣

## 3.1 幸福的假象

## 3.2 享乐与乐趣

> 享乐是意识中的资讯告诉我们已经达到生物程序或社会制约的要求时，所产生的一种满足感。

> 睡眠、休息、食物与性，都属于恢复“均衡”的体验，在肉体需求引起精神熵后，重整意识的秩序。它们并不能带动心灵的成长，也不能增加自我的复杂性。换言之，享乐虽有助于维持意识的秩序，却无法在意识中创造新秩序。

> 乐趣具有向前发展的特性，并蕴含新鲜感和成就感。享乐无需耗费精神能量，但乐趣必须运用高度的注意力。

> 每个充满乐趣的学习经验，都使孩子不断发展的自我日趋复杂。

> 太过于自满的人往往要求附带的报酬，才肯在新目标上投注精神能量，以至于无法再从人生中汲取任何乐趣，唯一的积极体验只剩下享乐了。

> 如果要控制体验品质，就必须学习从每天的生活中创造乐趣。

## 3.3  构成心流体验的要素

> 1. 面临一份可完成的工作；  
2. 必须能够全神贯注于这件事；  
3. 有明确的目标；  
4. 有即时的反馈；  
5. 能深入而毫不牵强地投入到行动之中；  
6. 能使人觉得自由控制自己的行动；  
7. 进入“忘我”状态，但心流体验告一段落后，自我感觉又会变得强烈；  
8. 时间感会改变。

> 寻求挑战的简单方法就是投入一个竞争性的环境。竞争是发展复杂性的捷径。竞争只有在它以使个人技巧臻于完美为目标时，才有乐趣。

> 通过有规律的行动，把意识规范得更有秩序。

> 当情况要求一个人运用相关技巧来应付挑战时，这个人的注意力就会完全投入，不剩一丝精神能量处理任何与挑战无关的资讯，而完全集中于相关的刺激上。

> 心流体验之所以能达到完全的投入，是因为目标明确，而且能得到即时的回馈。如果选择的目标微不足道，成功的乐趣也几近于零。

> 除非一个人学着去确立目标，辨认与评估回馈，否则无法从任何活动中发掘乐趣。

> 这就导致在一般状态下，心灵常会受到精神熵的突如其来的干扰。

> 所有对心流的典型描述都提到“控制感”，不像日常生活，时时要担心事态会失控。

> 冒险专家的乐趣并非来自危险本身，而是来自他们使危险降至最低的能力。只有在个人力量能左右结果时，才能确知自己握有控制权。

> 当一个人沉溺于某种有乐趣的活动，不能再估计其他事时，它就丧失了最终的控制权，亦即决定意识内涵的自由。

**智勇多困于所溺**

> 心流中，没有自我反省的空隙。

> 要达到这样的自我成长，必须能提供相当的行动机会，并且在技巧方面不断要求精进。

## 3.4 目标不假外求

> “自成目标”指的是做一件事不追求未来的报酬，做这件事本身就是最大的回馈。

> 某些违反我们意愿、不得不去做的事，逐渐也会呈现它固有的报偿。

> 很多活动的乐趣都不是自然天成的，它需要我们在开始时做一些并非心甘情愿的努力。一旦个人技巧得到回馈，互动开始，自然就会产生值得的感觉。

> 通常休闲有助于工作后的放松，但这段时间往往只是被动地吸收资讯，没有运用任何技巧去开发新行动的契机，结果生活只是由一连串无聊和焦虑的感受所组成，个人全无控制力。

> 心流体验跟世间所有事物一样，不可能绝对的好。它的好在于它具有使人生更丰富、更紧凑、更有意义的潜力，在于它能加强自我的力量与复杂性。

> **永远警戒是自由必须付出的代价。**一定要时时刻刻重新评估我们所做的一切，不要让习惯和过时的智慧蒙蔽、阻碍了进步的可能。

# 第4章 如何在日常生活中寻找心流

## 4.1 心流活动

> 学习新技巧，有一定的目标，提供回馈，使控制成为可能。

> 带来乐趣的活动可以分成四类：一是竞争类；二是投机类；三是眩晕类；四是模仿类。

> 只有注意力集中于活动本身时，竞争才能改善体验。

> 投机性游戏能带来乐趣，因为它能产生一种控制不可知的未来的错觉。

> 眩晕是改变意识的最直接方法。任何能改变我们感知现实的活动，都充满乐趣。

> 模仿经由幻想、扮演或假装，使我们自觉超出现实的限制。

> **心流活动的共同点：带来一种新发现、一种创造感，把当事人带入新的现实。**它促使一个人有更好的表现，使意识到达过去连做梦都想不到的境界。

> 就因为这种充满动力的特性，使心流成为成长与发现的源泉。我们不可能长期做同种层次的事依然觉得乐趣无穷。我们不是因此感到厌烦，就是饱受挫折，然后寻求乐趣的意愿就会促使我们拓展自己的技巧，或发掘运用技巧的新方向。

> 游戏规则的愿意是引导精神能量遵循能带来乐趣的模式，但它们能否发挥效用，决定权仍在我们。

> 我们所谓的宗教，实际上就是创造意识秩序的最古老、最野心勃勃的尝试。

## 4.2 心流与社会文化

> 不能用一套价值标准去评判另一套价值标准。由于任何跨文化的价值评判，都必然迫使所评判的文化暴露于另一套全然陌生的价值标准之下，因此根本无从比较。

> **当周遭的一切都在意料之中时，生活就没有了挑战；没有挑战，生命就没有意义了。**

> 美国杰斐逊总统和中国毛泽东主席都相信，每一代人为了主动参与控制他们生活的政治体系，都必须发起一场革命。

> **文化是对混沌的一种防御。**文化制定规范，推动目标，建立信念，帮助我们克服生存的挑战；同时，文化必须把很多细枝末节的目标与信念排除，因而也局限了发展的可能性。**唯有把注意力限制在一组特定的目标与手段上，才能在自行创造的疆界里，进行毫不费力的行动。**

> 一种文化若能成功确立起一套目标和规则，不但能吸引其成员，又能配合他们的技巧层次，使他们能经常感受到强烈的心流，那么它就更接近游戏了。

> 纳粹的目标简单，回馈明确，并且为处于焦虑与挫折中的人们带来了解脱及重新投入生活的机会。

> 当一群人奉行一套能为他们带来更多人生乐趣的目标与原则时，别人很可能必须为此付出代价。

> 最优体验的第二个条件：一个人重组意识达到心流的能力。有些人不论到哪里，都能自得其乐；有些人即使美景当前，仍感到枯燥乏味。

## 4.3 自得其乐的性格

> 无法集中精神，每件事都分不出轻重，就导致病人享受不到一丁点乐趣。

选择困难症的原因是没能建立意识秩序，即价值观，结果是迷茫、焦虑。

> 控制不了精神能量的人，既无法学习，也找不到真正的乐趣。

> **当什么可以或不可以做已混淆不清时，人的行为举止就变得反复无常、没有意义，靠社会规则建立一时之需的人就会感到焦虑。**

> 当社会陷于失范状态时，一件事情是否值得投入精神能量就变得不清不楚，很难产生心流；当社会为疏离所苦时，问题则出在个人没有办法把精神能量投注于自己真正想要追求的目标上。在个人层次上，失范对应于焦虑，疏离则对应于厌倦。

当代社会阶级越来越固化，奋斗是否还有意义已经越来越模糊。同时随着政府、企业、个人的负债率提高，经济依靠投资驱动的模式已逐渐不可行，只能向依靠消费转型。未来会有越来越多的青年人感觉到焦虑和疏离。

> 有助于产生最优体验家庭环境的五个特点：  
1. 清晰：目标与回馈毫不含糊；  
2. 重视：父母对孩子目前所做的事，感受与体验有浓厚的兴趣；  
3. 选择：孩子有自己的选择，自己承担后果；  
4. 投入：孩子有信心放开自卫的护盾，全心全意去做感兴趣的事；  
5. 挑战：父母为孩子安排复杂渐进的行动机会。  

> 在秩序不佳的家庭，孩子的大部分能量都浪费在层出不穷的谈判与争执，以及不让脆弱的自我被别人的目标所吞噬的自我保护上。

## 4.4 在困顿中体验快乐

> **“自得其乐的性格”最大的特征是，他们能在一般人无法忍受的情况中找到乐趣。**

革命的乐观主义精神

> 凡是能承受独自监禁煎熬的人，都有这种设计心流活动、建立目标的禀赋。

盖西伯拘而演《周易》；仲尼厄而作《春秋》；屈原放逐，乃赋《离骚》；左丘失明，厥有《国语》；孙子膑脚，《兵法》修列；不韦迁蜀，世传《吕览》；韩非囚秦，《说难》、《孤愤》；《诗》三百篇，大底圣贤发愤之所为作也。

> 在困难和威胁几乎使我们陷于瘫痪时，我们必须找到投注精神能量的新方向，一个不会受到外来力量影响的方向，以便肯定自己的控制力。即使所有希望都破灭了，我们还是得寻找一个有意义的目标，围绕着它重新整顿自我。那么，纵然在客观环境里沦为奴隶，主观上仍然保持自由，最不堪的情境也能转变成心流体验。

那些在纳粹集中营中挺过来的人们。

> 只想保护自己的自恋者，在面临外在环境的威胁时就会崩溃，接踵而来的惊慌失措，使他们无法把该做的事情做好，因为他们的注意力转向内心，专注于恢复意识的秩序，根本没有余力应付外在的现实。

# 第5章 感官之乐

> 学着去控制身体和感觉。光靠身体的动作不能产生心流，一定要投入心灵的力量才行。

## 5.1 运动的乐趣

> 所有体育活动最纯粹的形式，就是突破体能的极限。

1. 确立一个总目标，并尽可能包含多个实际可行的子目标；
2. 找出评估目标进度的方法；
3. 保持精神集中于所做的事情上，并且对活动涉及的挑战进行越来越精细的区分；
4. 培养随机应变所需的技巧；
5. 在活动变得令人厌倦时，随时提高挑战的难度；

## 5.2 爱情的乐趣

1. 肉体享乐；
2. 追逐浪漫爱情；
3. 真正的关怀；

在彼此身上投注更多的注意力，了解伴侣的思想、感觉与梦想。

## 5.3 控制的最高境界

> 瑜伽一词在梵文里的意思是“结合”。首先是结合身体各部分，然后整个身体与意识结合。

瑜伽的八重境界：

1. 制戒：节制可能伤害他人的行为与思想——虚伪、偷窃、淫欲、贪婪；
2. 内制：遵守清洁、学习、顺从上帝的规矩；
3. 坐法：长时间静坐不向压力或疲惫屈服；
4. 调息：身体放松，呼吸节奏稳定；
5. 制感：从外界事物上撤回注意力，控制感觉的出入；
6. 执持：长时间专注于一种刺激；
7. 静虑：不需要外来刺激，专心致志；
8. 三昧：沉思与思考对象合二为一。

## 5.4 视觉之乐

> 汲取平凡中的不凡之美。

> 只要能控制发生在我们身上的一切，看与不看并没有什么分别。

## 5.5 聆听音乐

> 帮助听者把注意力集中于特定的模式上，培养所需要的情绪。

> 创造声音和谐之美的能力，与潜存于社会秩序下的抽象和谐（也就是文明）之间有密切关系。学习吧精神专注于优美的节奏与和谐之中，意识的秩序才得以建立。

孔子强调礼乐的原因。

## 5.6 美食之乐

美食与音乐都是有秩序的系统，心流来自于将系统变得有秩序。

并不是为了生存而做饭，而是为了享受调和五味的乐趣而烹饪。

> **基于恐惧而勉强压抑欲望，人生就会变得黯淡无光。这种人会变得刻板、自卫，自我也停止成长。唯有自动自发地遵守某些几率，人生才有乐趣，而仍然保持理智。一个人若能学会发乎本心，控制本能的欲求，就能享受乐趣而不上瘾，不至于成为欲望的奴隶。**

> 一个人清醒的时间有限。

# 第6章 思维之乐

> 好奇心（所有知识的种子）乃是愉悦的最纯粹形式的反映。

> 心流总是一方面用到肌肉与神经，一方面又需要意识、思想与感觉的配合。而某些活动的乐趣直接来自心灵的秩序，不需要通过对肉体感觉。

> 享受心灵活动的乐趣，也需要规则、目标、取得回馈的途径、集中精神、并且在技巧的层次上随机应变。

> 我们很少注意到自己对心灵的控制力竟是那么薄弱。在独处、无需集中注意力时，心灵没有秩序的原貌就会呈现。

> 除非一个人知道如何整顿自己的思想，否则注意力一定会被当时最棘手的事件所吸引；它会集中于某种真实或想象的痛苦，最近的不快或长期的挫折中。

## 6.1 记忆：科学之母

> 人类自有历史以来，记忆力一直被视为最珍贵的心灵天赋。

> 一个人倘若没什么值得记忆的事，人生就会变得贫乏。

> 稳定的内涵能使心灵更丰富。所谓创造力与记诵式学习不兼容，其实是一项错误的假设。

> 前者（能记住抽象概念的人）的意识不受环境产生的秩序限制，他总有办法自娱，从自己的心灵内涵中寻求意义。

## 6.2 思维游戏

> 最简单的秩序体系就是为每个事物取名字，我们发明的字眼，便把独立事件纳入宇宙通用的类别。

取名的过程类似于在数据库中建立索引的过程。名不正则言不顺。

> 文字是建造象征体系的“积木”，使抽象思考成为可能，并扩大了心灵存储刺激因素的空间。若缺少整理资讯的体系，即使最清晰的记忆也不能阻止意识陷入混沌。

如果一个概念和观点不能被清晰地表达，说明还没有被真正认识或理解。

> 科学与哲学的兴盛于发展，只因思考带给人愉悦。

个人对这个观点持保留态度。一方面是马克思的唯物史观认为，重要历史事件的终极原因是社会的经济发展。另一方面，也有因为痛苦而思考获得成果的，比如司马迁的《史记》。

> 哲学、新科学观念的出现，也是源于找到新方法描述现实的乐趣。

> 当一个人学会一套象征体系，并且有能力加以运用时，他就在心灵之中建造了一个随时与他同在、自给自足的世界。

文王拘而演周易。

> 缺少内化的象征体系的人，自身没有什么可以仗恃的东西，内心物理抗拒那些自称握有解答者的谎言。不能为自己提供资讯的星灵，只能在混乱中随波逐流。

## 6.3 文字的游戏

> 每晚读诗对心灵的作用，就跟每天用健身器材锻炼身体的效用相同。

> 维多利亚时代的人有大量内容详实的书信作品，可视为从股份乱的事务中理清秩序的范例。

> 若非通过书写时思想缓慢而有机的成长过程，观念根本不可能出现。

> 写作是在情绪紊乱中塑造秩序的一种治疗法。

## 6.4 挖掘历史宝藏

## 6.5 科学的兴味

> 从事科学研究的最好理由，就是因为它能为研究者建立心灵的秩序。

## 6.6 哲学的乐趣

> 如果学习是发自肺腑的感觉，非但毫不费力，还能带来乐趣。

> 一个业务科学家，并非为了要跟专业科学家竞争，而是用象征的训练手法扩充心灵的技巧，在意识中创造秩序。

# 第7章 工作之乐

> 良好的工作需要高度的技巧，并能提升自我的复杂性。

> 被迫做不需技巧的工作，往往造成精神熵。

## 7.1 工作的乐趣

> 身处所谓“文明”社会里的大多数人，都为实现少数剥削者的梦想放弃了享受生活乐趣的希望。

> 我就是我自己生命的老板。

> 和谐平衡的生活方式。

> 乐趣根植于复杂度的增长。

> 借着生产性活动构筑自我的存在。

> 不计较外在的报酬，自然而完全地投入。

## 7.2 像玩游戏一样去工作

> 为高收入而忍受不断重复的工作，很快就会觉得枯燥。

1. 目标；
2. 回馈；
3. 挑战；

技术与艺术的结合；

1. 重新设计工作，使它尽可能接近心流活动；
2. 自得其乐的性格，加强技巧，选择可行的目标；

## 7.3 工作与休闲

> 一个人每周处于心流状态的时间越长，反映的整体体验品质就越高。

> 工作时即使已进入心流，动机仍然偏低；休闲时尽管体验品质很差，动机仍然很高。

> 如果我们认为把精神集中于一份工作违反了自己的意愿，就会觉得浪费了精神能量。

对工作的不满：

1. 缺乏变化与挑战；
2. 与直属上司的人际关系；
3. 压力太大，太紧张；

> **在实现自己目标的同时，也帮助老板和同事实现他们的个别目标；**

> 把精神能量集中投注在塑造个人目标上，无视一切转移注意力的诱惑；

## 7.4 如何有效使用闲暇时间

> 未来不仅属于受过教育的人，更属于那些懂得善用闲暇的人。

# 第8章 人际之乐

生活品质的决定：

1. 我们如何体验工作；
2. 我们与他人的互动关系；

> **有必要学习在没有外援时，仍能控制自己的意识**

## 8.1 微妙的人际关系

人是社会关系的总和。

呆子：独处的人。

## 8.2 寂寞之苦

> 情绪最低潮的时候：注意力无所寄托。

> 内在维持心灵的秩序十分困难。我们往往需要外在的目标、外来的刺激、外来的回馈，帮助我们控制注意力的方向。

学会控制意识。

> 痛苦往往比茫然无依，被混沌蚕食心灵好过。

> 学习运用独处的时间在童年时期就很重要。

> 如果一个人不能在独处时控制注意力，就不可避免地要求助于比较简单的外在手段：药物、娱乐、刺激等任何能麻痹心灵或转移注意力的东西。

> **在成长的同时享受人生，就是从人生必然会出现的精神熵中，创造更高的秩序形式。不要把新挑战看成需要压抑或者逃避的东西，而是一个学习和改善技巧的机会。**

> 如果一个人能随心所欲地进入心流，不受外在条件限制，就已掌握了改变生活品质的钥匙。

## 8.3 驯服孤独

> 如果要驾驭陌生的环境，就必须把自己的一套秩序加诸旷野之上。

> 专心阅读和写作。

> 熬过孤独唯一的方法就是设法整顿注意力，不让精神熵损害心灵。

> **如果把不读当作实现在人群中不可能实现的目标的机会，那么你不但不会觉得寂寞，反而会喜欢独处，而且从中学到新的技巧。**

