---
title: 面试
author: 王致远
date: '2018-10-31'
slug: certain-company-auditioin
categories:
  - 找工作
tags:
  - 解决方案
---

# 无领导小组

注意要点：

1. 询问结果呈现形式的要求；
2. 服务组员；
3. 征求大家的讨论方式，是直接讨论还是先个人思考（5 min）后再讨论；
4. 选出时间控制者；
5. 每个人的结论呈现方式；
6. 用纸笔记录每个人所陈述的意见和理由；
7. 按顺序陈述，根据之前陈述人的观点调整自己观点中的不足；
8. 分析题目中的判别标准；
9. 先求同，再存异；
10. 细化他人意见；
11. 跳出原有思维框架，进行补充；
12. 最后陈述者先向小组成员陈述一遍，查漏补缺，取得大家的共同同意；
13. 共同鼓励；
14. 最后陈述时要有对讨论过程的总结；
15. 哪位组员贡献最大？集体智慧，从不同角度给出建议，并最终统一形成答案。
16. 认为讨论环节哪些是做的好的，哪些是无效的？
17. 结束后有头有尾，收拾好桌面细节。
18. 在自己取得优势后对其他人的关怀。
19. 做有把握的事情、做无争议的事情、出现争议时给出理由、陈述清楚即可，不要纠缠讨论。
20. 在组内有人获得领导力，得到多人支持时，如果不是只有一人可以胜出的测试，此人又是一个懂“规则”的人，尽量更换跟随策略，做好一个“可合作”者，同时将自己不擅长展现的内容都尽量让此人来展现。

--------

# 具体企业面试

## 1. 移动研究院

一面：

- 群面：无领导小组；
    - 看问题的角度；
    - 对团队任务完成的贡献度；
    - 语言逻辑表达能力；
- 英语面试：
    - 英文自我介绍；
    - 科研、学习内容；

二面：

- 自我介绍
- 技术面：研究生期间的科研项目；

三面：

- PPT演讲：介绍做过的课题及工作内容；

英文自我介绍：

Good afternoon. Nice to meet you. My name is WangZhiyuan. I was born in LanZhou GanSu province. I graduated from Southwest JiaoTong University in 2016 and was recommended for postgraduate of BeiJing JiaoTong University. 
If I use three words to describe myself, they are conscientious, creative and technical. My tutor in school and leader during internship and frinds always describ me a conscientious man because I always treat my work seriously and finish my task efficiently. But I'm not conservative. I'm good at solve challenging problem, which can inspire my creation. And I desire to undertake such kind of job in the future. I am also a technical enthusiast. I love to search and learn new tools and skills for example programming language in my field.
I am very skilled at data science and data mining, although my major discipline is traffic management. I love to handle bunch of data and search unknown information from data. I spend a lot of my spare time in learning statistics and data manipulation skills and I have undertaken 5 traffic data mining reaserch projects in last two years. Especially, I really good at R languange programming. I have wriiten 4 R packages to support data mining research projects during internship and support my thesis of master degree. Now, i have the sufficient ability to handle 10 million rows dataset.
I wish I can go further in this field and i will sincerely appreciate Research Institue of China Mobile if I pass this interview and get this job. Thank you very much for your listening.

## 2. 中国进出口银行

### 2.1 英文自我介绍

Good afternoon. My name is WangZhiyuan. I was born in LanZhou GanSu province. I graduated from Southwest JiaoTong University in 2016 with double-major transportation and finance. Then I was recommended for postgraduate of BeiJing JiaoTong University majored in traffic and transportation planing and management. 
If I use three words to describe myself. The first word is conscientious. My tutor in school and leader during my internship always describ me a conscientious man because I always treat my work seriously and finish my task efficiently. The second word is creation. I'm good at solve challenging problems, which can inspire my creation. The third word is good learner. I can learn the framework and knowledge in a new field quickly even if I am not fimilar about that before. Besides these three characteristics, I am very skilled at data manipulation and data analysis. During the last three years, I have undertaken 4 data mining research and accumulate rich skills and experience in data science. 

I want to join The Export-Import Bank of China for three reasons. The first reason is I worship the Belt and Road Initiative and want to join in this magnificent project. I believe it's one of the essential part of Great Rejuvenation of Chinese Nation. I know this bank conducts many finance service and investment oversea to support B & R Initiative. If I have chance to devote myself in this project, I will feel a great honor and passion for my career. The second reason is I have cross-backgroud of transportation and finance not only about knowledge but also thinking methods of engineering and economy. This Bank is a great platform for me to use this cross-domain knowledge and solve complex problems in specific projects. The third reason is here I can learn a lot not only about industry but also about business and trade. I like to work hard and learn a lot.

### 2.2 进出口银行概况

中国进出口银行成立于1994年，是直属国务院领导、政府全资拥有的国家政策性银行，其信用评级与国家主权评级一致。是我国外经贸支持体系的重要力量和金融体系的重要组成部分。是我国机电产品、成套设备和高新技术产品出口和对外承包工程及各类境外投资的政策性融资渠道、外国政府贷款的主要转贷行和中国政府援外优惠贷款的承贷行，为促进我国开放型经济的发展发挥着越来越重要的作用。

主要职责：贯彻执行国家产业政策、外经贸政策、金融政策和外交政策，为扩大我国机电产品、成套设备和高新技术出口，推动有比较优势的企业开展对外承包工程和境外投资，促进对外关系发展和国际经贸合作，提供政策性金融支持。

业务范围：

1. 办理出口信贷（包括出口卖方信贷和出口买方信贷）；
2. 办理对外承包工程和境外投资类贷款；
3. 办理中国政府对外优惠贷款；
4. 提供对外担保；
5. 转贷外国政府和金融机构提供的贷款；
6. 办理本行贷款下的国际国内结算业务和企业存款业务；
7. 在境内外资本市场、货币市场筹集资金；
8. 从事人民币同业拆借和债券回购；

资金来源于国家财政拨款或票据融资，专门负责发放贷款支持进出口贸易，专营本国对外贸易信用。

政策性银行：

1. 由政府创立;
2. 以贯彻政府的经济政策和意图为目标;
3. 在特定领域开展金融业务;
4. 不以盈利为目的；

### 2.3 半结构化问题

#### 1. 自我介绍

各位老师好，我姓名王致远，出生于甘肃省兰州市，本科就读于西南交通大学，交通运输专业和金融学第二专业。研究生保送到北京交通大学，交通运输规划与管理专业。今年5月~10月在交通运输部规划研究院实习。

如果用三个词来描述我自己。第一个词是“责任心”，我的导师和实习时的领导对我的评价都是富有责任心，因为我经常高效率并尽可能完善地完成布置给我的工作。第二个词是“创新能力”，我擅长处理复杂的、有一定挑战性的工作，在形成解决方案的过程中能充分发挥创造力。第三个词是“学习能力”，我擅长快速学习一个新领域的相关知识，并完成相应的项目。除此之外，我非常擅长数据挖掘，过去三年曾承担四个交通数据挖掘的科研项目，擅长R语言，独立开发过4个数据分析程序，其中2个已经在我实习单位部署应用。

对于工程业务岗，我的优势是我具有复合专业背景：交通运输+金融+数据挖掘。不仅仅掌握了这些学科的知识，更重要的是培养了工程学和商科的思维模式，在面对工程和金融的复合问题时能够展现出优势。（如果说缺点，我的缺点是做事习惯高效率，对工作有些过于认真。）

#### 2. 对风险管理的认识

风险是金融学，特别是金融市场和金融产品中的重要概念。因为金融的本质是信用，而信用在未来是否履行是未知的，从而产生了风险。金融工具的三大属性：流动性、安全性、收益性，三者是不可能同时满足的。从而产生了风险管理。

风险管理分为几个过程：风险识别、风险评估、风险控制、风险监测。

- 风险识别中可以将风险归为宏观和微观：宏观有：政治风险（包括外交风险）、自然风险、市场风险（包括利率风险、汇率风险和价格风险）；微观有：法律风险、道德风险、信用风险、流动性风险。
- 风险评估，也是为风险定价的过程。金融学中较为著名的是CAPM资本资产定价模型。其中风险的体现是$\beta$系数，用来衡量个别金融资产相对于整个金融市场的波动情况。$\beta$越高，相对于市场的波动性越大。
- 风险控制的方法通常有：风险回避；风险转移或转嫁，主要通过保险、金融衍生品交易（比如远期、套期保值、期权）等方法；风险保留，通过内部控制的方法减小风险损失。
- 风险监测：可以使用大数据的方法，建立风险预警模型。

#### 3. 中美贸易战对进出口银行的影响

我认为中美贸易战对于进出口银行既是挑战，又是机遇。

中美贸易战的起因是美国指责对中国存在巨额贸易逆差，并且指责中国侵犯知识产权、并购国外高新技术企业；而根本原因是美国对中国崛起，特别是以“2025计划”为代表的高科技产业崛起的遏制与打压。9月，美国对中国2000亿美元进口商品，并威胁2019年1月1日起提升到25%。刚刚进行的G20峰会上，两国领导人进行了协商，最终决定休战，留下3个月的协商期，暂不提升税率。中国需要从美国进口国内民生需要的产品。

9月，中国举行中非合作论坛北京峰会。11月，中国举办了中国国际进口博览会，标志着我国对外贸易正逐渐从出口导向转变为进出口平衡的趋势。在中美贸易谈判的背景下，一方面，未来中国会扩大对美国及新兴市场的进口额度；另一方面，也推动中国加快改革步伐、推动产业升级、拓展新兴市场。

对于进出口银行来说，挑战来源于：在未来几年内，我国进出口结构会逐渐发生变化，所以进出口信贷市场的需求情况会发生变化，需要我行紧跟国家发展战略、提前谋划布局、积极设计新服务和产品、全力支撑对外贸易政策。

机遇在于：在新的贸易环境背景下，加大对有利于中国构建全球产业链、价值链中心的产业和项目的信贷支持；加大对以芯片、大飞机、船厂为代表的新兴科技产业的信贷支持。

#### 4. 介绍自己的专业

我研究生的专业是交通运输规划与管理，研究方向是运输与物流。研究生期间我主要参与的科研项目有：连云港港口集团信息化发展规划2017~2020，节假日高速公路车流量数据挖掘研究，中铁国际业务集装箱箱管系统建设研究，首都机场区域经济影响研究。实习期间主要承担的任务是，全国公路干线交通情况月度分析报告，高速收费数据的分析挖掘。

#### 5. 贷款的五级分类

- 正常（能够正常还本付息，不存在影响本息和还款时间的消极因素）；
- 关注（存在一些对偿还不利的影响因素，如因素继续，借款人的偿还能力受到影响）；
- 次级（还款能力出现明显问题，需要通过处分资产或执行抵押担保来还款付息）；
- 可疑（借款人无法足额偿还本息，即使执行抵押担保，也要造成一部分损失）；
- 损失（已无偿还本息可能，能收回极少部分）

后三者为不良贷款。

#### 6. 四类资产

会计核算的金融资产

1. 以公允价值计量的金融资产；
2. 持有至到期投资；
3. 贷款和应收账款；
4. 可供出售金融资产；

#### 7. 资本市场与货币市场

- 期限不同（资本市场>1年，货币市场<1年）；
- 金融产品不同
    - 货币市场：商业票据、大额可转让定期存单、短期政府债券；
    - 资本市场：股票市场、债券市场。
- 融资目的不同
    - 货币市场：短期资金周转需要；
    - 资本市场：企业长期投资计划；

#### 8. 航空产业

##### 大飞机制造

C919是中国首款按照最新国际适航标准，**具有自主知识产权的干线民用飞机**，于2008年开始研制，最大航程5555公里。属中短途商用机。首飞时间2017年5月5日。大量使用复合材料和铝合金，有效降低机身重量，绿色排放。面向全球市场。

大飞机重大专项是《国家中长期科学与技术发展规划纲要（2006-2020）》确定的16个重大专项之一。

中国商飞是我国实施国家大型飞机重大专项中大型客机项目的主体，也是统筹干线飞机和支线飞机发展、实现我国民用飞机产业化的主要载体。

C929中国首款宽体大型客机，载客300人左右，中俄合作研制。对标波音787。最大航程12000公里。

##### 机场经济影响评价

- 直接效应：（首都机场，内部服务保障公司，航空公司，外部服务供应商，货运及物流公司）
    - 就业
    - 增加值
    - 税收
- 间接效应：
    - 推动航空服务链上下游产业发展
    - 航空服务链就业人员二次消费贡献
    - 航空游客消费贡献
    - 航空货邮产生的经济贡献（推动进出口贸易）
- 引致效应：
    - 产业结构
    - 旅游，会展，酒店
    - 房地产
    - 综合交通
    - 外商投资
    
增加值=劳动者报酬+生产净税额+固定资产折旧+营业盈余

投入产出法：把一系列内部部门在一定时期内投入（购买）来源与产出（销售）去向排成一张纵横交叉的投入产出表格，根据此表建立数学模型，计算**消耗系数**，并据以进行经济分析和预测的方法。

##### 航空公司

1. 星空联盟（国航）；
2. 天合联盟（东航、南航退出）；
3. 寰宇一家（南航）；

#### 9. 航海产业

##### 航运公司

1. 丹麦马士基
2. 瑞士地中海
3. 法国达飞航运
4. 台湾长荣海运
6. 中国中海集运（中国海运集团）
7. 美国总统轮船
8. 韩国韩进航运
9. 中国中远集运（中国远洋运输集团）
10. 日本邮船集运
11. 台湾阳明海运
12. 中外运
13. 山东海丰

**中国远洋海运集团**由中国远洋运输集团与中国海运集团重组而成。

##### 中国船厂

中国船舶工业集团（长江以南，南船）：

- 江南造船（海军）（宇宙号集装箱船）
- 沪东中华（LNG船）
- 上海外高桥
- 广船国际

中国船舶重工集团（长江以北，北船）：

- 大连船舶重工（海军）
- 渤海船舶
- 青岛北海
- 武昌船舶

2018年3月已批复二者合并

船型：

- 航母等战列舰
- 集装箱（第5代集装箱船5000TEU，第6代集装箱船8000TEU）
- LNG船（-163度液化天然气）1980年后由韩国日本船厂主导

中国制造的宇宙号集装箱船，2018年6月上海交付，21000个标准集装箱，最大载重19.8万吨。亚欧航线。与韩国船厂竞争。

#### 10. 信贷业务员的工作内容

对公业务，做公司信贷，包括短期和中长期贷款、中间业务，口行叫“项目经理”。

##### 信贷工作

1. 客户营销：与客户保持密切沟通，多种渠道了解客户业务发展情况，摸清既有和潜在融资需求，找到业务契合点，为客户提供融资方案，建立业务联系，逐渐承接客户大项目，建立牢固银企合作关系。需要信贷员熟悉我行业务产品和操作流程，能够根据客户需求量身定做融资方案，同时需要有敏锐的金融市场嗅觉，给出合理报价，最终牢牢抓住客户。
2. 评级授信：评级，定性+定量（根据财务数据）。授信，根据评级计算出风险限额。集团客户需要做总量控制，子公司开展业务时，不仅占用自身额度，还占有总集团额度。
3. 业务受理：确定业务合作关系，由客户提交借款书面申请，启动贷前尽职调查。
4. 贷前尽职调查（核心）：贷款的主要风险因素，说明风险管理措施，说明贷款的合规性，最后就是否提供贷款表达意见。需要学习相关行业知识。实地走访经营和项目建设情况。
5. 项目送审
6. 合同签订：一般标准化，特殊情况需要法审，心地阿远有一定法律知识，规避法律风险。
7. 贷款发放与支付：实贷实付原则，贷款发放与实际用途相匹配，原则上都是受托支付。
8. 贷后管理：现场排查和非现场排查。
9. 档案管理。

##### 客户工作

1. 对账：对账单。
2. 账户业务：帮助客户收集材料，开户；

##### 综合工作

1. 常规数据报送：外部，向银监会；内部，向行内相关部门；
2. 内部工作会议；

#### 11. 岗位匹配度

我认为我的个体特征和工程业务岗是匹配的。首先，我本科获得了工学和经济学双学位，在金融学方面基础扎实，形成了完整的金融学的知识体系和思维模式。复合学科背景使我能够在工程信贷项目中综合运用复合专业知识，解决复合型问题。其次，我个人非常擅长数据分析挖掘，不仅熟悉数据挖掘流程和技术，还对将经济问题抽象为数据问题有一定经验，在岗位中能够衔接信贷业务员和数理统计员，促进信贷业务、工程业务和数理统计业务的流畅合作。第三，我的快速学习能力很强，形成了自己的一套快速学习某领域知识的能力，这非常符合工程业务岗的需要。

#### 12. 三去一补一降

供给侧结构性改革

去产能、去库存、去杠杆、降成本、补短板

#### 13. 技术经济学

几个重要概念：

1. 经济效果：投入与产出的比较；
2. 现金流量：一个经济系统在一定时期的现金录入和流出量；
3. 固定资产投资：建筑工程费，安装工程费，设备及器具购置费，建设期利息，固定资产调节税，其他工程费用；
4. 流动资产：货币资金，应收及预付款项，存货。
5. 固定资产折旧：固定资产在使用过程中，随着资产损耗而逐渐转移到产品成本费用的那部分价值。折旧方法有：平均年限法、工作量法、加速折旧法。
6. 成本：生产成本（原材料，燃料，人工成本，管理费，财务费，销售费）
7. 税金：增值税，营业税，资源税，城乡建设税，教育费税，企业所得税；


三个经济性评价指标：

1. 投资回收期法：在不考虑资金的时间价值的条件下，以项目净现金流入回收项目全部投资所需要的时间。
2. 净现值法：方案在寿命期内隔年的净现金流量，按一定的折现率折现到期初时的现值之和。
3. 内部收益率法：认为在整个项目寿命内，都存在未能回收的投资，只有在寿命期结束时才能全部回收，内部收益率就是未回收投资的收益率。对项目的“偿还”能力完全取决于项目内部，所以称为“内部收益率”。


## 3. 国家开发银行四川省分行

### 3.1 国家开发银行

国家开发银行成立于1994年，是直属国务院领导的政策性银行。2015年3月，国务院明确国开行定位为开发性金融机构。股东是中华人民共和国**财政部**、**中央汇金**投资有限责任公司、**梧桐树**投资平台有限公司和全国**社会保障基金**理事会。国开行主要**通过开展中长期信贷与投资等金融业务，为国民经济重大中长期发展战略服务。**是全球最大的开发性金融机构，中国最大的中长期信贷银行和债权银行。

开发性金融机构是政策性金融机构的深化和发展，以国家信用为基础，以市场业绩为支柱，通过融资贯彻国家政策，实现政府的发展目标。简单地说就是**既开展政策性金融业务，又开展商业性金融业务**的金融机构。开发性金融机构是政策性金融机构的深化和发展。**它以国家信用为基础，以市场业绩为支柱，通过融资贯彻国家政策，实现政府的发展目标。**

开发性金融机构的业务：

1. 新型城镇化；
2. 保障性安居工程；
3. 两基一支（基础设施、基础产业（农、能、重工、制造）和支柱产业）；
4. 支持走出去；

开行使命：

- 增强国力：
    - 两基一支；
    - 新型城镇化建设；
    - 支持企业走出去；
    - 应对国际危机；
    - 稳增长调结构；
- 改善民生：
    - 保障性住房；
    - 扶贫开发；
    - 三农（农村，农业，农民）；
    - 教育医疗；
    - 中小微企业；
    
开行愿景：建设国际一流开发性金融机构：
    - 持续创新的活力；
    - 全球领先的重要影响力；
    - 强大抗风险能力（全面风险管理体系）；
    
发挥作用：
    - 重点领域发挥主干作用；
    - 薄弱环节发挥引领作用；
    - 关键时期发挥逆周期作用；

### 3.2 四川省分行项目

1. 巴万高速：连通川陕的新通道；完成国家级和省级高速公路规划，带动川陕革命老区脱贫致富；PPP项目；
2. 天府新区、国际空港新城；
3. 成都轨道交通；
4. 中巴能源合作；
5. 清洁能源贷款，水能、风能、太阳能绿色能源开发；
6. 藏区脱贫攻坚战；光伏扶贫；扶贫搬迁资金；棚改项目；助学贷款；

川分对于国家顶层战略服务的思考：

1. 一带一路战略：设施联通（成都新机场，国际空港新城，成兰铁路、成贵铁路），贸易畅通（蓉欧班列），资金融通（支持企业走出去），民意相通（巴蜀文化交流，国外游客旅游便利化）。
2. 长江经济带战略（成渝城市群）：国家级城市群。城镇体系形成；交通互联互通；公共服务共建共享；生态环境联防联控；创新资源高效配置。先进制造业和现代服务业，优势产业集聚。天府新区建设。
3. 新型城镇化：大中小城市、小城镇、新型农村社区协调发展、互促共进的城镇化。新型城镇化的核心在于不以牺牲农业和粮食、生态和环境为代价，着眼农民，涵盖农村，实现城乡基础设施一体化和公共服务均等化，促进经济社会发展，实现共同富裕。
