---
title: 看《超级工程·港珠澳大桥》
author: ZhiYuan Wang
date: '2018-10-23'
slug: gangzhuao-bridge
categories:
  - 电影
tags:
  - 超级工程
  - 思考
---

今天是港珠澳大桥正式通车的日子，但之前对这座桥知之甚少。于是和豪杰看了《超级工程·港珠澳大桥》这部纪录片。

## 内容

纪录片里主要讲了大桥在规划、设计、施工建设方面遇到的一些工程难题，并介绍是如何解决的，以下几个印象比较深刻。

首先是伶仃洋航道是香港港和广州港的重要航道，每天有4000多艘船来往于此，怎么让桥不干扰航道运行？一种想法是把桥建高，让船在桥下过。但未来航道通行能力是30万吨级的，桥就必须建的特高，就会影响周围机场的起飞降落。所以选择了在中间留出空间供船通行，由人工岛+海底隧道连接这一段的设计方案。

随之而来的问题是人工岛怎么建？由于那一块的海床是个淤泥斜坡，用传统落石的方法会滚下去，建不稳定；如果把淤泥全部挖掉，是个非常大的工程（淤泥相当于3个胡夫金字塔），而且对生态破坏太严重。所以就设计了一个先用120根钢筒形沉管沉到指定位置，然后再在上面建岛的策略。

每个圆筒大小都接近篮球场大小，20多层楼高，这样大的钢桶该怎么制造？如果先造板，再进行拼接，这样误差会很大。所以就先做了桶的内框架，然后做一块块桶板，将其焊接到框架上再拼接。

另一个问题是混凝土的沉管隧道怎么建。请了两个建过海底隧道的德国工程师，他们说要先造模具，于是先造了个钢结构的隧道模具。同时开工的是巨大混凝土沉管加工工厂。等模具造好后，工厂也建好了。将模具运到工厂内，将混凝土往里面浇筑，等浇筑好了就推出去，浇筑新的部分。然后在海底挖好的凹槽里一块一块拼接。

除了基础工程性的问题，还要考虑风浪形成的共振、地震、氯盐对混凝土的腐蚀等问题。风浪是用物理性的扰流板还是什么其他结构解决的；地震和氯盐都是用新材料（比如减震橡胶）解决的。

除了关于海底隧道，桥面的建设也存在问题。由于离澳门机场很近，对吊装高度有严格限制，传统的桥支柱的吊装存在问题。工程师们用类似铰链的方法，让桥柱从水平旋转到垂直状态。

## 思考

看完这部纪录片有两点思考。

第一是我的专业交通运输规划与管理，虽然最后拿到的工科学位，但其实连工程的尾巴还没摸到，离这些实用的工程差别太远了。我们最多算是管理科学的学科。学各个学科，具体的知识还不是最重要的，最重要的是建立学科的思维体系和思维模式。比如经济学要学会从市场、供需这些角度看问题。以后要注重学科思维体系的培养，将知识凝结并升华到方法论的高度，并勤于总结，来指引自己。由此引来第二个思考。

第二是所谓“工科的思维”是怎样的呢？从这个记录片里我感受到的是**“提出方案，解决问题”**这样的思维，用老话讲就是**“兵来将挡，水来土掩”**。区别于科学的“提出假设，验证假设”，工程面对更多的是实际的问题。建设港珠澳大桥这样的决定，有可能是不太懂工程的人，比如政治家、经济学家提出的设想。而工程师就是要将这种不可能变为实际的人。如果以前有成熟的应用，那工程师只需要将技术应用就可以了；而面对这种前所未有的工程实践，只有凭借工程师们丰富的知识和经验，创造性地提出解决方案。如果说普通人的思维是，我有多大的资源来做多大的事。工程师们的思维可能是，我要做多大的事需要怎样的资源。

比如纪录片中，为了建座桥，那么需要修两个人工岛，需要修个海底隧道；为了修人工岛，需要120个圆筒沉到海床上；为了制造圆筒，需要先搭个框架，然后再将桶板拼接到框架上；为了建隧道，先要修个模板，还要有制造隧道的工厂，但现在没有这样的工厂，那么就修个工厂。将一个大型的工程，逐层分解，逐层细化，直到全部落地实践，**然后再逐层拼接完成。其中最令人深刻的是工程师们的自信，一种“兵来将挡水来土掩”，每个问题都有其对应解决方案的自信。**

其实软件工程中也是如此。很多有成就的开发者为了完成一个任务，没有得心应手的工具，于是先创造个这么个工具。结果最后项目也许默默无名了，但工具传播到全世界。当后人仰望时，他说“这个工具原本是为完成这个项目而设计的”，**一种“深藏功与名”的感觉**。

所以对于一个胸有成竹的工程师来说，工程问题就是个“提出方案，解决问题”的过程。**希望自己有朝一日也能成为不仅仅是组装轮子的人，也能成为“造轮子”的人。**