---
title: 25岁做什么可以让五年后受益匪浅
author: 王致远
date: '2018-11-23'
slug: 25-years-what-to-do
categories:
  - 个人
tags:
  - 思考
  - 学习总结
  - 转载
---

知乎上关于25岁做什么可以在五年后受益匪浅的讨论：

## 学霸猫

作者：学霸猫
链接：https://www.zhihu.com/question/52178718/answer/131556583
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

接触的人越多，看到的事越多，也越来越觉得这是个太混乱的时代，一切都在崩塌，一切都在重构。我们再也找不到25岁结婚生子，30岁事业有成，50岁退休的美好生活节奏。年龄和对应的生活秩序，正在无限混乱，工作、生活、情感都面临前所未有的复杂局面挑战。所以，无论今天的你是25岁还是30岁，请意识到，也许你对年龄和对应的人生阶段的所有认知，应该全部改写了：

1. 重建现实观：重新开眼看世界，下最彻底的决心抛弃教科书、父母、长辈教你的一切道理，在最动荡的**社会巨变期**，它们全部都过时了。你必须抛弃对工作、生活、婚姻的所有美好幻想，靠自己的双眼重新理解当下社会中人们的生活究竟在发生什么，真正面对现实，而不是网络世界上自媒体为你构建的所有想象。开眼看看世界，**把关于完美生活的一切幻想都放下，彻底放下。**
2. 拿自己做实验：不断地拿自己的生活、工作、情感上的各种事情来做实验，找到自己的**最佳节奏和最佳状态模式**，再慢慢培养习惯。养成“实验”的心态和方法论，凡事不着急下结论，也不急着培养习惯。没有什么是一定“最好”的答案，没有人可以代替你去了解你自己的节奏，为你自己下判断。有的人适合做匠人，有的人适合做管理，有的人适合单打独斗，有些人就是要熬夜才能有生产力。你自己到底是谁，到底适合什么生活方式，没有人能告诉你，只有实验和自己的体验，不会骗你。
3. 意识到这个世界上99%的人不是傻子就是骗子：媒体、信息、内容、知识全都是生意，背后都是不同的利益集团和个体在操纵，而我们不过是被一茬茬收割的韭菜而已。有很多人发表一些观点，虽然没有利益操纵，也不是存心想骗人，但确实自己的脑力和认知水平有限，也无法提供更接近本质和真相的思考。傻子和骗子多了，三人成虎，假的也能说成真的，黑的也能说成白的。**警惕一切流行的、火热的概念和观点，他们99%的情况下是错的，不仅没有卵用，而且永远把你带到坑里，让你始终觉得自己不行，生活绝望，别人都生活的比你好。关掉大多数媒体和信息源，越popular，越要小心。**
4. 近乎残暴地训练你的**判断力和筛选力**：每个人都有一长串梦想清单，每个人都有一长串待办事项，你也要知道，每一个渴望，每个动心，都是一个坑，它们都将向黑洞一样消耗和占据你的注意力，让你的精力和决心都越来越分散。在这个照单全收，每个人都收集了一大片没看的文章的时代，每分每秒都训练自己Say No的判断力，大多数书不必看，大多数朋友圈不必刷。这个世界太喧闹，我们的注意力太容易被分散，生存于这个时代，判断力和筛选力是我们必须进行的残暴训练。
5. 尽最大努力简化自己的工作和生活：今天25岁的人，还根本没有能找到自己在这个世界的位置，不知道未来会发生什么，也不知道自己未来会去哪个行业，做什么事，呆在什么城市，遇见什么人。不，我们根本都不会知道。从另一个角度想，与其为此而惶惶不安，不如享受当下的种种不确定性，享受不可预知的惊喜和快乐。**生活越简单，我们就越可能拥抱变化，适应变化。**轻装简行，享受飞翔吧。
6. 最后，锻炼永远都可以无条件的爱自己和蜜汁自信：肥一点，矮一点，丑一点，穷一点，傻逼一点，都不是事儿。心态要好。反正你有钱了，结婚了，成功了，还是会各种不开心的，人生之不如意十之八九，趁早学会没事儿偷着乐吧。人这辈子没有一劳永逸的事情，也没有过了某个点就万事大吉的magic point。心态要好，大家都是来地球玩一个RPG，反正最后分值都会清零的。啊，诸法空相，诸行无常，还是开心点好。

## 史蒂文

作者：史蒂文
链接：https://www.zhihu.com/question/52178718/answer/135219904
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

今年正好30岁，从反面回答一下吧，后悔自己25岁时没人告诉我的。

1. 25岁时，没人跟我说，**知识或者技能**这种东西，学到了就跟你一辈子，不管工作或时空跨度多大，新知和技能都能排上用场。
2. 25岁时，有人跟我说，**习惯**很重要，但没人跟我说重要到深度影响自己生活、人生选择和生命质量的程度。因为几乎大多数人，每时每刻都生活在形形色色的思维习惯、生活习惯中，比如健身、跑步、阅读、表达、写作、沟通、学习等等，所有影响我们生活工作结果的全是这些习惯。我们养成习惯，然后习惯养成我们。
3. 25岁时，没人跟我说，**围剿式学习**，就是吸星大法，通过观察对方的沟通、演讲、写作方式，从而**学习他们的思维方式、学习他们身上最优秀的思维习惯。**
4. 25岁时，没人跟我说，**真诚和诚信**有多么重要，真诚是领导力的真谛，诚信是商业的真谛，每个人的年薪、领导能力、商业成就全部都可以从这两个词汇里诠释。
5. 25岁时，没人跟我说，**父母正在逼近死亡**。年轻人可能心里想得更多的是幸福生活，但父母的年纪，他们年龄越大，越要去面临离开这一主题，他们担心被世界抛弃，担心自己在儿女生活中扮演不了什么重要价值，特别渴望回馈、关注和尊重，不管多忙，能多打一个电话就多打一个电话，能多在一起吃顿饭，就多在一起吃顿饭，能满足他们想要的，不管大小，尽量去满足。
6. 25岁时，没人跟我说，**睡眠其实真正决定了生命的效率**。因为睡眠决定着第二天的心情、状态、专注度等，而心情、状态、专注度直接影响结果，我们的现在就是由大大小小的这些结果构成的。所以睡个好觉可能是让生活变得更好的最大的捷径。
7. 25岁时，没人跟我说，保持自我，并不断变得更好，其实在一段感情里，远比委曲求全，一味地宠溺对方，更重要。保持自我可以测试出和对方是否合拍，不断变得更好，可以让感情更深刻而持久。千万不要因为孤独、无助、父母逼迫、个人面子、焦虑等原因仓促地选择一个人。这个人是自己生命的一部分，对自己施加着无以复加地影响，所以谨慎点，即便单身都比错误好很多。
8. 25岁时，没人跟我说，利用所有的感官去体验周遭的世界是那么重要，**刻意发现生活的美**，发现细微处的不同，会给自己带来很多小惊喜。

## [总结帖](https://www.zhihu.com/question/52178718/answer/445113848)

作者：冯汉
链接：https://www.zhihu.com/question/52178718/answer/445113848
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

小冯将其归为了九大类，分别是【自我学习】、【家庭恋人】、【理想生活】、【思维转换】、【重要品质】、【投资理财】、【工作效率】、【必要社交】、【保持健康】。

一.【自我学习】

1. 努力的学习知识或技能，学到了就跟你一辈子。
2. 习惯很重要，重要到深度影响自己生活，人生选择，和生命质量的程度。
3. 围剿式学习，通过观察对方的沟通，演讲，写作方式，从而学习他们的思维方式，学习他们身上最优秀的思维习惯。
4. 讲话速度慢下来，有意识的培养自己讲话的逻辑性和条理性，多用陈述句。
5. 参与话题讨论程度慢下来，在一群人闲聊时，不用总是立即接上一些立马想起来道听途说的新闻性内容，牵强附和聊天气氛，并时常把群体聊天注意力集中在自己身上。
6. 养成自己思考事件来龙去脉的习惯，梳理自己的思维过程，反思自己或者人性中的本性，并不要试图去指导别人。
7. 学习英语，用恶魔奶爸介绍的方法，每天1到2个小时，坚持两年。
8. 读书，使用微信阅读等工具刷书，每天1到2个小时，逐渐缩小阅读面，尝试深度阅读，每次阅读完都要尝试输出。
9. 近乎残暴地训练你的判断力和筛选力，每一个人都有一长串梦想清单，每个人都有一长串待办事项，你要知道每一个渴望，每一个动心，都有可能是坑，它们都将像黑洞一样消耗和占据你的注意力，让你的精力和决心都越来越分散。
10. 坚持1到2个兴趣爱好，不要浅尝辄止，要深度介入。
11. 为了更好的自己，考研。
12. 萃取自身的可迁移能力，技能，专业知识并非一份工作的精髓，在一个指数式变化的社会，一份工作的精髓在于给你提供了一个（萃取可迁移能力）的机会。（可迁移能力是指你从一个岗位转到另一个岗位，或者从一个行业跨到另一个行业后可复用的能力。）
13. 将个人能力成长，长成一棵树，而非杂草丛生。
    1.第一步，首先得有一个应用目标，
    2.第二步，画出个人的能力树。
        1. 一级分类为核心素质，通用能力，专业技能和各类知识。
        2. 核心素质和通用能力下的明细分类相对完整，而且识别出了最基本的素质和能力。
    3.有步骤的点亮能力树。
14. 学会演讲。
15. 看Ted，有一天出自己的Tedx。
16. 大胆发言，这个年龄只有靠大胆发言，才能有机会展示自己的能力。

二.【保持健康】

1. 每天都保持锻炼，或者养成每周周期性跑步的习惯。
2. 适当休息是无价的。

三.【家庭恋人】 

1. 父母和最爱自己的亲人正在逼近死亡，以后要多给他们打一个电话，多陪他们吃一顿饭。
2. 在恋情中保持自我，可以测试出和对方是否合拍，不断的变得更好，可以让感情更深刻而持久。
3. 去爱一个人，感情天长地久固然是好，只有经历过，你才会知道在今后该如何对待一段感情，让爱人成为亲人。
4. 把最好的脾气留给家人。
5. 趁有时间多去尝试，多去恋爱，顺便积累恋爱经验。
6. 缘分不是等来的，努力地去争取。
7. 恋爱或者平时交往要勇敢自信。

四.【理想生活】

1. 利用所有的感官去体验周围的世界是多么重要，刻意发现生活的美，发现细微处的不同，会给自己带来许多小惊喜。
2. 一天24小时，22小时用于眼前的苟且，2个小时用于诗和远方，即使天马行空，即使不被外人所理解，但这有何妨？

五.【重要品质】

1. 真诚和诚信很重要，真诚是领导力的真谛，诚信是商业的真谛。
2. 拒绝重复，拒绝无聊，拒绝拖延，马上行动。
3. 学会忍受孤独，25岁以后离结婚越来越近，离单身越来越远，你真正为自己而活的日子不多了。
4. 努力的去分享，给予。
5. 不惜一切代价地完成独立。
6. 了解并用吸引力法则，好心情吸引来好的事情，好的事情反过来又促进好的心情，这是一个良性循环。
7. 正在年轻的时候，即使你知道再多“今后可能受益终身”的事，即使你下了再大的决心，即使你做了再周密的计划，如果没有坚持下去，你依然可能一事无成。
8. 真诚帮助他人。
9. 多与人交流，多去了解不同人的生活和想法。

六.【思维转换】 

1. 重建现实观，开眼看世界，把关于完美生活的一切幻想都放下，彻底放下。
2. 意识到这个世界上99%的人不是傻子就是骗子，媒体、信息、内容、知识全都是生意，背后都是不同利益集团和个体在操纵，而我们只不过是一茬茬被收割的韭菜而已。
3. 不要让专业限制你的选择，除对技术要求较高的职位，毕业去公司通过实际工作中学习，是完全可以掌握上手工作的。
4. 不要怕犯错，年轻没有失败。
5. 多开拓些思路，要更大范围去了解不同领域的发展、见解，跳出自己熟悉的系统，反过来再来思考自己熟悉的领域。
6. 拿自己做实验，你自己到底是谁？到底适合什么样的生活方式？没有人能告诉你，只有实验和自己的体验，不会骗自己。
7. 将时间花在重要的事情上，不要因为自己顺手就去做那些不重要的事情。
8. 25岁这个特殊的节点上，增加的应该是具有基础性、支撑性的四梁八柱。

七.【投资理财】

1. 适度消费，消费用于投资自己的见识，加深与朋友的关系。
2. 要存钱，花掉1/3来进行自我提升。
3. 学会理财，开始学着投资股票和基金。
4. 学会化妆，所有姑娘的颜值都会提高两分。
5. 给自己买一份重疾险，给自己留一个保底。
6. 一定要存一笔，当老板要解雇你或者让你去做你不愿意做的事情时，你就可以很有底气地去辞职。

八.【工作效率】 

1. 保证好自己的睡眠，睡眠其实是真正决定了生命的效率。
2. 记录时间，利用好碎片时间来提升自己。何时app（有广告）.
3. 学会利用工具，磨刀不误砍柴工。

九.【必要社交】

1. 加入一个公益组织或者NGO
2. 从零开始做人，完全的基于人品积累人脉，建立基于人情的人脉圈子。
3. 缩小朋友圈，维护好。（与4不冲突，增加自己有效朋友圈比例。）
4. 多交朋友，不要混迹于那些纯社交的饭局。饭局还是小的好，能交换更多的信息，说更多的心里话，在这些活动中找到志趣相投的人成为好朋友，找到人品好的人成为合作伙伴，找到贵人帮助自己成长，也尽力帮助更多更年轻的人。

人生在勤，不索何获。  ——张衡《后汉书-张衡列传》