---
title: 读《世界文明史·近东》
author: 王致远
date: '2019-03-01'
slug: history-of-civilization-02
categories:
  - 读书
tags:
  - 读书笔记
---

从这里开始，这本书就进入了正题——世界各个时期，各地的文明。文字也变得具体、生动、有趣起来。

### 苏美尔

一开始介绍的当然是人类历史上最古老的文明——苏美尔文明。它起源于两河流域（幼发拉底河和底格里斯河之间，也叫美索不达米亚平原）。历史从公元前40世纪-公元前24世纪，后被阿卡德（两河流域的另一文明）所灭，其文明被苏美尔和阿卡德的后裔——巴比伦人所继承。

苏美尔文明的主要成就：**创造了人类历史上的最早文字——楔形文字**。楔形文字是用铁笔写在湿的泥板上，然后在太阳下晒干，上面的文字就保留下来了。虽然相比中国刻在竹简上更加麻烦，但令人惊奇的是，竟然考古出土了当时的图书馆，存放了3万块泥板。苏美尔人还学会了冶炼金属，造出了青铜。

作者的评价是：

> 我们可以获得一个简单概念：阶级分明，活动庞杂，资源丰足，分配不均。苏美尔所显示的，可以说是整个人类历史的基调。

### 古埃及

古埃及是四大文明古国里最古老的，也是文明程度最高的古国，位于尼罗河中下游地区（非洲东北角）。由于埃及西部和南部与非洲大陆由沙漠隔绝，所以其受非洲其他地方影响较小，受西亚影响更大。文明形成于公元前30世纪，终止于公元前30年，长达3000年。古埃及历史可以分为五个朝代：前王朝、古王国、中古王国、帝国、新王国。朝代交替时候是乱世，朝代时期是治世，和中国历史很像。

作者赞叹到：

> 尼罗河文化不但风格特殊，而且其深厚、壮阔、细腻，别说刚刚草创的苏美尔文化无法与之媲美，就是拿它和已有高度发展的希腊或罗马文化相比，也不逊色。

古埃及文明的起源和尼罗河的定期泛滥有密切关系。尼罗河定期泛滥时，就会携带沃土冲击埃及土地，留下沃土后泛滥结束。所以埃及人只需观测、记录好尼罗河泛滥，在泛滥结束后播种，种植庄家，就可坐等收成。而不是像其他地方的农民，需要辛苦的犁地，把土地养肥。所以在这样有利的农业条件下，古埃及文明会这么早熟。为了感谢尼罗河和黑土地，古埃及人将它们奉为神灵，男神叫奥西里斯（俄赛里斯），女神叫伊西斯，类似于中国的伏羲和女娲。除此以外还信奉太阳神——阿蒙神。伊西斯对于埃及有着母性的慈爱。

埃及的古王国时期也叫金字塔时期，主要的金字塔都是这个时代修的，最著名的是第四王朝的胡夫金字塔和哈尔法金字塔。胡夫此人有些像秦始皇，四处征战，好大喜功，利用战俘奴隶修建金字塔。之后第六王朝的佩皮也是个厉害的法老，统治埃及90年，但显赫一时后引发了埃及内乱，结束了埃及的古王国时期，进入第一中间期，分裂为南北朝（类似于中国的魏晋南北朝），受西亚影响的占据北朝，受非洲大陆影响的占据南朝。

中古王朝时期，埃及再次统一和强大，文明也更加快速发展。但这时候不修金字塔了，改修神庙了。中古王朝覆灭后，进入第二中间期，之后进入帝国时期，埃及达到鼎盛。这个阶段出现了几个有为的法老。图特摩斯一世使用军事征服，将埃及势力扩张到叙利亚和努比亚，修建了卡纳克神庙。图一世去世后，女儿哈特谢普苏特的女法老上位，利用女性细腻的统治，使埃及经济高度发展。其地位类似于武则天。之后其外甥图三世上位，毁掉了和哈女法老有关的名字和塑像。但他也不是个孬种，一上台便打压了西亚的反抗势力，牢牢地把西亚攥在埃及手中，被认为是古埃及最伟大的法老之一。后来又过了很久，拉美西斯二世上位，他便是《出埃及记》中所指的法老，他的时代被认为是古埃及落日的余晖，之后埃及就慢慢衰落了。公元前30年，埃及正式成为罗马的一个省。此后，埃及便不再在历史舞台上露面。今天，所谓埃及，除剩一个地名之外，几乎已一无所有。

> 埃及的灵魂根植于埃及人所创造的文化。

古埃文化的兴衰：

> 文化有如生命，一旦达到顶点，接着便会衰颓。

> 当时的几个文明古国，看起来颇像几座小岛。在这些小岛四周，尽是蛮族之海。文明代表财富和舒适，野蛮代表饥饿和忌妒。饥饿和忌妒像海浪不断冲向小岛，小岛虽筑有堤防，但一旦堤防破裂，小岛即被淹没。

> 富裕产生闲暇，闲暇产生文艺，埃及文化随着帝国威势，像正午的太阳，放射出万丈光芒。

一将功成万骨枯：

> 撑持着庄严、华丽、巍峨的神庙、宫殿及金字塔的，是无数工人及农夫。

古埃及工艺品的精致程度，就算拿到工业时代也算不错。

> 在蒸汽机发明以前，谈工艺，我们所有的东西，几乎古埃及件件都有。同时，就制作而论，他们有些东西且较我们所制者为佳。

古埃及富有的原因：**出口外贸型经济**。

> 古埃及远较邻近各国为富，主要有一个原因：进口者为原料，出口者为加工品。

古埃及的法律体系也很客观理性：

> 埃及人早就有了“法律之前，人人平等”的观念。

因为地理条件的优势，古埃及慢慢荒废了军事，使得财富太多、军力太弱。

> 埃及四周不是沙漠，就是大海，对于外来侵犯无所顾虑，不养兵不足为奇。

古埃及的政治体系也是皇权相权分立的，皇权是法老，相权是首相，很先进的政治体系。

> 行政首长称首相（Vizier），总理行政、司法及财政大权。首相秉承法老意旨，治理国事，同时又是贫苦大众的保护者。

古埃及的女性地位很高

> 自古及今，女性在社会上这么有地位，恐怕埃及要数第一。

古埃及人关于家庭幸福的思考，放到现在都很受用：

> **专注你的事业，美化你的房屋，爱护你的妻子。别使她饿着，别使她冻着……和睦相处，让她高兴，她会使你受益……假定你们相处不善，那你的家庭便会破败。**

夫妻互相为第一合法继承人，也是很神奇，两个没有血缘关系的人竟然在法律上是最近的关系。

> 根据婚姻的默契，丈夫的财产及其而后的收入，通通都得交付妻子掌管。

埃及人的性格特征：

> 埃及人是很实际的。他们很像今天的美国人：喜欢大场面，喜欢建造庄严宏伟的东西，勤恳节俭，埃及人是极端的保守派。埃及人的最大特色是实事求是，不发空论。埃及人可说是全世界最喜欢化妆的民族。在男女关系上，女性站在主动地位。

埃及的人才制度也是向社会开放的，类似于中国的科举制：

> 利用学习、实习进而出任公职的制度。

埃及的书不是苏美尔人的泥板，而是在水里种一种植物叫“纸草”，然后将纸草的茎削了，横排一层，竖排一层，用力挤压，让茎中带有粘性的液体渗出来，将两层压在一起。然后用埃及人自己发明的墨汁在上面写。装订的时候，将每一张纸草首尾相接，所以最后形成一个卷轴。

苏美尔的楔形文字还是象形的，而埃及人逐渐将象形文字演化为字母，成为了现在西方文字的雏形。

> 字母可算是东方人留给西方世界的最大的文化遗产。

埃及人在医学上也有成就。不过埃及人更相信疾病是因为鬼缠身，要驱鬼才能治病。用药物治病是排在后面的。这种观点在巴比伦等西亚国家也被广泛接受。甚至现在中国农村还有“巫医”的概念。

> 今天我们所吃的药物，不少即是尼罗河谷居民发明的。

> 身体不舒服，在埃及人看来，不是得病而是有鬼。

> 埃及人的日常生活，充满了符箓迷信。

埃及人这个认识很贴近中医养生的观点：

> 吃进身体的食物，除一小部分可以滋养身体外，大部分都是废物。这些废物如不清除，久之足以使人致病

古埃及不论金字塔还是神庙，都修得规模宏大。不是优美，而是崇高。

> 埃及建筑一度均充满这种精神：美为主要目标，但除美之外，尚需雄壮、气魄。换句话说，他们所追求的，乃男性美的极致。

> 这一建筑的目标，似在于就人类之想象所及，以美向神作最虔诚的贡献。

> 埃及人真是历史上最伟大的建筑师。

> 建筑与雕刻乃埃及艺术的主干，

> 浮雕，可算是雕刻与绘画之间的一座桥梁。

埃及的绘画的人物身体有种扭曲，将侧面图和正面图扭在一起。

> 埃及绘画和浮雕大致具有同一特色：线条美，构图差。

埃及人的日常生活很逍遥

> 埃及人很会过日子，他们白天努力工作，晚上则尽情消遣。

艺术源于精神的自由和丰富

> 凡富有生命的艺术品，均是发自艺术家活跃的心灵，一旦艺术家的心灵受到束缚，其所创造出来的作品必然气息奄奄、枯燥乏味了。

> 悲观主义的进一步发展，必然产生“及时行乐”的思想。

埃及的宗教

> 埃及的一切，彻头彻尾可以说都带有浓厚的宗教色彩。

> 由于（太阳）神鹰孜孜不倦地飞行，故埃及人特取之为宗教及皇室的标志。

埃及人还将各种动物奉为神灵：

> 游埃及大神庙，常使人有置身动物园之感。

> 蛇是智慧、长寿及神秘的代表。

埃及人认为生殖器代表了活力的创造：

> 埃及人性器崇拜之风极为普遍。

埃及人关于“不朽”的观念：

> 埃及宗教最为突出的一点，是特别强调“不朽”。

> 称心的天平，用羽毛做砝码，心里若存有一丝一毫的虚伪，心就会比羽毛重，心比羽毛重便不及格，不能复活。

埃及的祭师阶级，犹如中国的宦官，是政治体系里的毒瘤，一步步侵蚀埃及的政治健康。

> 埃及祭师具有两种作用：一、法老权威的支柱；二、社会秩序的秘密警察。

> 全国祭师自然形成一个阶级。

> 为了供应神，全埃及的财富几乎都集中到了祭师之手。

> 整个拉美西斯家族执政的朝代，人民是君主的奴隶，君主是祭师的奴隶。

也有法老曾想打破祭师阶级，但由于太过激烈，根基不稳，失败了

> 阿肯那顿想一脚就把祭师阶级踢开，可是他忘记了这个阶级所具有的权势。

### 巴比伦

生命与文明如何保持长盛不衰？不断注入新的血液，创造新的细胞。

> 文明有如生命，要生存必须和死亡不断斗争。生命和死亡斗争的方法，最巧妙的就是新陈代谢——不断创造新细胞，不断创造新生命。世界上，许多文明之所以绵延不绝，就是由于它们不断开创新境，不断注入新鲜血液。

巴比伦也位于美索不达米亚平原。巴比伦人的血统继承自阿卡德，文化继承自苏美尔。巴比伦在种族上有着许多闪米特的特点：黑头发，多胡须，肤色略黑。巴比伦曾由于图特摩斯三世的东征，沦为埃及的附庸。巴比伦历史的开端者，是一位强有力的人物——汉谟拉比。《汉谟拉比法典》于1902年在苏萨出土，条文刻于绿玉圆柱之上。汉谟拉比希望每一个人通过这部法典，知道什么是他的权利。巴比伦大城在公元前18世纪即已成为世界最为壮观的都会。巴比伦帝国在尼布甲尼撒死后30年崩溃。波斯人统治巴比伦达2个世纪后即转让给亚历山大。

#### 商业

尼布甲尼撒二世是巴比伦负有盛名的国王。尼布甲尼撒深知道路对商业的影响，故对筑路一事不遗余力。巴比伦商业的繁盛，有两大原因。第一，安全宽广的国道；第二，幼发拉底河从波斯湾至塔帕萨库斯（Thapsacus）的畅通水路。巴比伦财富的增加，和它成为近东贸易中心、进一步与地中海诸国发生商业往来，有着直接的关系。**巴比伦文明本质上是商业文明。**巴比伦盛时，其商务约占世界之半。巴比伦郊区，居然成为外国人投资的热点。大的钱庄，多半为世业，其所经营的项目，除借贷之外，还有房地产及商业投资。就有关买卖、借贷、契约、合伙、佣金、汇兑、遗赠、合同、期票、本票等研究，我们发现巴比伦的物质文明已发展到相当惊人的程度。

巴比伦是个商业社会，商业社会主张享受。巴比伦人虽在敌人铁蹄之下讨生活，但仍花天酒地欢乐不止。巴比伦盛行我们所发现的一种“女性化的衰象”。埃及人常轻视巴比伦人，说他们没有文化。

> 由于追逐口腹的享受，追逐感官的快乐，意志薄弱、精力衰败是必然的。

> 兴由勤奋，败由奢侈。

#### 法律

巴比伦最负盛名的便是《汉谟拉比法典》，它与罗马帝国的法律政治一样，被公认为是古代社会留给今人的宝贵遗产。以眼还眼，以牙还牙的“复仇法”是巴比伦刑罚法的开端。由于严刑峻法达几千年，以致遵守上述规定已成巴比伦人的第二天性。随着时间，巴比伦法律的发展有三大趋向：一、由天断到人断；二、从严酷到温和；三、从坐牢到罚金。

在商业法方面，巴比伦法律所保护的对象，主要还是债权人。巴比伦在这方面的一个原则是，**欠债必还**。一家财产，由诸子平分，保障了社会贫富差距不会太大，但不利于资本集中，诞生工业革命。《汉谟拉比法典》有一种一贯精神，**就是重视私有财产**。巴比伦在文学艺术方面的贡献，虽比不上埃及和巴勒斯坦，但以其商业法律而论，实非其他文化所能及。巴比伦人视文字仅为一种商业的工具。

#### 政治与宗教

巴比伦的王权受到三种限制：法律，贵族（含富商巨贾），祭师。由于国王的统治时间是有限的，但神的统治时间是无限的，祭师可凭借神的势力，使国君俯首听命。不少巴比伦祭师同时又是大地主、大厂商及大资本家。建造巴比伦者为商人，享受巴比伦者为祭师。在巴比伦，神庙越富有，道德越堕落。

神话里，提玛特又被称为混沌，这一来马尔杜克就成了征服混沌及开创天地的英雄，类似于盘古。巴比伦人相信，每人生来便有一个神，这个神能为你驱邪降福。希伯来人的所谓天使，就可能来源于此。鬼到了人身上，这个人不是得病，就是发狂。平常鬼为什么不敢扑人？因为人有神庇佑。但人若犯罪，神便会弃他而去。神既去，人失掉保障，因此随时都有碰到鬼的危险。

> 一切文化的开端，可说都离不开宗教。宗教给你勇气，给你耐心。

#### 伦理

巴比伦女性的地位，与埃及罗马相比是差多了。不过，若和希腊及中世纪的欧洲相比，巴比伦女性完全可以知足了。巴比伦人崇拜伊什塔尔，与中世纪欧洲人崇拜圣母玛利亚，似均有尊重母性及女性的意味，但在巴比伦无论如何也找不出欧洲人的那种骑士精神。巴比伦，女孩子和男孩子一样是有权利接受教育的。巴比伦人实行的是一夫一妻制。他们婚前男女关系颇随便，但结婚后便绝对不随便了。通常，男方先以礼物下聘，女方往往以高于聘礼代价之物为嫁妆。

#### 科学

商业必须精于计算，计算便会产生数学。数学加上宗教的要求，天文学便诞生了。美索不达米亚的祭师，一身兼有数不清的职务，其中之一是天文学家。天文学可算是巴比伦的特殊成就。他们把整个黄道先分为360度，然后，每度分60分，每分为60秒。可知现在世界通行的时制，1月分为4周，一天分为12小时（现改为24小时），一小时分为60分，一分分为60秒，显然来源于巴比伦。

现代数学、天文学、医学、文法、辞典、考古学、历史及哲学的基础知识，也是由巴比伦开创。

### 亚述

亚述这个国家也位于美索不达米亚平原，在靠两河上游的位置，时间晚于巴比伦。亚述很像战国时期的秦国，由于受到四境蛮族的威胁，自始至终对武力非常重视；由于百姓生活条件恶劣，民风剽悍尚武。武力的建立，最初在于自卫，但进一步发展后就是征服。**亚述从兴至灭，其最大特色为武力至上。**但正所谓“天道好还”，最初他们怎么屠杀与搜刮邻人，最后邻人又照样对待他们。以撒哈顿是亚述有名的君主，他把亚述变为近东最富最强的帝国。巴尼拔继承了以撒哈顿所建的基础，使亚述国势如日中天。在亚述巴尼拔时代，曾经统治亚述、巴比伦、亚美尼亚、巴勒斯坦、叙利亚、腓尼基、苏美尔、埃兰、米底亚和埃及。但物极必反，自他死后，由于40余年内战，国力消耗过甚，亚述从此一蹶不振。

#### 政治

亚述是完全的武力政权。在亚述人观念中，政府就是武力的别称。亚述政府是国家发动战争的工具。亚述法律，可以说就是军法。对其人民特别强调忠贞、纪律及爱国心。

亚述君主的第一个支柱是军队，其次就是宗教。亚述帝国的管理是很松散的，没有实施中央集权。亚述经济不能自给自足，它的生存要靠劫掠，然而劫掠要靠武力。因此，一旦武力不足恃，败亡立见。

> 东方君主政体的最大缺点，就是战乱相循的无可避免。所谓战乱相循，一则为地方或属国的不断反叛，一则为中央的王位争夺。

#### 军事

亚述人的战术，**特别注重急行军与各个击破**。这种战术也是拿破仑用以制胜的秘诀。将士功劳大小，以所斩敌人首级多寡为标准（与秦国很像）。在亚述，集体坑杀战俘的事，时常发生。(在历史上，优待战俘自亚历山大及恺撒始。)

#### 艺术

尼尼微民间家庭设备，其丰富程度已和工业革命前的欧洲不相上下。

亚述人特别喜欢在建筑上刻浮雕。但其建筑其无可救药的缺点是朽坏得太快，放不过100年，也许和他们建筑材质是砖块而不是石块有关。

在人类文化中，经波斯、马其顿而传至罗马的武器、战术、涡形柱头、女像柱头、分省统治，就是亚述人留下来的。

> 国度不同，审美观念亦有别。

## 腓尼基

> 这些小国家小部落，在别人看来，实在微不足道，可是在他们自己看来，他们每一个都是历史的主角、世界的中心。

这句话说得太好了，人类本性中同时有自大（想要通过自己的理论解释一切）与恐惧（对外部未知的世界），二者共同让人们觉得，自己是世界的中心。

在美索不达米亚平原，住在北部地区的为印欧族系统；住在中南部地区的，即从亚述到阿拉伯，为闪米特系统。闪米特发源生息之地为阿拉伯。

腓尼基在如今黎巴嫩及以北，叙利亚以西，地中海东海岸上，背靠山，面向海。类似于中国的潮汕地区，由于受山限制，海岸窄狭，所以注定腓尼基人非向海上讨生活不可。腓尼基人是做生意的民族。他们的船走遍每一处海域去做生意。

腓尼基人精于贸易，也精于制作小商品，包括了：玻璃、金属器皿、搪瓷花瓶、装饰品、珠宝、武器。但他们的贸易不是秉持公平正义原则的贸易。他们的行为往往因对象而异：弱则用抢；愚则用骗；不弱不愚，才和你规规矩矩做生意。这类行为，常使人一提到闪米特商人便痛恨不已。

腓尼基人的航海技术惊人，他们跨越地中海，出直布罗陀海峡，经非洲西北，绕好望角，最后竟到达非洲东海岸。是他们最先发现了好望角，较达·伽马早了2000多年。沿着航线，腓尼基人筑了不少要塞。著名的有加的斯、迦太基、马赛、马耳他、西西里、撒丁、科西嘉。

通过商业及文化，他们把东方和西方连接起来。欧洲从野蛮进入文明，腓尼基人功劳也不小。腓尼基对文明世界的贡献是他们把学自埃及的字母传播给了西方世界。不过腓尼基人是从右往左写的，字母到了希腊人手里，拼写就依照希腊人原来的传统习惯一律改为由左向右了。欧洲人是希腊人的学生，他们的书写习惯，自然也照老师的样子。

> 字母是一种了不起的发明。这一套神奇的符号是世界文化最宝贵的遗产。

### 叙利亚

大马士革的居民多半也是闪米特人。他们也是生意人，不过和腓尼基在海上开展贸易不同，他们组成商队沿着叙利亚平原山地道路从事贸易，不过也很富有。叙利亚的工匠也手艺高超，技术精良，他们能制陶器、木器，能雕刻象牙，能镶嵌珠宝。

大马士革的时尚、仪节及道德观念，一切均唯东方古巴黎——巴比伦马首是瞻。

> 性是人丁兴旺、禽兽繁殖、五谷丰登的表征。

> 叙利亚人对神的最大献礼，就是以自己亲生的子女为燔祭。

### 犹太

约旦河谷不断流着鲜红的血液。这些血液有些是为人流的，有些是为神流的。

其取代过程，显然是先用来记账，慢慢变成了文学及传播思想的媒介。

我们之所以重视犹太人，并不因其人口众多，也不因其幅员广阔，而是因为他们为世界提供了伟大的文学作品、影响深远的宗教及若干圣智的哲人。

巴勒斯坦是一个很小的地方

它对后世的影响，不但巴比伦、亚述、波斯赶不上，甚至连埃及或希腊也赶不上。

这块地区，自古即成兵家必争之地，因此，一次又一次战祸不断向它袭来。

巴勒斯坦变成了美索不达米亚及埃及的磨心，这是一种折磨，也是一种熬炼。

巴勒斯坦一度是“奶与蜜流经之地”，

雨量丰富，空气潮湿，因此颇宜于农作物生长。

整个巴勒斯坦，有着纵横交错的运河沟渠，农田需水，运河沟渠即可灌溉。

然而今天的巴勒斯坦，除少许绿洲外，大部分已属不毛之地。

犹太人相信，其始祖亚伯拉罕之先世，来自苏美尔的乌尔。该族定居于巴勒斯坦，约在摩西降生前1000年（约公元前2200年）。他们征服迦南，是膺天命，因迦南为上帝对他们的应许之乡。

关于犹太人进入埃及，我们既不知道时间，也不知道进入时的身份——奴隶还是自由人。

犹太人的生殖和苦难常成正比：“折磨愈大，繁殖愈多，生长愈速。”

犹太人征服迦南的事例，在近东可算是家常便饭——一个又饥又渴的游牧部族，向一个比较富足的农耕地区突袭。

从祖先开始，犹太人就已是若干种族的混血儿。

犹太人除非万不得已，不愿与外族通婚。

犹太人的形象仍是：一个长而带钩的鼻子，[4]两块突出的颧骨，卷曲的发须，瘦高而结实的身体。

犹太人的形象仍是：一个长而带钩的鼻子，[4]两块突出的颧骨，卷曲的发须，瘦高而结实的身体。除此之外，他们还有一颗刚愎而富于计算的心。

犹太人的形象仍是：一个长而带钩的鼻子，[4]两块突出的颧骨，卷曲的发须，瘦高而结实的身体。除此之外，他们还有一颗刚愎而富于计算的心。

犹太人说的是希伯来语。这种语言可以说是地球上音调最为铿锵的语言。

虽然征服了迦南，可是犹太人并未形成一个统一的国家。

家庭不但是犹太人的社会单位，而且是经济单位。一家人生活在一起，工作在一起。家庭成了他们力量的源泉、权威的象征、政治的基础。

其后，犹太人采用了家族共产制。

这削弱了家长权威，唤醒了个人独立意识。个人意识的觉醒

以色列人在那个时代，没有王，他们每一个人，只有朝着自己认为对的方向去做。

继扫罗为王者为大卫。他是击杀歌利亚（Goliath）[8]的英雄，以容貌俊美深获约拿单及无数美女的爱慕。

所罗门王登基之前，头脑异常冷静，把他的政敌一个一个加以肃清。

所罗门也许真的聪明过人。他是一位英明之主，确保内外和平，发展犹太工商业，使人民恪守法律秩序。

在他统治下的耶路撒冷，和平富足达到极点。耶路撒冷是大卫王所建之都，

为进一步发展商业，所罗门组成商运船队，经由红海与阿拉伯及非洲贸易。他更慷慨提供这条路给腓尼基人使用。腓尼基人过去与阿拉伯及非洲贸易，差不多都是取道埃及，但自此之后，他们便都转向巴勒斯坦了。
	[笔记]一带一路战略


所罗门有许多黄金和宝石。这
	[笔记]一带一路战略


所罗门聚集在耶路撒冷的银子，简直和街上的石头一样多。

所罗门修神庙，对犹太人而言，可以说是破天荒之举。

犹太人敬仰所罗门的智慧，却怀疑他对神的虔敬。

所罗门死后，犹太已民穷财尽。

他们这时所崇拜的目标，已不是威严赫赫的耶和华，而是一位像众先知所描述的，专以仁爱为怀的救世主。

因为圣殿——耶和华之家筑成后，长期流浪的犹太人，在精神上才算有了依托。

犹太人的教已由多神教进入了一神教。

摩西一再告诫犹太人勿崇拜邪神

人们之所以崇拜蛇，理由可能是：一、蛇为阳具的象征，拜蛇是一种变相的阳具崇拜；二、蛇首尾可以相接，故用以代表智慧、巧妙及永恒。

在犹太人的想象中，耶和华是一位好勇斗狠、秉性倔强、威灵赫赫的神道。

耶和华是所有神道中最具人性的神。

耶和华不是一位和平主义者，

宗教历来为政治的镜子，耶和华是当犹太在大卫及所罗门统治下结成一体，耶路撒冷修筑了圣殿，然后才奠定其全犹太唯一真神地位的。

在犹太神学中，“罪”是一个核心观念。罪是德的对应

犹太人在精神生活上，几乎时时在和罪恶斗争。

德、罪、奖、惩，在他们看来一律都是现世的。

德、罪、奖、惩，在他们看来一律都是现世的。犹太人的“复活”观念，是在他们国破家亡后才兴起的。

复活观念的兴起，对犹太人影响很大，因为它，基督教才开始萌芽。

有罪就会收到恶果，如何解除此项威胁？第一是祷告，第二是牺牲。

割礼，显然是牺牲的遗迹。用一部分代全体，神享用了包皮，即等于享用了整个的人。

先知对犹太宗教的影响不小。由于他们来自民间，深知民间疾苦，因此他们所说的，大都是民众的心声。这批人思想深刻，观察敏锐，感情丰富，犹太教之所以后来能风靡整个西方世界，可以说得益于他们事先所作的一番整理、提高、净化之功。

一个社会，当财富集中于少数人之手，大多数人便自然陷于贫穷了。

经过20多年的精心擘划，犹太社会是工业化了，可是由于长期沉重的徭役赋税，大多数人的生活资源已被榨得精光。

人民生活困苦的原因，一方面在于贵族的压榨，一方面在于富人的剥削。

所罗门死后巴勒斯坦便一分为二：北方称以法莲[20]，以撒马利亚（Samaria）为都；南方称犹太，以耶路撒冷为都。南北对立，苦战不休，犹太从此即趋式微。

埃及人攻下耶路撒冷后，便动手加以搜刮。这一次他们把所罗门多年聚集的金银财宝差不多都搬光了。

先知多半具有悲天悯人的性格。

犹太人的先知，可以说都是“街头政治家”

一般先知并不以其预言足以兑现为能事，大都只是指出时弊，吐出愤懑，描述希望。

以赛亚，犹太人最伟大的先知，

任何一个国家，任何一个社会，凡有经济剥削存在，却又承认经济剥削合理，其势必不能长久。

以赛亚对那些一方面剥削穷人，一方面假装伪善的人，更是深恶痛绝：

他最后的预言是，流亡在外的犹太人，有一天必能回到故乡重建家园

以赛亚对犹太民族的最大贡献，是提出了弥赛亚救世主的思想。

阿摩司和以赛亚的思想，可以说是基督教思想的发端。

阿摩司与以赛亚所预言的救世主，纯洁、慈爱、友善诸德行，大部分已由耶稣基督体现。他们更共同努力完成了耶和华的改造工作：在此之前，耶和华是“战神”；在此之后，耶和华是“爱神”。

犹太对当代世界最大的影响，是他们编撰了《圣经》。

我们相信，《圣经》是积年累月的产物。

圣经》内容包罗万象，其中有传说，有历史，有诫命，有律法，有预言，有诗歌。

继臣服于亚述之后，犹太还得臣服于埃及和巴比伦。

攻下耶路撒冷后：第一，将全城夷为平地；第二，把所罗门所建圣殿捣毁；第三，让西底家亲眼看着其诸子被杀后，再挖出其眼睛；第四，将全城人掳至巴比伦为奴。

在耶利米时代，犹太罪恶充斥，政治腐败，教会堕落。

而以赛亚所说的则是，耶和华是宇宙中的唯一真神，他的慈爱无边无际。

以赛亚说，救主来不是为了统治，而是为了服务。

我是耶和华，在我以外并没有别神，除我以外再没有神。

和今天一样，回到故乡的犹太人，立刻发觉他们竟是不受欢迎者。因为这个地方，自他们离开后，另一批闪米特人来了，在这儿生息繁殖。

回来的人一天一天增加，耶路撒冷慢慢又成为犹太人的天下。

犹太人是提倡疾病预防的鼻祖，

割包皮，犹太人称之为割礼，在古埃及与现代闪米特间非常盛行。割礼，从一方面来说，是对上帝尊敬、对民族忠诚的表现，[35]另外，也是预防性病的一种方法。

以色列人，乃上帝卫护者之意。

由于确信宗教的统一与社会的统一不可分，不容忍便成了他们的特性。

由于歌唱足以使充满苦难的生活获得安慰，乐队基于宗教颂圣的要求，因此皆能得到相当的发展。据

家庭是犹太社会的基石

犹太人在很古的时代所行的婚姻制度，是把男孩子嫁出去。成

在犹太社会里，妇女常能出人头地。

第一，痛斥独身主义；第二，视妇女不生育为罪大恶极；第三，严禁堕胎和杀婴。

任何限制人口增加的做法，在犹太都是异端和不讨上帝喜悦的。

犹太民族相当好战。

犹太是个精力充沛——充沛到横冲直撞，无比虔诚——虔诚到把自己孤立起来，敏感热情——由此创造了近东第一流文学作品，勇敢坚毅——以致历尽折磨仍巍然独存的民族。这个民族是值得我们刮目相看的。

对夫妇而言，爱情地位并不重要。

新娘有了嫁妆，到夫家便有地位，因为她已与用钱买来的不同。

犹太人对其妻子儿女的爱护，可以说是无微不至的。

结婚前，男女不一定有爱情，但结婚后，夫妻情谊甚笃者却屡见不鲜。“

第八诫，确立私有财产制

耶和华也很希望犹太财富增加，他曾说：“你只可把钱借人，不可向人借钱。”

犹太富人对穷人比较仁慈。

安息日，不但自己休息，也应让雇工、奴隶乃至牲畜休息。

按犹太人的习俗，对无家可归的外邦人，也要亲切招待，供他吃，供他住，给他礼遇和尊敬。耶和华常常提醒犹太人，要记着你们也曾流落异乡无家可归。

它对犹太人的影响，与其说是行为上的，毋宁说是精神上的。

由于圣诗所抒发的是一种宗教感情，因此它充满了恶毒的诅咒、凄苦的呻吟与热烈的赞颂。赞颂的词句，占了诗中的绝大部分，因此圣诗又可称之为“赞美诗

《箴言》所针砭的坏事，好色之外，就是怠惰

箴言》的作者也不鼓励雄心壮志。

戒多言，也是《箴言》劝世目标之一。智者多做，愚者多说。“

《箴言》中一再提到的是道德和智慧。

人有智慧就有生命的泉源。

人生之幸与不幸，全与善恶无关。

人的命运不由善恶决定，于是，好运、坏运便只有看机会了。

在你一生虚空的年日，就是神赐你在日光之下虚空的年日，当同你所爱的妻，快活度日。

因为多有智慧，就多有愁烦，增加知识的，就增加忧伤。

我见人，莫强如在他经营的事上喜乐

凡你手所当作的事，要尽力去作。因为在你所必去的阴间，没有工作，没有谋算，没有知识，也没有智慧。

犹太人在作《箴言》时，是何等推崇智慧，现在，智慧竟一文不值了。

耶路撒冷，犹太民族的象征，建了毁，毁了建，自有人类历史以来，已不知重建了多少次。

事实上，若不是整个世界因科学技术的发展，在经济政治上结为一体，要想世人同奉一位上帝是很困难的。

## 波斯

米底亚对波斯文化的贡献有：雅利安语言，36字母，以羊皮纸和笔代泥板的书具，米底亚柱廊

君主专制制度，可以说是一种含有巨大冒险性的赌博。继位者精明能干，则兴；继位者昏庸腐化，则衰。

一兴义师，米底亚便不战而亡。米底亚人对居鲁士不但没有抵抗，而且非常欢迎。

我们对于居鲁士可得出六点认识：第一，他是一位美男子

第二，他建立了波斯帝国

第三，他把波斯及米底亚部队，编练成一支战无不胜、攻无不克的大军；第四，他攻下了萨迪斯及巴比伦，结束了闪米特人在西亚长达1000余年的统治；第五，他承受了亚述、巴比伦、米底亚及小亚细亚诸国的版图，而形成了罗马以前最大的帝国；第六，他是有史以来最善于统御的一位君主。

波斯居民是强壮勇敢的山地民族。

雅利安”（Aryan）与“伊朗”（Iran）是同义语。

波斯人可以说是近东各民族中长得最英俊的。

在波斯人观念中，学书学写，太文绉绉了，人们不应把时间用在这方面，而应习武、下棋甚至谈恋爱。

波斯人善饮，居鲁士还以酒供应部队。波斯大臣讨论国家大事前，必定要先喝酒，很多大事都是在喝酒之后决定的。

我们所认识的居鲁士，是有史以来最擅长征服、最宽仁厚德的国君。他的宽仁厚德，也许正是他所向无敌的原因。

他的政策是：波斯国内各民族，应该享有信仰的自由。过

居鲁士与拿破仑相同的另一点是，他们的失败都在于野心过大。

康比斯继位为王，但他完全不像乃父。他狂暴嗜杀，贪得无厌，处理事情更神经兮兮。

这些失意的事加在一起，使康比斯精神错乱了。

大流士受贵族推选为王

他以无边的暴力及迅雷不及掩耳的手段，镇服了各地方的叛变。

在他治理下，数十年间西亚获得了无比的安定与繁荣。

大流士进入爱琴海，兵败马拉松，丧师归来，企图再攻希腊未成，便忽然生病而死。

在大流士极盛时代，波斯帝国有20个行省。其版图囊括了整个埃及、巴勒斯坦、叙利亚、腓尼基、吕底亚、弗里吉亚、伊奥尼亚、卡帕多西亚、西里西亚、亚美尼亚、亚述、高加索、巴比伦、米底亚、波斯本土、现在的巴基斯坦俾路支（Baluchistan）、印度河西岸、粟特（Sogdiana）、大夏（Bactria）、玛萨基提及中亚的一部分。

境内又多山多沙漠。这块地方冬季严寒，夏季酷热

影响波斯人生活的主要因素为政治、军事，而非经济。

影响波斯人生活的主要因素为政治、军事，而非经济。换言之，波斯财富的累积靠的是权力，而不是工商业。

波斯王的意旨具有绝对性。

宦官由于其地位特殊，或为王的近侍，或为太子师保，在宫廷中具有莫大的影响力。

王权的真正支柱，也可说整个帝国政府的真正支柱是军队。事

波斯是全国皆兵

波斯部队的军力，素以人马众多著称。

任何一支部队只要组织严密、训练有素，即使人数少，亦可使之溃不成军。

司法界相当清廉，因为贿赂一经证实，行贿者与受贿者都是死罪。

除省长、将军与监察三者分立制衡外，国王更常派情报人员为其耳目

在其治理下，尽管苛捐杂税一大堆，但老百姓因有和平及秩序，所以渐渐都富足了起来。

每一个地区可以保留自己的语言、法律、风俗、道德、宗教、钱币。

波斯治绩之隆，当以大流士一世为最高峰。

查拉图斯特拉就是祆教的始祖。

阿胡拉·玛兹达与阿里曼，一神一魔鬼

查拉图斯特拉所描述的阿胡拉·玛兹达具有七种特性（或为七方面之代表）：光，理性，正义，统治，虔诚，幸福，不朽。

按查拉图斯特拉最初的想象，所谓恶魔只是一种抽象的、阻碍人类幸福、安宁、进步的邪恶势力。

基督教有上帝，它有阿胡拉·玛兹达。基督教有撒旦，它有魔鬼。基督教有天使，它有守护神。

在查拉图斯特拉的想象中，宇宙是一大战场，每人是一小战场，在这些战场上，善与恶时时刻刻在斗争。人命中注定一生下来就得作战。人在作战时，不是站在善的一边，就是站在恶的一边。

按经上说，人之职责有三：“使自己由敌人变成朋友，使自己由邪恶变成正直，使自己由无知变成博学。”

这种民族优越感，其实不仅波斯有，几乎各时代各民族都有。

每座神坛，必燃圣火。

据说一个虔诚纯真的祆教徒是绝不怕死的。这也许就是祆教之所以受波斯政府重视的理由。

善多于恶，则当先下炼狱洗净其罪，然后升天。

希腊人常常对谁都不相信，可是就相信波斯人。

波斯的历史尽管充满了血腥味和铁臭味，但其人民生活是极温文尔雅的。

像犹太人一样，波斯经典亦视肉欲为大罪。手淫者要挨皮鞭。男女苟合被视为大罪

经典不但不鼓励独身主义，而且容许多妻及纳妾。

波斯妇女地位的下降，始于大流士之时。

堕胎被视为大恶，故对堕胎者有杀无赦的规定。

波斯男孩5岁以前由妈妈哺养。5岁至9岁，由爸爸管教。

学生黎明即起，先跑一大段路，然后骑马。

穷人付不起医药费，可到祭师那里去求治，因为祭师治病是免费的。

甚至所有波斯艺术品都是舶来品。

希腊人是聪明过人的民族，

波斯花了1000多年的时间统一近东，其所作所为，似乎特意在为希腊的起飞做准备。

大流士一手所建立起来的波斯大帝国，维持不到100年便烟消云散。

波斯的式微，和罗马的式微走的是同一条道路：在上者，残暴、愚昧；在下者，腐化、堕落。

波斯贵族把吃列在第一位。由

居鲁士及大流士是波斯帝国的缔造者，薛西斯是继承者，以后的君主，则是败坏者。

一个人往往外表漂亮，内心便非常空虚。

自薛西斯一世开始，此后，波斯宫廷谋杀即史不绝书。

帝国的土崩瓦解，中央武力衰颓是一层原因，另一层则是被征服者时时均有恢复自由的渴望。

有些帝国，原也包含许多不同国家，但因统治者目光远大，在其武力鼎盛时代，运用种种办法将这许多国家同化，使整个帝国成为一个有机体。

亚历山大现在冲劲十足。他的兵在波斯帝国境内，有如秋风扫落叶。

“如果我是你，”亚历山大的副帅帕尔梅尼奥（Parmenio）对亚历山大说，“我便接受了。因为向前，胜负很难预测。”“如果我是你，”亚历山大说，“我便接受了。但可惜我是亚历山大。我只知向前，不问胜负。”

亚历山大此时只有骑兵7000、步兵4万，然而，面对波斯百万大军，他竟毫无所惧。

凭着精良的武器，凭着卓越的指挥，凭着无比的勇气，

当他把波斯并为马其顿帝国的一省，并为其留下一个干练的守将后，旋即整兵向印度进发。