---
title: 读《世界文明史》（持续更新）
author: 王致远
date: '2019-02-12'
slug: history-of-civilization
categories:
  - 读书
tags:
  - 读书笔记
---

# 东方的遗产

## 文明的条件

所谓“文明”的内涵：

> 在发明的进步方面，在经济组织的变动方面，在政府组织的尝试方面，在宗教的热情方面，在伦理与礼仪的盛衰方面，在文学的精华方面，在科学的发展方面，在哲学的智慧方面，以及在艺术的成就方面，都能依时代并用默察方法有条理地进行叙述。

文明的定义：

> 文明是增进文化创造的社会秩序。它包含了四大因素：经济的供应、政治的组织、伦理的传统及对知识与艺术的追求。

文明的原动力：

> 一旦恐惧被克服，好奇心与进行建设的欲望不受约束，人们自然便会产生进一步了解并改善生活的冲动。

> 文明在农舍里播种，但只在城市里开花。

> **文明不是由伟大的种族创造的，相反，伟大的文明创造了民族。文明是世世代代种族的灵魂。**

文明之于种族，类似于习惯之于个人。个人养成习惯，然后习惯塑造个人。

### 文明的经济条件

> 食物的共同需要，有助于国家的形成。分析到最后，文明是基于食物的供应。

> 豢养家畜、繁殖牛羊与饮用兽奶，在人类发展中具有举足轻重的作用。牲畜繁殖的奇迹是人可以控制，

> 人们接受了贮存食物以备将来之需的教训。

> 人类从兽类步入文明的三个步骤——语言、农耕与写作

> 和狩猎相比，农耕获得的食物既好又稳当。

想起《采购与供应链管理》中将两种供应商管理模式比喻为“狩猎式”和“畜养式”。欧美车企使用“狩猎式”，利用市场来寻求供应商；日本车企使用“畜养式”，精心培育核心供应商。

> 火的发明多少限制了不分青红皂白的暴食乱饮，并配合农耕，使人类脱离了狩猎。

> 工业的开始就是火。

> 人们一贯以棍棒作为代表权力与权威的象征。

打狗棒，权杖，魔杖……

> 之后是一个由火来代替日光的阶段，制作出不少奇形怪状、有很多用途的容器。

> 另外，有三项进一步的发展是原始人类用来创造经济文明的必要要素：运输的机械装置、贸易的进展与交易的媒介。

物质流，信息流，资金流，商流

> 轮子——这是在机械发明里最伟大的一件事

> 河流便成了最方便的运输大道。

直到火车的发明，让无河道的内陆也能依靠铁路像水运一样便捷。

> 这些具有专长的部落或村落，有时用他们从事的行业作为姓氏，如铁匠、渔人、窑匠等（Smith，Fisher，Potter……）。

> 拥有过剩物品的人，通过交换满足了自己的所需。

> 最早期的交换媒介，都是一般必需品。

> 牛在当时轻而易举地变成了猎人与畜牧人用来做交易的媒介，并用来作为价值的标准。

### 文明的政治条件

> 贸易在原始社会引起了相当大的骚动，因为它的出现带来了金钱与利润，进而有了财产，然后有了小的政府组织。

> 在原始社会中，几乎所有的土地都是公有的。

> 在“未开化”地区有食物的人，总是与缺乏的人分享。

> “当你看见他们相互之间是如何以礼相待，而这些都是在极度文明的国家里所看不到的，你一定会大为吃惊

> 我的”与“您的”两个词的概念，已熄灭了我们慈悲的火焰，点燃了贪婪的欲火，这些都是野蛮民族闻所未闻的。

> 他们都把自己当成一个大家庭里的人来看待。

原始社会是公有制的，所以中国古人常羡慕尧舜时期民风淳朴。

> 共有意识是非生物学的，是生存竞争中的一个障碍，不能激励各项发明、工业及繁荣。共有意识给由于贫穷与无知而生活在疾病与灾害盛行的原始社会中的原始人类带来了安全感，但这些安全感绝不能使他们摆脱贫穷。

> 人类从狩猎进入农耕阶段，并由此引发了由部落财产变为家庭财产的改变。农业虽然创造了文明，却也带来了私人财产制度，还带来了奴隶制度。

懒惰的根源：

> 原始人类的懒惰特性有其根源，一般推测是源于由战斗与打猎造成的过度的疲乏而养成的慢慢休养恢复的习惯。

> 人类终止了同类之间的杀害与相食，仅仅是使之成为奴隶，这是伦理上的一大进步。

> 战争助长了奴隶制，奴隶制也助长了战争。

> 由于奴隶增加，财富也随之增多，而为少数人提供了悠闲，也更间接地促进了文明。

> **每种新的发明，都是强者手中的工具，用来作为增强主宰地位并使役弱者之用。**

> 富与贫成为牢不可破的财富与穷困的意识，阶级的斗争像一条红线贯穿了全部的历史，进而国家兴起并成为阶级管理、财产保护、战争发动及和平组织的不可缺少的手段。

> 人类天赋的不同，加上而后的机遇不同，便产生了财富与事业的人为不平等。

> 因此原始的共产主义的梦想，潜入了每个现代的社会。

> 定期性地，不管合法与否，土地被重新分。

> 所有的经济历史是自然地集中财富和爆发革命的社会历程。

这就是“话说天下大势，分久必合，合久必分”的原因：革命之后，新的阶级分层逐渐固化，财富集中越来越扭曲，然后爆发新的革命。

> 最早具有持续性的社会组织形式是家族。几个家族结合起来，在同一个酋长的管辖之下就形成了部落，这是成为国家的第二个步骤。战争产生了酋长、国王及国家，正如他们又酝酿了战争。

> 社会由两种权力管制：平时用言语，战时用刀剑。

从“时代意见”的视角看待战争：

> 战争的影响是深远的，它残酷地充当了衰弱民族的清除器，而提高种族在勇气、暴力、残忍、智慧和技能上的水准。它刺激发明，使武器变成有益的工具并使战争的艺术变成和平的艺术。**繁荣为国家之母，而战争则为其父。**

