---
title: 张小龙在微信公开课上的演讲摘抄
author: 王致远
date: '2019-01-20'
slug: speech-of-xiaolong-zhang-about-wechat
categories:
  - 时事社论
tags:
  - 读书笔记
---

讲到设计微信时的原动力：

> 原动力应该是你内心深处的一种很深的认知或者希望。它很强大，以至于说它可以坚持很久，并且你克服很多困难都要去做到它。

微信的原动力首先是一个好的工具，一个好的朋友。

> 做一个好的工具，对于我来说，我觉得是可以并且值得痴迷的一个事情。

> 所以对于微信来说，我们会有这样一些底线，要做一个好的工具，而且可以陪伴你很多年。

> 微信是一个生活方式。

微信的第二个原动力时一个好的平台：

> 当一个平台可以造福人的时候，它才是有生命力的。

> 这个时候我们的原动力是让创造价值的人体现价值。

小游戏的原动力时创意的平台：

> 小游戏的原动力是，它应该是一个关于创意的平台。并且让产生创意的人体现价值。

张小龙讲到对于社交的理解：

> 沟通就是把自己的人设强加给对方的过程。

> 发朋友圈，其实就是把自己的人设带给所有朋友，放到所有朋友的脑袋里面的过程。所以朋友圈是一个表现自己的地方。

> 其实我们人的社交是没有发生改变的，或者说社交的需求并没有发生改变。

> 线下的社交效率是比较低的。因为它要跨越地理和时间才能做到。

> 朋友圈本质上是一个什么，朋友圈其实开创了一个新的社交的场所，其实它不止是一个时间流。我把它比方成一个广场。

讲到微信正在做的即刻视频

> 我们要做的是，能够让一个人真正的去记录他正在经历的东西，然后让他的好友来看到。

> 朋友圈已经变成了一个很传统的社交的地方，就是我们每个人在里面展现自己最美好的一面来获得他人的认可。

讲到在微信上阅读和“看一看”的功能：

> 本质上其实我们并不是在做阅读，而是每一个人在帮助其他人阅读，它是一种社交性的阅读。

> 所以我们并不考虑什么是信息流，而是用一个什么样合理的方式来展现信息。

讲到AI技术：

> AI是要落地到我们实际的一个功能或者是场景里面去的。

> 好的技术是为产品服务的，

> 传统说的工具，是人来驾驭工具。但是当AI很强大以后，AI可能是可以驾驭人的。

> 这种工具扩展了人类的某一种能力，使我们通过这个工具变得更强大，PC其实就是这样一种东西，它也是一个工具，它可以使人类变得更强大一些。

讲到与用户的关系：

> 在微信，我们要时刻提醒我们自己的是，我们自己就是用户，我们施加于用户身上的，最终也会施加到我们自己身上，有点像己所不欲勿施于人。

> 我们对于用户的态度上必须是一种善良的态度，而不是一种套路的态度。所以这种善良是一种基于理性之上的善良。

讲到卡包功能的设计初衷：

> 改变的结果是希望通过消费的行为和电子智能做一种自动的关联，变成人与线下消费连接的通道，实现更好的连接。

讲到企业微信：

> 企业微信后续新的变化是基于一个新的理念——希望让每一个企业员工都成为企业服务的窗口。

> 企业可以让所有的员工变成一个对外服务的窗口，带着你的小程序到处跑。

讲到微信的未来方向：

> 我们用户数的增长是自然而然增长的过程，对我们而言，我们要考虑的是对我们已有的用户提供什么服务，这个更重要的问题。

> 在这个时代下，创新才是应对未来的唯一办法。

> 在下一个阶段，我觉得微信更多的是围绕微信通过不同的APP尝试跟微信有某一种关联的其他一些服务形态

> **我们在思考问题或者是思考做什么的时候我们经常会问自己一个问题，就是我们在做这个事情的意义是什么？我们自己做每个功能、每个服务背后的意义，或者说一个梦想在里面到底是什么？**

> 微信的梦想是什么？刚才说过，**从个人角度成为人最好的一个工具朋友。从平台角度，建立一个市场，让创造者体现价值。**

作为产品设计师的成就感：

> 但是，我更觉得幸运的是，我可以在过程中，将自己对这个世界的认知，体现在产品中，并成为产品的价值观。

> “万物之中，希望至美。”