---
title: 学习shiny包
author: 王致远
date: '2019-04-23'
slug: learn-shiny
categories:
  - R语言
tags:
  - 学习总结
---

# Get Start

Shiny包有11个内置demo。

```{r eval=FALSE}
library(shiny)
runExample("01_hello")
```

每一个Shiny APP包含三个部分：

- UI，控制显示外观
- server function，运算
- shinyApp function，构造APP



```{r eval=FALSE}
library(shiny)

# Define UI for app that draws a histogram ----
ui <- fluidPage(

  # App title ----
  titlePanel("Hello Shiny!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Histogram ----
      plotOutput(outputId = "distPlot")

    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {

  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({

    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")

    })

}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

一个Shiny APP的结构如下

```{r eval=FALSE}
library(shiny)

# See above for the definitions of ui and server
ui <- ...

server <- ...

shinyApp(ui = ui, server = server)
```

当运行APP时，R session忙着监听APP，所以不会有其他响应。

建议每一个APP都在一个单独的project/directory里，例如如果目录叫my_app，那么可以这样运行它。runApp的第一个参数是路径名，所以必须要在当前工作路径下。

```{r eval=FALSE}
library(shiny)
runApp("my_app")
```

如果需要将APP代码也显示出来，那么运行

```{r eval=FALSE}
runApp("App-1", display.mode = "showcase")
```

也可以点击Script工具栏上的Run APP，可以选择在Window、Viewer Pane或者浏览器中运行APP。


