---
title: 博客重新部署解决方案
author: 王致远
date: '2019-04-25'
slug: netlify-fault
categories:
  - 博客
tags:
  - 解决方案
---

前两天格式化电脑后，原来的Rstudio和各类设置都没有了，需要重新设置，本篇博客记录下收拾的顺序，以便下次参考。

1. 下载并安装好R/Rstudio/Git。
2. 设置Git
    1. git config --global user.name "YOUR FULL NAME"
    2. git config --global user.email "YOUR EMAIL ADDRESS"
3. 生成SSH
    1. 检查是否已有SSH：file.exists("~/.ssh/id_rsa.pub")
    2. 使用Rstudio创建密钥，在Git面板，点击“Rreate RSA Key”
    3. 点击"View public key"找到公钥
    4. 将SSH公钥上传到Github
4. 将博客等package克隆到本地
5. 安装hugo
    1. 尝试devtools::install_hugo()
    2. 如果第一步连接不上，那么从github下载好[hugo](https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Windows-64bit.zip)
    3. 将hugo解压在D盘根目录下
    4. 安装Hugo blogdown:::install_hugo_bin("d:/hugo.exe")
6. 尝试修改并上传，理论上来说，设置好了SSH就不需要再在push时不需要输入用户名和密码了，证明连接成功

之后又遇到了Netlify部署网站出错的问题，具体表现在：

1. 在Rstudio里可以serve site，并且在viewer里没问题；
2. 已经生成了html等文件，并且已经push；
3. Github里也有这次commit的内容；
4. 但网站停留在上次更新的状态，没有这次更新的内容；

解决方案：

1. 登录[netlify](https://www.netlify.com/)，选择通过Github登录；
2. 选择到博客的项目里去；
3. 选择Deploys；
4. 找到上一次Deploy failed，点击Retry deploy，稍等片刻即可；

另外，本博客的[原始域名](https://condescending-mclean-f3cc47.netlify.com/)，等wzyblog.top过期后，可以继续使用原始域名或为域名续费，视未来使用情况而定。
