---
title: 游江南（毕业旅行）
author: 王致远
date: '2019-07-05'
slug: travel-of-jiangnan
categories:
  - 旅游
tags:
  - 旅游
---

> 这不是一次单纯的旅行。  
而是我给自己出的一道题目。  
未来的路我得一人走，  
能否依靠智慧做出判断，  
依靠毅力坚持到底，  
能否在完成目标的过程中，  
欣赏美丽，体会快乐，同时保持体面。  
我将用这道题试试自己。

6月11日去了故宫，18和19日去了山海关&北戴河，22日去了世园会，和晓程、王琦都见了面，毕业清单上的待完成事情几乎全部做完了，但是我还有一桩心愿未了——去长三角地区看看。说来也是很奇怪，从18岁到25岁已经七年了，我竟然从未去过东南地区，也是全国最富裕的地方。而想到工作后就算再去，更多都是出差性质了，几乎再不可能有这样整段的时间好好地畅游江南了。所以我下定决心，一定要在毕业后和入职前的这个时间段去江南地区玩玩。

6月23日周日，中午和王琦在凯德茂上面的探鱼吃烤鱼，其他时间在收拾行李和看书，策划这次江南游，准备离校后直接去旅行，旅行完再回家，再去成都报到。这样我需要把旅行不带的，又不扔的东西通通邮寄回家。所以要提前计划好旅行要带什么东西，考虑路上的洗漱、换衣。因为没有小尺寸旅行箱，所以我在转移城市时候只能手拎一个布袋子，所以必须要带够衣物，又不能带多以减轻负担。初步的路线安排是：南京-苏州-上海-杭州，从25号开始每个城市玩2天，7月3日早上从杭州回兰州。因为豪杰陪慧慧去杭州租房子，有可能和他俩在杭州汇合。

6月24日周一，早上把之前没邮走的行李又打包了两个箱子，不要的东西都扔掉了，但是迟迟不能封箱，因为导师没有在离校系统中确认签字。中午和豪杰又去吃了金谷园，点了西红柿鸡蛋水饺2两，香辣牛肉锅贴2两，猪肉大葱水饺2两，还有一瓶梨汁，非常清凉爽口。这也是和豪杰最后一次在金谷园吃饺子了。下午回来后焦急地等待导师签字。文秀师姐在和他沟通，一直在说等等，不知道在等什么？等到4:30终于在系统中确认了。我飞快地跑下楼，办理了退宿，去学苑食堂下面机器注销了一卡通，跑到八教学院办公室领到了毕业证书。终于，终于，终于，在5:00，最后一个证拿到了手！然后赶紧回宿舍把包含所有材料的文件袋放入箱子，打包封箱，邮寄回兰州。晚饭时候去了金谷园，还了中午忘记付的账。回来后买去南京的车票，订南京宾馆，计划南京的行程。

在衣物方面，我带了5件主力短袖T恤，准备每两天换一次（火车上的两天也算，所以一共10天）。带了5双袜子，准备轮番换洗。带了一件长袖衬衣，准备坐高铁时空调太冷穿。带了一件夹克衫，以防遇到极端冷的天气。带了一件长袖T恤作为预备队。因为去的都是大城市，可以随时补充衣服，所以足足够了。带了一套睡觉用的短袖短裤。

在药品方面，带了一包创可贴，用来贴脚伤的，实际上起了大用；带了3支藿香正气水，为了预防中暑、胃肠型感冒和风热感冒的，有备无患。（如果有行李箱，还会带一瓶黄连素，预防肠胃炎。）

在洗漱用品方面，带了洗脸毛巾、擦脚毛巾，带了剃须刀（但没有带充电头，在旅行前充好了电，把充电头邮寄回家），买了旅行瓶，灌装了学校里没用完的洗发露和浴液（这样就不用宾馆的了），洗面奶挤到了圆形小盒子里，这样能每天保持脸上的干净清洁。当然还有牙膏、牙刷、梳子。即使一个人，也不能玩的邋里邋遢的。

在电子产品方面，没有带平板（邮寄回家），带了kindle，和16000毫安移动电源。旅途中主要通过看书打发无聊。

最后事实证明，我带的大多数东西都起到了重要作用。虽然有计划之外的事情发生，总体风险都在我的控制之内。

### DAY 1：鸡鸣寺-明城墙-玄武湖-老门东-夫子庙

6月25日周二，旅行正式开始了。前一天晚上睡得不是很踏实，因为6:30就要起床洗漱，8:30的G165次列车。豪杰也早早起来，他是十点多和慧慧出发，到杭州下，所以大可不必起这么早的，不过坚持要送我。晓静师妹也说要送我到车站，不过稍微晚了一点，她看到公交车来了让我先走，我也就走了，没能见到，不过心意领了。离开了北京了，没有后悔，还是有点不舍。在火车上我先迷糊了会儿，然后在看书。旁边坐的是个四五十岁的中年阿姨，无意中瞅到她似乎是在看很厚一本中医的书，就聊了聊，原来她也不是中医，工作是财务方面的，只不过一直对中医感兴趣。她还说报过很多中医学习班，包括徐文兵的厚朴中医学堂，但是学费又贵又没学到什么。她还帮我诊脉，让我多运动，情绪放开朗，给我推荐了个成都锦江中医大附属诊所的年轻大夫叫李爽，说水平挺高。感觉她也是比较善良的。

到了南京站，坐地铁3号线到我住的常府路地铁站。地铁上我好奇地观察车厢里的乘客，想发现南京人都有什么特点，就是觉得女生似乎五官更加柔和，打扮更加温婉，扎马尾穿浅色裙子的居多。办理了住宿，下来午饭吃了小杨生煎，吃了个小杨、大虾、荠菜的三拼生煎，每样2个，外加鸭血粉丝汤，给我送了好几张满减劵。吃饱喝足后，就正式开始游玩南京啦。

第一站当然先去心心念念的玄武湖。第一次听说这个湖还是我爸说的，当年他们学校（曾经的南京铁道医学院，现在的东南大学医学部）就是在玄武湖边上，当年他也经常绕玄武湖散步跑步。听“玄武湖”这个名字就觉得又美又有一定神秘感，因为“玄”本意是黑，黑就神秘，“玄之又玄，众妙之门”更是神秘。“武”让我想到“雄姿英发，羽扇纶巾”的周瑜那样的英武之气。所以“玄武”二字给我的感觉就是在泼墨山水中拿着羽扇指挥千军万马的感觉。

不过去玄武湖的路上会路过鸡鸣寺，既然路过就不能错过。一进寺院就觉出，其氛围不是普通很俗的烧香拜佛的寺庙，有一种清凉安静之感，和成都的文殊院有异曲同工之妙。在入口处赠送了三支清香，然后指引香台在前方，顺着指引牌一路往上走竟然越登越高，指引牌上始终说香台在前面却不肯说还有多远，直到那座小山的山顶平台，有种小小的被“骗”了的感觉。这里也体现了南方人细腻的心思——既要设置困难，让人登高再燃香拜佛，方知虔诚之重要；又要设置目标，不断激励，鼓励人一路向上。不过因为达成目标心切，很多路过的殿堂都没有进去看，所以我从另一条路下来后重新再登一次。这次才知道，原来鸡鸣寺在二十世纪的主持是个女的比丘尼叫宗诚法师，鸡鸣寺成为尼众道场。我就说为什么从售票窗口到念经的女尼女居士，全都是女性，甚至游客都以女生居多。鸡鸣寺最高的塔叫药师塔，据说92版《新白娘子传奇》中因雷峰塔还没修好，就借药师塔拍的。据说绕塔三周可以消除污浊，我也便如此做了。我在想，为什么很多宗教和哲学的，都在强调重复性动作？我想是人思想的和行为的惯性是很大的，俗话说“三岁看小，七岁看老”、“江山易改，本性难移”，能真正影响一个人、改变一个人是很难的，唯有通过重复性动作，不断加强意识，加强记忆，才能实现改变人思想和行为的目的。重复性动作就是在强化意识的过程。

从鸡鸣寺的后山下山过了解放门就是明城墙的台城段，买了30元的门票登上去一看究竟。之前我已经看过很多的城墙了，有八达岭的坚固（毕竟能承载那么多游客是吧）、慕田峪的壮观、故宫的肃穆、嘉峪关的雄浑、山海关的奇特，南京城墙给我的感觉是“厚重”。用来粘连墙砖的粘合剂成分到现在仍是未知之谜，可是整个城墙却像建造之初那样坚实稳固，青色的墙砖之间的白色“胶水”让城墙呈现黑-白-灰的斑驳颜色，加上敦实的砖块，不仅是材料的厚重感，也让我体会到了历史的厚重感。从大明王朝到太平天国再到国民政府，南京和南京城墙一次次被给予厚望，最终免不了一声遗憾的叹气。但叹息后的南京和南京城墙并不消沉，抖擞抖索精神，还是努力活成自己喜欢的模样，自信而坚定地立在这里。从明城墙上向鸡鸣寺看去，可以看到最高的紫峰大厦矗立在鸡鸣寺身后，古典与现代同框，表达着南京保留古典文化的同时在新时代也要奋发有为的精神气。

顺着明城墙顺时针走，往右手边看便是玄武湖。湖边绿树成荫，空气清新，湖光鸟影。吹着风，赏湖景，心情宁静又惬意，安心又放松。城墙上遇到一个很有青春气息的中老年阿姨，让我给她拍照，她摆的POSE自信又优雅，如舞蹈家一般。我给她拍了张竖副的之后，我似乎想试试她的审美如何，拍横幅的把她放到构图中央拍了张，故意问她怎么样，她果然说，如果能在旁边一点会更好，那我自然就4:6比构图了。她很有可能是搞艺术的，审美敏感，语气和姿态优雅、客气、大方。后来聊天才知道，她已经当奶奶了，刚从北京过来带孩子的。这更加坚定了我的判断。后来她坚持要给我拍几张，说看我也是不会常来的。我坦诚的说在北京上学，这是第一次来南京，对这座城市印象很好。这也算是南京之行的奇遇了，虽然她和南京人可能关系不大，但对南京的好感更多了。

沿着城墙走到了玄武门，终于找到下城墙的口，其实早就想更距离地感受玄武湖了。玄武湖有五个湖心岛，分别是菱洲、樱洲、环洲、梁洲、翠洲，其中环洲环抱着樱洲。走到环洲和樱洲之间的水塘上，荷花开得很盛，荷叶和荷花都比北方的更大，亭亭玉立，阳光下透出荷花剔透的质感和荷叶的纹路，清新大方，又有谁能说这里的红配绿会俗？让我觉得有趣的是，小孩子们都在放一种特殊的“风筝”——用细线牵着的小鸟玩具，和风筝不同的是，小鸟会在空中扑翅膀，并且放的高度比风筝低，感觉比风筝更有趣一些。看着小朋友们在荷塘边玩耍，我突然很羡慕他们，羡慕他们的童年可以在这么美的地方愉快地度过，我在想我的孩子也可以这样吗？之后走到梁洲，走到翠洲，我一边看美景，一边想这个问题，甚至在查中铁二院有没有南京分院。不知未来有没有机会能哪怕短时期的居住在这里。走到湖东边的翠洲门我就坐地铁往回走了。

豪杰之前给我推荐了老门东，说那里吃的不错。于是我直接坐到了夫子庙的下一站，步行去了老门东。那里竟然是徽派建筑。之前我一直以为徽派建筑只在安徽歙县那里有，没想到在江南这边这么普及。不过只是形似，内容已是商业化的餐馆和文创小店，也就没有灵韵了。在老门东吃了晚饭，喝了特色的冰杨梅汁，走在小巷里，小巷很像我读完江南的文字后幻想的江南的样子。误打误闯地到了先锋书店老门东分店，里面是文艺有余，底蕴不足，装修很古典，但选书较粗，有种刻意小众、刻意文艺的感觉。我更喜欢北京的三联书店和万圣书园。

出了老门东，我本来想找个地铁站回去，因为已经挺累了。没想到误打误闯又到了夫子庙，得，既来之则玩之，又逛了秦淮河夫子庙，吃了鸭肠，觉得不错。当时天还没完全黑，华灯还没完全点亮，但也是很好看了。只是游人如织，没有独享美景的欣喜感，多了些热闹的氛围。终于从夫子庙坐上了回常府路的地铁，其实就一站路，但也累的走不动了。之前还没有走得这么累过，然而这才是第一天。

### DAY 2：灵谷圣境-中山陵-音乐台-明孝陵-美龄宫-十朝历史文化园-新街口-夫子庙

现在回想起来，这次旅行的第二天是令我印象深刻的一天。前一天晚上我在携程上订了灵谷景区-音乐台-明孝陵-美龄宫的联票90元，预约了中山陵的免费参观。没有看攻略，也没有问豪杰，只是从地图上景点的远近制定了由远及近的游玩路线：灵谷-中山陵-音乐台-明孝陵-美龄宫，事实证明，我的这个路线规划是再正确不过的。

一大早天灰蒙蒙的，下着小雨，我坐公交车先到了灵谷景区。真正进景区之前有一片中等大小的湖，湖上的莲花画出了一道优美的曲线，我当然选择最佳的构图把它记录了下来。到了有两座石狮镇守的“灵谷圣境”入口，雨越下越大，已有中雨大小，游客非常少。我独享着这片郁郁葱葱的幽静，深深呼吸着树和草的味道，心想这景色不愧为“圣境”之称，虽然隐隐地有种阴凉之气，但被这种幽深隐晦的美感深深地吸引。穿过“灵谷圣境”大门来到一个牌坊处，别处的牌坊以三门居多，这处牌坊居然有五门，每个门上都有圆形的国民党的青天白日旗，正中门的旗下有“大仁大義”四个大字，两旁是四朵梅花，真是非比寻常！牌坊下有一群可能是学美术的年轻人在画图，记录这难以用言语描述的美。从牌坊再往里走，看到一座外观很大气的大殿，名叫“无梁殿”，下面写的是“辛亥革命蜡像馆”，进去后挂在殿正中的是巨型的“国民革命烈士之灵位”，整个无梁殿像个巨型的棺材，像是在表达着“就算如此巨大的棺材都装不下牺牲的革命烈士”的意思。我看了震惊得头皮发麻，过了这么多天回想起来，头皮依然发麻，直击我心灵。

绕过无梁殿往里走是一片大草坪，草坪上有一棵大树叫“金陵桂花王”。我看地图发现灵谷景区的东边的几个景点还没去过，于是从东边的路迂回过去，到了灵谷寺。和鸡鸣寺都是女僧人不同，灵谷寺都是男僧人在念经，其中有些戴着眼镜的年轻人，和我岁数相仿，跟随着木鱼的节奏在快速念经，不知是什么机缘让他们这么早出家。灵谷寺里面一处建筑叫藏经楼，门外有两座通体洁白的菩萨石刻雕像，那座院子古朴静谧，令人身心宁静。外边有座院落叫玄奘院，大概是纪念玄奘法师的，不过是2005年后修的。

从灵谷寺右手边（东边）的路走，路中间有一座“灵谷深松”的大碑，当时下着雨，路上人很少，那条路通往密林深处，非常幽深。往前走到了琵琶街，传说在琵琶街上行走山谷有回声，在此拍掌犹如奏弦之音。当时雨水敲击在地面，发出的声音经过山谷的传播正和琵琶声相像，我倒认为名字应该取自这里。再往前走的右手边是谭延闿之墓，我对此人也不甚了解，看那里也有点阴寒，就没有过去。

往左手边走绕过一间房子的后面，就到了灵谷塔。之前我总觉得“灵谷”这名字和“魂魄”与“骸骨”有关，应有“灵骨”的隐含意思，看了灵谷塔的介绍。果然灵谷塔原为国民革命军阵亡将士纪念塔。走到塔下，发现这座塔是可以上去的。这座塔有九层，60米之高。我之前从未爬过这么高的塔。每爬一层我都在该层外边的回廊上绕一周看景色，直到最高的第九层，塔北边的钟山隐藏在水汽云雾之中，不知有多高，塔的南边可以俯瞰灵谷景区，其中轴的湖-牌坊-殿-草坪-塔的构造是陵墓的样子。我顿时懂了：整个灵谷景区是国民党用来纪念阵亡将士的地方，我就说为什么一进来就有种幽深、阴凉、静谧、肃穆的氛围。下了灵谷塔，灵谷景区转的差不多了，从靠西边的小路从出口出去了。

由于我预约的中山陵门票是10:30-12:30进场的，当时已经10:30，还有可能要排队，所以我就坐了10元的观光车，没有再走过去，结果发现路比我想象的短得多，而且都是绿道，非常适合步行，所以决定后面去其他景区走绿道就可以了。中山陵给我的震撼没有灵谷景区那么大，可能和游客太多也有关系。一开始是“博爱”牌坊，也是三门的，看来国民党认为，哪怕是国父都比不上阵亡将士。“博爱”牌坊往里走是“天下为公”门，过了大门就是三层台阶，上了台阶就是祭堂，祭堂里面是孙中山的棺椁，也不知孙中山遗体是不是真的在里面。

出了中山陵，吃了午饭（冰激凌+鸡翅，很久没吃过冰激凌了）就去了音乐台。原来音乐台是玩鸽子的地方，有很多白的、灰的、紫的鸽子。游客主要是家长带着小孩子过来喂鸽子。音乐台的中央用音箱播放着音乐。感觉也是轻松而美好的。很羡慕南京的小朋友们。

出了音乐台又吃了些午饭，就从绿道步行去明孝陵了。明孝陵是朱元璋和马皇后的陵寝。由于我是从北门进来的，进去后直接就是金水桥，所以先去主体建筑部分，再去神道。主体建筑部分由外向里先是文武方门，文物方门有五孔门，中间的门是墓主人（朱元璋、马皇后）进（没有出）的，王公子孙从左右两边的门进出，最旁边的左右偏门才是文武大臣进出的，体现了严密的等级制度。但现在就算是中间的门也被游客们随意穿越了。进了文物方门前面是碑殿，有一座康熙题的“治隆唐宋”的大碑，是在称赞朱元璋的功绩堪比唐宗宋祖。但这话怎么听起来这么耳熟呢？

> 秦皇汉武，略输文采。唐宗宋祖，稍逊风骚。一代天骄成吉思汗，只识弯弓射大雕。俱往矣，数风流人物，还看今朝。

感觉当时的康熙表达的也是这个意思——表面上夸赞朱元璋，来笼络中原汉族知识分子的民心，实际表达的是“还看今朝”。再往前走是享殿，享殿已经毁于战火了，现在只有三层汉白玉的基座，曾经是规模宏大的建筑，现在只在基座上改了个小小的店，里面卖些文创商品。由于实在是很喜欢南京，所以买了套南京的明信片，包括了南京的十大景点。再往里走是方城，修的有些像故宫的午门，上面是端楼，再往后就是宝顶，是朱元璋和马皇后的合葬墓，肯定是不让游客们去的。后来在明孝陵博物馆里知道，整个明孝陵的造型和故宫造型是反过来的，故宫由南到北是先大后小，明孝陵由南到北是先小后大。考虑到故宫是朱元璋的儿子朱棣在定都北京后修的，所以其中的隐藏含义耐人寻味。

话说朱元璋对马皇后的感情真的是非常真诚专一，马皇后是朱元璋的原配结发妻子，在朱元璋才是个小喽啰时就跟了他，和他一起共患难。都说现在的感情是“同甘难以共苦，共苦难以同甘”。但朱元璋和马皇后是真的“同甘共苦”了，朱对于马一直尊重和感激，认真听取她的建议；马皇后也保持节俭朴实的生活作风。朱一心扑在治国理政的事业上，马做他稳定的大后方。马皇后逝世后，朱元璋非常伤心，从此再没有立过一个皇后。朱元璋在得到了天下后，仍然对糟糠之妻始终如一，不忘初心，心思全部在统治和治理上，真的可以算是好的领袖了。相比现在有点权力就换妻纳妾，搞婚外恋包二房，搞权色交易的领导，真的不知道高到哪里去了。

出了主体建筑往南走就走到了神道。明孝陵的神道堪称独特，除了翁仲路的两对文臣武将的石像外，还有石像路的神兽，分别是狮、獬豸、骆驼、象、麒麟、马，每种神兽都有站姿和卧姿两种姿态，所以6种动物一共有12对。介绍牌上写着：

> 这些石兽采用圆雕技法刻成，线条流畅圆润，气魄宏大，风格粗犷，既标识着帝陵的崇高、圣洁、华美，也起着保卫、辟邪、礼仪的象征作用。

按照现在的话来说，这些神兽都雕刻的“萌萌哒”，很圆，很憨的样子。每只神兽的嘴角上扬，都像是在微笑，十分亲切可爱。六种动物中，只有獬豸是传说中的神兽。

> 头生一角，如遇二人相争，必以其角触不正之人。把它放在陵前，取“正直不阿”之意。

出了明孝陵，步行去美龄宫距离很近。原来的印象里，宋美龄只是被蒋介石宠爱的“花瓶”，再没有其他印象。但美龄宫的展馆一开始就是地下室的宋美龄画展，其绘画技术堪称大师级，真的超出了原来的认识。后来看对她的介绍，称赞她是“集美貌、才华、权力、财富于一身的女子”，真是很高的评价了。挂在大厅的她的肖像照也是端庄、优雅、大气的，感觉是有很深底蕴的。其实想想也是，蒋介石何许人也？一代枭雄！天下“花瓶”多了去了，为何独对宋美龄如此溺爱迷恋？其身上一定有独特的特质。所以，**不要轻易对不熟悉的人贴标签，下定义。人是复杂的。**这是我所学到的。美龄宫里还让我印象深刻的是建筑和装修风格。美龄宫是由留学归来的建筑学子设计的，所以既有西式建筑的富丽堂皇，也有中式建筑的中庸典雅。装修风格也不是极尽奢华的，而是在朴素中透露出典雅的艺术审美，是一种隐晦克制的奢华。后面参观总统府也是这种体会。这种装修风格也是很有特点的。

出了美龄宫去了“南京十朝历史文化园”，讲道理修的还是不错的，只是我玩得实在是太累了，已经细细看不懂了，就走马观花地看了一遍。南京曾经是东吴-东晋-南朝（宋齐梁陈）-南唐-明-太平天国-中华民国的首都。除了明朝搬到北京去了，其他怎么感觉都是短命的朝代？令我印象深刻的是南京的文化氛围很好。博物馆的下面是个图书阅览室，里面的图书都是捐赠的。买点饮品就能在那里一直看书。真是个有浓郁知识氛围的城市。

从文化园延绿道走到苜蓿园地铁站，心想还没有去过南京最繁华的商圈新街口，于是去那里看看。最令我吃惊的是，新街口地铁站有24个出口，像个环形的迷宫一样，很难找到要出去的出口。商圈的繁华程度还可以，类似于春熙路。我在美食城吃了个海鲜面，价格也不算贵。最后从新街口步行到常府路，路上还买了个青团试试。第一次吃青团，是豆沙馅儿的，非常好吃。

到此第二日计划中的旅行基本就结束了。刚回到宾馆准备好好休息，王涌龙（研究生同学，南京城交院工作）说到南京了，过来找我。等他在小杨生煎吃了晚饭后，一起又去了秦淮河-夫子庙。这次去比昨天天色更晚了些，华灯更多了，也更好看了。只是这一天实在是太累了，走了34000多步。十点回到宾馆本想好好休息，没想到隔壁住进来一对夫妇，一直在看恐怖片，声音极大。12点时我向前台提出了抗议。他们声音小了些，但还是很吵。最后虽然睡着了，但睡得很不好，导致第三天身体很虚，精神萎靡。但总体来说，对旅行的第二天还是非常满意的。

### DAY3：总统府-南京博物院-苏州观前街

原本的计划是每个城市各玩两天，但实在很喜欢南京，而且觉得不去打卡总统府和南京博物院有点可惜，所以变更计划，第三天继续在南京玩，晚上坐火车到苏州。将上海的时间压缩到一天。

由于前一天很累很累，而且晚上被吵得没休息好，所以第三天很疲倦。而且由于第二天走得太多，脚已经开始出水泡了。但这才第三天，我怎么可能认输？于是用创可贴给水泡的地方打上补丁，坚持出发。

一大早先去了总统府，游客很多。原来南京总统府最早是两江总督的衙门，后来被太平天国选作天王王府，最后才被国民党政府选作政府所在地。孙中山就是在这里宣誓就职中华民国临时大总统的。一直以为，两江总督指的是现在的江苏和浙江，实际上是江南省（江苏、安徽、上海）和江西省。两江总督是清朝最高的封疆大吏之一，从一品官秩，我们所熟悉的林则徐、曾国藩、左宗棠、李鸿章都当过两江总督。

总统府里最令我印象深刻的有三点。一是低调、克制、朴素、冷静、典雅的房间装修风格。二是园林古朴精致，吸纳了苏州园林的设计理念，精致程度甚至超过了故宫里的御花园（有点讽刺）。三是虽然叫总统府，但不是总统一人办公的地方，而是整个当时中央政府的所在地，包括行政院等重要机构都在总统府里。

本以为10点能逛完总统府，没想到一直逛到中午才出来。吃了午饭后就去了号称中国三大博物院之一的南京博物院。由于打太阳晒着，天气太热，外加身体太疲倦，实在是没能很精细的参观博物院，只是走马观花看个大概。总体感觉是，藏品数量很大，但不像国家博物馆和首都博物馆那么多精品，特别是我最喜爱的瓷器没有太多喜欢的展品。地下有个叫“民国馆”的很有意思，布置的像是拍民国电视剧的片场，天花板上是夜空，走在“街道上”有种穿越了的感觉。“民国馆”的尽头是大茶馆，好像是“非遗馆”。如果时间充裕，真想坐在那儿喝茶听戏。“数字馆”虽然布置用心，但感觉比不上北京世园会在植物馆和中国馆的光影效果。

逛完南京博物院，我实在是太累了，就坐G7371，16:04出发，17:22到苏州，找到了我要住的宾馆。落定之后，想出来找点吃的，结果误打误闯去了苏州较有名的一条古风商街叫观前街，因为它在玄妙观的前面。不过我对这条街印象一般，还不如成都的锦里。找了家传说中的老字号——朱鸿兴面馆吃了碗卤肉面，感觉也就那样，远不如北方面食。回到宾馆，在考虑怎么玩苏州。因为之前时间仓促没有做攻略，外加自己走路找地方实在太累，脚痛的也走怕了，在携程上发现了225元逛拙政园-狮子林-寒山寺-虎丘-山塘古镇的旅游团，加了下几个景点的门票钱好像超过225了，于是决定第四天跟团去玩。

### DAY4：拙政园-狮子林-寒山寺-虎丘-山塘古镇

### DAY5：平江路-可园-沧浪亭-上海外滩-南京路

### DAY6: 上海观光大巴1号线-3号线-外滩观光隧道-杭州与豪杰慧慧汇合

### DAY7：断桥-白堤-平湖秋月-苏堤-花港观鱼-牡丹亭-飞来峰&灵隐寺-苏堤南-长桥-学士公园-柳浪闻莺公园-俶影桥-龙翔桥

### DAY8：西里湖-郭庄-茅家埠-太子湾公园
