---
title: 游山海关-北戴河
author: 王致远
date: '2019-06-20'
slug: shanhaiguan-beidaihe
categories:
  - 旅行
tags:
  - 旅游
---

之前早打算在毕业这段时间去秦皇岛玩，但因为导师安排的编书任务和自己的拖延一直没抽时间去。眼看着距离离开北京越来越近了，列了个未完成事情清单，其中就包括去秦皇岛玩，总算把这件事提上了日程安排。

17号早上，发现会有两天空闲时间，果断决定18~19号去，就着手订车票和宾馆。发现秦皇岛市区景点不多，主要集中在北端的山海关和南端的北戴河。而且18号早上从北京南到秦皇岛没有票，到山海关有票，那正好买到山海关的。计划是第一天先在山海关玩，晚上之前坐从山海关到北戴河的火车，赶到北戴河住下，第二天玩北戴河，从北戴河回北京南。

18日早上6:30起床，6:50洗漱完毕，7:10吃完早饭，坐地铁去北京南站，到车站时8:10，正好检票，时间把握的还挺好的。在火车上开始看《边城》这本书。10:30到了山海关站，因为高铁的站台最靠北，所以没多想就从北出口出来了（这个北出口后来坑了我一下）。

出了火车站就坐上了25路，直奔老龙头景区。如果说山海关是万里长城的最东起点，那老龙头又是山海关的最东起点。明朝初年，一代名将徐达在山海关修长城，后来明朝中后期的戚继光等继续完善加固，形成了东有入海老龙头，西上角山的一套完备的军事体系，有效阻碍了从北方而来的游牧民族，对敌人形成了从心理到战术上的压迫。在北京我也去过八达岭、慕田峪两处长城，也去过最西端的嘉峪关长城，但像老龙头伸入海中的我是第一次见，估计也就仅此一处了。老龙头的基础门票50元。站在长城的最东端起点，吹着微咸的海风，心中顿生一股豪情。距离上一次看海已经整整7年了，所以很兴奋地拍着海。之后下到老龙头下面的沙滩上，在海边找了块稍平的石头坐下，观察涨潮。我发现，涨潮并不是后一浪一定比前一浪高，但整体的趋势是越来越高的，或许稍不留神，突然有一浪变得格外高，就会打湿鞋子衣服。之后顺着沙滩走到了同样伸入海中的海神庙，其中供奉有妈祖，她是中国乃至整个东亚和东南亚共同信奉的女海神，传说她只是个普通女孩，救过很多落水的人，但英年早逝了，为后来的人所纪念。在老龙头景区的出口处有一家纪念品店，规模挺大，但卷闸门半关着，我因为好奇所以钻了进去，里面有店员在闲谈，摆放了很多贝壳、珊瑚制成的小工艺品，非常好看，而且不是很贵，要不是碍于不好拿就买回去一个了。

出了老龙头，原坐25路到了山海关城楼。刚进景区南门，我看到右手边有爬城墙的，直接就买票上城墙了，实际上再往前走才能到景区正门，不过这样也好，就不用走回头路了。当时正值中午，城墙上的日头暴晒，我带着帽子，觉得胳膊和脖子上的皮肤发烫，也无树荫可躲，打开雨伞发现一点都不遮阳，只能顶着日头往前走。往前走到“天下第一关”的主城楼，十分壮观。城楼里摆着“天下第一关”的匾额，字体苍劲有力，匾额下是山海关的整个布防图，其规模之大和布局之细密令人惊叹，再往下是重82斤的青龙偃月刀，刀体之大令人惊叹，遥想当年能挥舞起这把刀的猛士，该是何等威风。下了城楼，在城楼门里，发现有个办“通关文牒”的摊子，办一个15元。虽然稍贵，但图个“通关”吉利的名头，也为留个纪念，就办了个，觉得很好玩。从城门往里走是瓮城，对敌人瓮中捉鳖的地方。我在中心的座椅上坐了一会儿，因为四周都是树，顿觉清凉了不少。但感觉树把我团团围起，我倒想被捉住的鳖，于是没坐一会儿就起来走了。城门右手边是兵部分司，相当于现在的军区一样，其装饰就有种军队的肃穆感。再往外走就是景区出口了。出了景区一直向西走，走到了位于城中心的钟鼓楼。一开始竟然没意识到那是钟鼓楼，走过了，后面才又折回去。因为去年母亲在此求过我找工作顺利，事实上过程也还算顺利，于是让我这次过来还愿。我轻轻敲了敲鼓和钟就下去了。之后步行到王家大院，里面说是民俗博物馆，但我觉得没什么意思，走马观花看了遍就出来了。再步行到长城博物馆。说来也是很巧，我到那里正好是3:55分，工作人员告诉我4:00就不让进了，让我赶紧领票，还算顺利地进去了。这个博物馆比王家大院好多了，还是免费的，真应该不去王家大院，在这里多看看。以后有时间要补一下《长城》这部纪录片。

看完出来后，我就去山海关车站坐车了，没等到公交车，步行走过去的。结果到了才知道，原来山海关站分为北广场和南广场，我早上出来的北广场之让出不让进，而南广场要绕很远才能到！真是坑煞我也！一看离火车时间很近了，就赶紧打车到南广场进站了。

到北戴河站时大概是6.00，等到了37路公交车，坐了将近1小时到了预定的宾馆，在刘庄北里那里。刘庄感觉是北戴河一个宾馆聚集区，很多宾馆和海鲜大排档。顺利找到了我在携程上66元订的宾馆，还算干净。晚上本打算继续看《边城》，闲来无事打开电视看了下，发现能看电影，看了之前想看的《怦然心动》，觉得电影很棒，具体见[另一篇博客](https://www.wzyblog.top/post/2019/06/20/flipped/)。晚上刚熄灯蚊子挺多，本来有点烦，后来就慢慢睡着了。早上醒来发现并没有给我咬包，大概是觉得我的血不香？又发现桌子上有没发现的电蚊香，其实应该点上蚊香的。

