---
title: 读《易经》（持续更新）
author: 王致远
date: '2019-05-16'
slug: read-yijing
categories:
  - 读书
tags:
  - 读书笔记
---

易之卦辞与爻辞含义十分灵活，从不同角度，不同层面，可以有不同理解，应仔细玩味，耐心探索。

# 经上

## 1. 乾卦

111111

> 乾，元亨利貞。  
> 初九，潛龍勿用。  
> 九二，見龍在田，利見大人。  
> 九三，君子終日乾乾，夕惕若，厲，无咎。  
> 九四，或躍在淵，无咎。  
> 九五，飛龍在天，利見大人。  
> 上九，亢龍有悔。  
> 用九，見群龍无首，吉。  
> 《彖》曰：大哉乾元，萬物資始，乃統天。雲行雨施，品物流形，大明終始，六位時成，時乘六龍以御天。乾道變化，各正性命，保合大和，乃利貞。首出庶物，萬國咸寧。  
> 《象》曰：天行健，君子以自強不息。潛龍勿用，陽在下也。見龍在田，德施普也。終日乾乾，反復道也。或躍在淵，進无咎也，飛龍在天，大人造也。亢龍有悔，盈不可久也。用九，天德不可為首也。

上乾下乾，也叫重天乾卦。天是阳气积聚而成，有纯阳之性。乾卦其象为天，其义为健，其德为元、亨、利、贞，六爻取龙为象，借潜、见、惕、跃、飞、亢，龙形之变，以明乾道变化之象。勉励人们效仿“天”之德，自强不息，顺天而行，相时而动。

元亨利贞：元始，亨通，和谐有利，正固持久。

天行健君子以自强不息：天道运行，周而复始，健而无息，君子应效法天道，自强不息。赞美阳刚之德，揭示了刚强者的进取哲学，勉励人们要效法天的刚健精神，奋发进取，自强不息。

初九：潜龙勿用，阳在下也，龙隐于渊，待时而兴，不宜有所作为。当自身修养尚未达到成熟的程度，隐伏而不显露，所以君子不能有所作为。君子通过学习来积累知识，通过诘疑来明辨是非，以远大作为内心的目标，以仁义作为履行的责任。

九二：龙出离潜隐状态，出现在大地上，到了发挥作用、有所作为的时候了。九二刚健得中，虽距成功尚远，但有了成功的素质，所以说有“大人”之象。

九三：君子整日里勤奋努力，直到夜里还忧惧警惕，虽陷危险之地，亦可以免于咎过。九三位置不上不下，功业尚未成就，变数很多，有志于胸的人要时时振奋精神，努力不懈，事事小心谨慎，夜晚也不能疏忽大意。只有这样严格要求自己，才不会发生过失。

九四：龙或腾跃而起，或退居于渊，审时度势，进退均不会有危害。此时龙还未飞腾，但跃跃欲试，已具有不可限量的潜在力量，但仍需待机而动，只要把握有利的时机进退，就不会发生过失与灾难。

九五：龙飞上天空。九五居上卦之中，得正又在君位，刚健中正，相比九二的“大人”，不仅是更高层次的有德有位者，而且能够游龙在天，兴云布雨，天下感受其利。

上九：龙升腾到极限，有所追悔。刚进过甚，盛极必衰，盈满是不可能长久的。当极盛之时，唯其有悔，才能穷则思变。

用久：群龙无首。以刚健为体，柔顺为用，刚健而能柔顺，获吉是必然的。

## 2. 坤卦

000000

上下皆坤，象征“地”柔顺宽厚。坤卦利于固守如牝马顺而健之正道。

> 坤：元亨，利牝马之贞。君子有攸往，先迷后得主。利西南得朋，东北丧朋，安贞吉。

君子有所远行时，争先向前会迷失正道，随后顺从而行才符合常理。君子观此卦象，取法于地，以深厚的德行来承担重大的责任。

乾德以统天为本，坤德以顺承天为前提；古乾刚坤柔，乾健坤顺。乾之四德无所限制，坤之四德限于牝马，后得主，安贞吉。

坤卦充分体现大地之美，女性之美，阴柔之美。坤代表大地，大地承载万物、化育万物，顺应天时，具有宽厚、包容、正直、宏大、安静的胸怀。很多成功人士缺的不是乾卦的精神，而是坤卦的精神。

> 初六：履霜，坚冰至。

踏着薄霜，可以推断坚厚的冰层快要结成了。这也是一种次序，循序渐进的现象，做事要先小后大，先薄后丰。

> 六二：直、方、大，不习，无不利。

平直、方正、辽阔，即使去陌生的地方，也没有不利。做人要正直、方正、大气、中和。

> 六三：含章，可贞。或从王事，无成有终。

蕴含美德而不是显露于外，这样可以坚持正道。如果辅佐君王的事业，不已成功自居，最后才会有结果。六三应当等待时机发挥作用。守坤道行辅佐之事，确实颇多艰难。含章，就是要把才华隐藏起来，要有忧患意识，含蓄、收敛。

在高位或凶险之时，不要显示自己，要顺从别人，这是一个转变，虽然不宜做到，但也要努力，不然会有凶险。能含晦藏美，慎行免咎，确实是过人智慧，终能成就功业。

> 六四：括囊，无咎无誉。

扎紧口袋，如缄口不言，没有指责，也没有赞誉。谨慎才没有祸害。

> 六五：黄裳，元吉。

经过了含蓄和隐藏，就是大吉大利。裳，表示要居下不争。

> 上六：龙战于野，其血玄黄。

坤卦是阴从阳发展的过程，阴发展到极盛，高亢到要和乾阳一争高低，势必两败俱伤，血流遍野。作为行坤阴之道的辅佐者，要居卑而静，当其事业和声誉发展到极盛之时，必须警惕与乾阳争斗的局面出现。

> 用六：利永贞。

阴柔之性中带有阳刚之质，这是有利于永守坤之正道的。乾卦用九是刚而能柔，坤卦用六是柔而能刚，刚柔并济含于其中，同时显示出阴阳转化的规律。

地道极为柔顺，但运动却是刚健的；极为娴静，品德是方正的。

天地交通变化，草木就茂盛，天地阻隔不通，贤人就隐退。

坤道代表宽厚、包容、安静的胸怀，需要我们循序渐进地修持，即所谓冰冻三尺非一日之寒。到达一定程度后不能忘记根本，即天地、阴阳和谐之道，避免不必要的争斗，获得幸福。
