---
title: 城际铁路站点综合交通衔接规划
author: ZhiYuan Wang
date: '2020-01-07'
slug: 城际铁路站点综合交通衔接规划
categories:
  - 交通
tags:
  - 读书笔记
---

# 8.1 交通衔接规划主要内容

## 功能定位及发展战略

根据城际铁路站点在城市总体规划和综合交通系统中的地位，确定城际铁路站点**在城市发展中的定位**，**在综合交通系统中的定位**以及**所在片区的地位**。根据城市社会经济发展目标与城市发展目标，制定城际铁路站点**发展目标与发展策略**。

## 综合交通场站布局

依据城际铁路站点功能定位，总体发展目标和发展战略，提出城际铁路站点**规划布局原则和要求**，合理**布局各种交通方式的位置**，打造高效、一体化的交通系统。

## 城际铁路车站交通组织

分析城际铁路**站内部各种交通方式车流、人流特征，确定交通组织流线，实现人车分流，减少交叉干扰**；对外完善城际铁路车站与城市其他组团及周边城镇、大型集散地等之间的交通衔接关系。体现“以人为本，以流为主”的核心要求，为旅客提供方便、舒适的乘车环境和快捷便利的“零换乘”或“最短时空换乘”条件。

# 8.2 交通衔接规划主要原则和理念

## 8.2.1 模式

城际线路与城市轨道交通、公共交通系统的衔接在规划设计时实现**“整体规划、分期实施、有机衔接”**，体现“零换乘、无缝衔接”等先进的规划理念。城际铁路主要承担中长距离的居民出行，**其站点作为城市交通枢纽，需建成各种交通方式一体化的交通系**统，通过良好的换乘体系，发挥最佳运输效能，扩大服务范围，提高网络整体效益。根据城际铁路站点功能定位及衔接的交通方式不同，其一体化衔接换乘模式主要分为**立体节点型衔接模式**和**平面网络化发展模式。**

立体衔接模式主要将其他交通功能及城市功能垂直叠加，多种功能分布在不同层面上，相互采用垂直联系，可使资源空间的集约化利用，充分发挥轨道交通促进地区高强度开发的能力。平面网络化发展模式基于TOD开发理论，围绕车站布置不同交通设施和城市功能，通过地面及地下步行廊道连接周边的交通场站和公共建筑，构成网络状的城市综合体，其范围将覆盖以车站为中心的500m的步行合理区。

## 8.2.2 原则

城际车站综合交通衔接规划，需要根据城市空间形态、旅客出行等特征，按照“零距离换乘”的要求，将城市轨道交通、地面公共交通、出租车、私人交通等设施与城际铁路车站紧密衔接，建立主要单体枢纽之间的快速直接连接，使各种运输方式有机衔接，这对城际铁路车站本身以及整个综合交通运输体系的运转效率都有积极作用，主要原则包括：

### 外部畅通、过境分离

外部交通畅通，打通枢纽与周边各城镇及城市组团之间的联系，减少过境交通的影响。结合城市整体规划布局，整体、宏观的进行考虑，通过合理的交通枢纽与周边各城镇及城市组团之间的交通线路设计，完善现有的交通流线，使枢纽与周边城镇及城市组团之间联系紧密，交通顺畅，不形成拥堵。同时，通过过境道路与城市外环路相衔接或者建设高架等方法，结合城市内部道路系统的完善，减少过境交通的影响。

### 立体布局、到发分层

结合目前综合客运枢纽向大型化、综合化、立体化和功能多元化的发展趋势，交通组织也逐渐由平面化转向立体化，根据目前国内在建和规划的综合客运枢纽分析，一般是按照高进低出的原则组织交通。同时为避免车流、人流的混行，实行到发分层。

### 单向循环、减少交叉

由于枢纽交通流量大，极易造成交通拥堵。单循环交通系统流线清晰，能够有效地减少冲突点，实现站区车流无交叉干扰，便于信号灯控制，优化车辆运行秩序，同时能有效利用路幅，增加交通容量，是解决交通拥堵问题最直接、有效、经济的方法。目前国外大型综合交通枢纽多采用此原则进行交通组织。

### 分块循环、快进快出

为保证外部交通流的快速集散和干扰最少，应尽量将各种车流分块循环实现车流的快进快出。此原则需要有效利用现有地形环境，优化组织交通，使各类车辆各行其道，形成高效快捷的交通流。

### 人车分流、安全便捷

综合客运枢纽交通组织的最终目标是实现人流的快速集散，但这是基于安全的前提下，为保障安全，应尽量减少冲突点，相应的也要求实行人车分流。人车分流原则不仅能为旅客提供一个安全、舒适的步行环境，充分体现了“以人为本”的设计理念，同时也有助于避免由于人车交叉带来的交通拥堵。

### 公交优先、以人为本

换乘公共交通的客流是枢纽内客流的主要组成部分，占总量的70%以上，因此，旅客的换乘也应以大容量的公共交通为主要运输工具。公交优先便于客流的快速集散和减少旅客在枢纽内的滞留时间，充分体现以人为本。

# 8.3 实证

## 8.3.1 城际铁路站点分类

在此，我们将包含城际客流的铁路客运站统一视为城际铁路客运枢纽，并参考《铁路旅客车站建筑设计规范》（GB50226-2016）中客运专线铁路旅客车站规模的相关规定（见表8.3.1-1），将城际铁路站点划分为两类：高峰小时旅客发送量大于5000人为大型城际铁路综合交通枢纽；高峰小时旅客发送量小于5000人为一般城际铁路站点。

高峰小时发送量PH（人）

- 特大型：PH>=10000
- 大型：5000<PH<1000
- 中型：1000<PH<5000
- 小型：PH<1000

从换乘流线和组织上来看，大型城际铁路综合交通枢纽由于规模庞大、功能复杂，“立体换乘”是其换乘模式的发展方向，旅客无需出站，通过立体换乘功能空间组织站内各功能要素和交通要素，实现各种交通工具之间的综合换乘。而一般城际铁路站点由于换乘体系的简化，旅客流线也相对单一，多为平面上的流线组织。

从车站功能性的差异来看，大型城际铁路综合交通枢纽不但要将铁路、地铁、轻轨公交等多种工具有机衔接、融为一体，更有甚者综合了交通、商业、服务业、办公、居住、娱乐等功能，以客运站为基础将整个站区发展成为城市的副中心。而其他中小客运站由于其客流量和规模有限，其功能上保证与其他交通设施的无缝连接即可。

## 8.3.2 大型城际铁路综合交通枢纽交通衔接

近年来，以交通为主导的枢纽已不能完全适应城市的需求，大型铁路客运站以高铁车站上加盖城市综合体开发、构建超级交通城为新发展方向，客运站设计也由此进入第四代车，重庆沙坪坝站、杭州西站、合肥西站等是其中的典范。第四代铁路客站具备以下四个主要特征：

### 交通一体化

第四代铁路客站更强调客运效率和旅客的体验，它是以铁路客站为中心（或中心之一）的，**综合了各种城市对内对外客运交通方式的一体化交通建筑。**无缝衔接、无风雨换乘、零手续中转是基本要求，旅客在其中能感受到明确、便捷、安全、舒适。客站如同各种交通聚集节点上的自动换乘机器，高效吞吐着客流。

### 站城一体化

第四代铁路客站是城市的有机组成部分。**它并不强调本身独立的站房形象，可以是模糊了铁路与城市的界限的城市综合体，也可以是站城融合的一体化综合开发项目。铁路客站是城市规划的前导、经济发展的引擎，也是整合容纳各种城市功能的容器。**

### 可持续发展

第四代铁路客站及所属设施必须安全、耐久，经济效益好，具有“自身造血”功能，它给所在区域及周边带来的是环境的改善，土地价值的升高。

### 智慧车站

第四代铁路客站利用先进的信息技术，以满足旅客出行需求为核心，优化整合服务资源，实现车站智慧式管理和运行。利用先进的智能技术解决信息精准、换乘便捷，以及安全、疏散、反恐等各种难题，让旅客轻松享受智能化出行新体验。

### 案例

1. 广州南站：典型的第三代大型铁路客运站。自下至上分为B1层（地铁站、停车场）、1F层（进出站层、购票层）、2F层（高架站台层、东落客平台）和3F层（高架候车层、西落客平台）共四层。
2. 上海虹桥综合交通枢纽：虹桥站分为地下一层（B1F到达层）、地上一层（1F站台层）、地上二层（2F出发层）和地上三层（3F商业层）。
3. 武汉站：典型的第三代大型铁路枢纽，它首创了“桥建合一”的站房形式，将铁路站场、旅客站房和交通广场三者完全立体叠合。铁路和站台以多排并联桥梁的形式架空，桥上建站房、桥下设换乘交通。
4. 深圳福田站：是中国第一座深埋于城市中心地下的城际铁路车站，它的设计理念介于第三代与第四代铁路客运站之间。地下一层是与城市轨道、公交等的客流转换层及售票层，地下二层为站厅层，主要为进出站大厅及车站设备和办公用房，地下三层为站台层。
5. 沙坪坝站：首例上盖城市综合体开发的第四代大型铁路客运枢纽。沙坪坝站深入地下八层，集铁路客运、城市轨道交通、城市地面交通系统为一体。
6. 杭州西站：为东西向高架站，站房最高处约52米，地上共5层，分别为：一层，高铁出站层和综合交通设施层（公交、大巴、出租车、社会车辆）；二层，6米快速出站和城市服务设施层；三层，高铁站台层；四层，高架候车厅和高架落客平台层；五层，空中花园连廊和候车室旅客服务层。而地下三层为城市轨道和停车设施。

## 8.3.3 一般城际铁路站点综合交通衔接

一般城际铁路车站更加注重配套规划公交、出租车及社会车辆停车场等，需要为城际铁路与道路交通间的客流交换预留好场地。

### 案例

1. 青盐线青岛西站
2. 徐宿准盐线宿迁站
3. 成蒲线大邑站：城市标志性窗口，利用TOD的开发理念，将车站周边打造为一个集交通，商业，办公，文化资源，整合当地旅游资源优势的综合性商业板块。
4. 渝万城际长寿北站
5. 海南东环线美兰机场站：是国内首个直通机场的高铁站。
6. 成灌铁路犀浦站