---
title: 交通指标汇总
author: 王致远
date: '2020-01-07'
slug: 交通指标汇总
categories:
  - 交通
tags:
  - 学习总结
output:
  blogdown::html_page:
    toc: true
---

# 0. 总

| 类别   | 建议指标                                                               | 备选指标                                                                                                                                                                                                                                                                     |
| -------- | -------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 交通需求 | 全市、关键区域或通道的：交通需求总量、交通出行结构 | 区域与对外交通、城市交通等各种交通方式的需求规模、结构、分布；每人或每车平均出行次数、出行距离。                                                                                                                                 |
| 交通供应 | 区域对外交通：可达性、运输能力                              | 港口泊位等级、数量、航线数量、客货运吞吐能力等；公路等级、长度、密度、通行能力等；机场航线数量、客货运吞吐能力等；铁路长度、线路数量、客货运吞吐能力等；口岸客货运运输能力等；            |
|          | 城市交通：可达性、交通承载能力                              | 城市道路等级、长度、密度、通行能力等；公交线网数量、场站规模、车辆数、专用道长度，公交站点半径覆盖率等；轨道网络规模、密度、站点数量、车辆数，轨道站点半径覆盖率、周边覆盖人口岗位数量等；步行非机动车通道长度、密度，公共自行车租赁点数量等；停车设施供应规模、结构、供需缺口； |
| 交通运行 | 基础指标：平均行程速度，服务水平/拥堵等级              | 交通流量、周转量、饱和度（负荷度）；平均延误；                                                                                                                                                                                                            |
|          | 特征指标：各方式出行时耗，拥堵持续时长，拥堵里程比例 | 路段或路网行程时间比；不同拥堵等级的持续时间、比例；常发拥堵路段数量、长度、里程比例；道路行程时间可靠度；                                                                                                                  |
|          | 综合指标：交通运行指数                                          | 道路拥堵指数；拥堵延时指数；                                                                                                                                                                                                                                       |
| 交通运营 | 区域对外交通：客货运发送量，平均运送速度               | 各种方式客货运发送量的比例                                                                                                                                                                                                                                          |
|          | 城市公共交通：全天或高峰客运量、交通分担率、平均运营车速、候车时间、准点率 | 公交平均换乘次数；公交、轨道交通车辆每平方米站立人数；公共交通平均步行到站距离；乘客满意度、投诉率；                                                                                                                           |

# 1. 点

## 1.1 对外交通客运枢纽

### 1.1.0 换乘距离与时间限制

枢纽内主要换乘交通方式出入口之间旅客步行距离不宜超过200m。

### 1.1.0 换乘用地

城市综合客运枢纽中对外交通集散规模超过5000人次/d，应规划对外客流集散与转换用地，用地面积应符合规定（P18）。

### 1.1.1 对外交通客运枢纽分级

| 分级 | 客运规模（人次/日） |
| ---- | ----------- |
| 一级 | >80000      |
| 二级 | 30000~80000 |
| 三级 | <30000      |

旅客日吞吐量小于0.2万人规模为客运站。

### 1.1.2 铁路客运站规模

| 分级 | 高峰小时旅客发送量 |
| ------ | ------------------ |
| 特大型 | >10000             |
| 大型 | 3000~10000         |
| 中小型 | 600~3000           |

### 1.1.3 铁路客站集疏运设施衔接要求

| 规划日均旅客发送量
（万人次） | 交通设施衔接要求                                                                                                                                                                                              |
| ----------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| >=5                           | 1. 宜设置公路客运站接驳;<br>2. 应设置城市轨道交通接驳；<br>3. 应与城市快速路或多条城市主干路衔接；<br>4. 应设置公交枢纽站、中途站接驳；<br>5. 应设置出租车上落客区，蓄车区；社会车上落客区，停车场；<br>6. 应设置非机动车停车场； |
| 1~5                           | 1. 宜设置公路客运站衔接；<br>2. 可设置城市轨道交通接驳；<br>3. 应与城市快速路或多条城市主干路衔接；<br>4. 应设置公交枢纽站、中途站接驳；<br>5. 应设置出租车上落客区，蓄车区，社会车上落客区，停车场；  6. 应设置非机动车停车场； |
| 0.5~1                         | 1. 应设置公交枢纽站接驳；<br>2. 应与一级公路或城市快速路、主干路衔接；<br>3. 应设置机动车、非机动车停车场；<br>4. 宜设置出租车上落客区，蓄车区，社会车上落客区；<br>5. 可根据需要设置公路客运站衔接；<br>6. 可设置轨道交通线路接驳； |
| <0.5                          | 1. 应设置公交站点接驳；<br>2. 应设置机动车、非机动车停车场；<br>3. 宜设置社会车、出租车上落客区； 


### 1.1.4 机场航站楼设置条件

机场与城市间的客流量超过1500人次/h，可在机场服务范围内设置城市航站楼，城市航站楼应有便捷的交通条件。

### 1.1.5 机场客运集疏运设施衔接要求

| 规划年旅客吞吐量
（万人次） | 交通设施衔接要求                                                                                                                                                                                                         |
| --------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| >=4000                      | 1. 宜引入高速铁路衔接；<br>2. 应设置城际铁路、城市轨道交通接驳；<br>3. 应设置机场专线巴士、城市公共汽电车或公路客运站接驳；<br>4. 应设置出租车上、落客区，蓄车区，社会车上、落客区，停车场；<br>5. 应设置3条及以上高速公路或城市快速路衔接； |
| 2000~4000                   | 1. 宜引入城际铁路衔接；<br>2. 宜设置城市轨道交通接驳；<br>3. 应设置机场专线巴士、城市公共汽电车或公路客运站接驳；<br>4. 应设置出租车上落客区，蓄车区，社会车上落客区，停车场；<br>5. 应设置2条及以上高速公路或城市快速路衔接； |
| 1000~2000                   | 1. 应设置1条及以上高速公路或城市快速路衔接；<br>2. 可引入城际铁路衔接；<br>3. 宜设置城市轨道交通接驳；<br>4. 应设置机场专线巴士、城市公共汽电车或公路客运站接驳；<br>5. 应设置出租车上落客区，蓄车区，社会车上落客区，停车场； |
| 200~1000                    | 1. 宜与高速公路、一级公路、城市快速路和主干路等交通系统衔接<br>；2. 应设置机场专线巴士、城市公共骑电车或公路客运站接驳；<br>3. 应设置出租车上落客区，蓄车区，社会车上落客区，停车场； |
| 20~200                      | 1. 应设置出租车上落客区，蓄车区，社会车上落客区，停车场；<br>2. 宜与一级公路或城市主干路等交通系统衔接；<br>3. 宜设置机场专线巴士、城市公共汽电车或公路客运站接驳； |

年旅客吞吐量2000万人次及以上的机场宜与城际铁路、高速铁路衔接，年旅客吞吐量1000万人次及以上的机场，应布局与主要服务城市之间的机场专用道路，并宜设置机场航站楼。

年旅客吞吐量1000万人次及以上的机场应规划城市公共汽电车、出租汽车、机场专线巴士等衔接设施；年旅客吞吐量20万人次及以上的机场，宜规划机场专线巴士、出租汽车等衔接设施。

### 1.1.6 公路客运站、客运码头集疏运设施衔接要求

| 规划年日均旅客发送量（万人次） | 交通设施衔接要求                                                                                                                                                                                                                                                      |
| ------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| >=1                             | 1. 应与一级公路或高速公路，或城市快速路、主干路衔接；<br>2. 有条件可设置城市轨道交通接驳；<br>3. 步行交通系统应与城市道路紧密衔接；<br>4. 应设置非机动车停车场；<br>5. 应设置公交枢纽站接驳；<br>6. 宜设置出租车上落客区，蓄车区，社会车上落客区，停车场； |
| 0.5~1                           | 1. 应与城市主干路及以上等级的道路系统衔接；<br>2. 应设置公交枢纽站接驳；<br>3. 步行交通系统应与城市道路紧密衔接；<br>4. 宜设置出租车上落客区，蓄车区，社会车上落客区，停车场；<br>5. 应设置非机动车停车场；<br>6. 有条件客设置城市轨道交通接驳；<br>7. 根据需要设置出租车蓄车区、社会车停车场； |
| 0.1~0.5                         | 1. 应与城市主、次干路衔接；<br>2. 应设置公交站点接驳；<br>3. 宜设置停车设施；<br>4. 宜设置社会车、出租车上落客区；

## 1.2 城市内部交通客运枢纽

### 1.2.1 城市公共交通枢纽衔接交通设施配置要求

| 客运枢纽区位 | 交通设施配置要求                                                                                                                            |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------- |
| 城市中心区 | 1. 宜设置城市公共汽电车首末站；<br>2. 应设置便利的步行交通系统；<br>3. 宜设置非机动车停车设施；<br>4. 以上至出租车和社会车辆上落客区； |
| 其他地区 | 1. 应设置城市公共汽电车首末站；<br>2. 应设置便利的步行交通系统；<br>3. 宜设置非机动车停车设施；<br>4. 应设置出租车上落客区；<br>5. 已设置社会车辆立体停车设施； |

# 2. 线

## 2.1 城市对外交通

## 2.2 城市内部交通

### 2.2.1 城市公共交通走廊层级划分

| 层级       | 高峰小时单向客流量（万人次/h） | 客运强度（万人次/(km·d)） | 宜选择的运载方式        |
| ------------ | ------------------------------ | ------------------------- | ------------------------------- |
| 高客流走廊 | >6                             | >3                        | 城市轨道交通系统        |
| 大客流走廊 | 3~6                            | 2~3                       | 城市轨道交通系统        |
| 中客流走廊 | 1~3                            | 1~2                       | 城市轨道交通或BRT或有轨电车系统 |
| 普通客流走廊 | 0.3~1                          | 0.3~1                     | 公共汽电车系统或有轨车系统 |

### 2.2.2 集约型公共交通能力划分

集约型公共交通 mass transit，为城区中的所有人提供的大众化公共交通服务，且运输能力与运输效率较高的城市公共交通方式，简称公交。可分为大运量、中运量、普通运量公交，按**单向客运能力划分**。

| 运量等级 | 单向客运能力 |
| -------- | ------------ |
| 大运量 | >3万人次/h |
| 中运量 | 1~3万人次/h |
| 普通运量 | <1万人次/h |

### 2.2.3 城市轨道交通线路快线和干线

| 大类 | 小类 | 运送速度（km/h） |
| ---- | ---- | ---------------- |
| 快线 | A    | >65              |
| 快线 | B    | 45~60            |
| 干线 | A    | 30~40            |
| 干线 | B    | 20~30            |

快线宜布局在中客流及以上等级客流走廊，客流密度不宜小于10万人·km/(km·d)。干线A宜布局在大客流及以上等级客流走廊，干线B宜布局在大、中客流走廊。

线路长度大于50km时，宜选用快线A；30~50km宜选用快线B；干线宜布局在中心城区内。

特大城市中心城区的半径一般在15km~20km，都市区通勤半径一般不超过40km。干线布设于中心城区内，长度一般为15km~30km。快线B位于都市区通勤范围内，长度一般为30km~50km，考虑到直径线或袋装城市情况，不宜超过60km。快线A长度一般大于50km，不宜超过100Km。


### 2.2.4 城市道路的功能等级划分

城市道路的功能等级可以分为三大类，四中类，八小类。

三大类：干线道路（承担中长距离联系交通）、集散道路、支路道路（承担中长距离联系交通的集散和中短距离交通的组织）；

四中类：城市快速路（城市主要中心之间连接）（2级）、主干路（城市分区组团间连接）（3级）、次干路（分区组团内连接）和支路（社区级渗透性/到达性连接）（2级）。

八小类：

| a. 大类 | 中类 | 小类      | 功能说明                                                                         | 设计速度 | 高峰小时服务交通量推荐（双向pcu） |
| -------- | ------ | ----------- | ------------------------------------------------------------------------------------ | -------- | --------------------------------- |
| 干线道路 | 快速路 | I级快速路 | 为城市长距离机动车出行提供快速、高效的交通服务                | 80~100   | 3000~12000                        |
|          |        | II级快速路 | 城市长距离机动车出行提供快速交通服务                               | 60~80    | 2400~9600                         |
|          | 主干路 | I级主干路 | 为城市主要分区（组团）间的中长距离联系交通服务                | 60       | 2400~5600                         |
|          |        | II级主干路 | 为城市分区（组团）间中长距离联系及分区（组团）内部主要交通联系服务 | 50~60    | 1200~3600                         |
|          |        | III级主干路 | 为城市分区组团间联系以及分区组团内部中等距离交通联系提供辅助服务，为沿线用地服务较多 | 40~50    | 1000~3000                         |
| 集散道路 | 次干路 | 次干路   | 为干线道路与支线道路的转换以及城市内中短距离的地方性活动组织服务 | 30~50    | 300~2000                          |
| 支线道路 | 支路 | I级支路  | 为短距离地方性活动组织服务                                              | 20~30    | —                               |
|          |        | II级支路 | 为短距离地方性组织服务的街坊内道路、步行、非机动车专用路等 | —      | —                               |

### 2.2.5 城市道路红线宽度

| 道路分类      | 快速路 |       | 主干路 |       |       | 次干路 | 支路 |    |
| ----------------- | ------ | ----- | ------ | ----- | ----- | ------ | ----- | -- |
|                   | I      | II    | I      | II    | III   |        | I     | II |
| 双向车道数（条） | 4~8    | 4~8   | 6~8    | 4~6   | 4~6   | 2~4    | 2     | — |
| 道路红线宽度（m） | 25~35  | 25~40 | 40~50  | 40~45 | 40~45 | 20~35  | 14~20 | — |


### 2.2.6 城市快速路、主干路交通高峰时段机动车平均行程车速低限

| 道路等级 | 中心城区 | 其他地区 |
| -------- | -------- | -------- |
| 快速路 | 30       | 40       |
| 主干路 | 20       | 30       |

### 2.2.7 城市道路过境通道

城市道路上过境交通量大于等于10000pcu/d，宜布局单独的过境交通通道。



# 3. 面

## 3.1 城市对外交通

### 3.1.1 对外交通衔接时间要求

规划人口规模100万及以上城市的重要功能区、主要交通集散点，以及规划人口规模50万~100万的城市，应能15min到达高/快速路网，30min到达邻近铁路/公路枢纽，并至少有一种交通方式可在60min内到达邻近机场。

## 3.2 城市内部交通

### 3.2.1 居民通勤出行（单程）平均出行距离的控制要求

| 规划人口规模 | >500 | 300~500 | 100~300 | 50~100 | <50 |
| ------------ | ---- | ------- | ------- | ------ | --- |
| 通勤出行距离 | <9   | <7      | <6      | <5     | <4  |

1000万及以上的超大城市可适当提高

### 3.2.2 采用集约型公共交通方式的通勤出勤单程出行时间

集约型公共交通站点500m服务半径覆盖的常住人口和就业岗位，在规划人口规模100万以上的城市不应低于90%；

| 规划人口规模（万人） | 采用集约型公交95%的通行出行时间最大值（min） |
| -------------------- | -------------------------------------------- |
| >500                 | 60                                           |
| 300~500              | 50                                           |
| 100~300              | 45                                           |
| 50~100               | 40                                           |
| 20~50                | 35                                           |
| <20                  | 30                                           |

### 3.2.3 高峰期95%的乘客在轨道交通系统内部（轨道交通站间）单程出行时间

不宜大于45分钟。

### 3.2.4 轨道交通站点800m半径范围内覆盖

中心城区轨道交通站点800m半径范围内覆盖的人口与就业岗位占规划总人口与就业岗位的比例

| 规划人口规模（万人） | 覆盖目标（%） |
| -------------------- | ------------- |
| >1000                | >65           |
| 500~1000             | >50           |
| 300~500              | >35           |
| 150~300              | >20           |

| 规划人口规模 | 中心城区人口密度 | 轨道交通站点覆盖率的合理区间 | 轨道交通站点覆盖率的最低要求 |
| ------------ | ---------------- | ---------------------------- | ---------------------------- |
| （万人） | （万人/km2） | （万人）                 | （万人/km2）             |
| >=1000       | 1.0~2.0          | 64~100                       | 65                           |
| 500~1000     | 0.8~1.2          | 51~78                        | 50                           |
| 300~500      | 0.1~1.0          | 33~64                        | 35                           |
| 150~300      | 0.3~0.8          | 21~51                        | 20                           |

### 3.2.5 轨道交通车站及车辆基地面积

车辆基地应资源共享，占地面积总规模按每千米正线0.8~1.2公顷控制；

* 车辆段面积按25~35公顷/座控制；
* 停车场面积按10~20公顷/座控制；
* 综合维修基地用地按30~40公顷/座控制。

通道控制区宽度宜为30m，2线及以上线路通道应结合运营要求确定用地控制范围；准地下车站控制区长度宜为200m~300m，宽度宜为40m~50m。标准地面、高价车站控制区长度宜为150m~200m，宽度以为50m~60m。起终点车站、编组数大于6节或股道数大于2线的车站、采用铁路制式的车站，具体情况具体分析。


# 4 网

## 4.1 区域

## 4.2 城市

### 4.2.1 不同规模城市的客运交通系统构成

| 1000万人以上 | 应构建快线、干线等多层次大运量城市轨道交通网络。                                                                         |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| 500万以上 | 应确定大运量城市轨道交通在城市公共交通系统中的主体地位，以中运量及多层次普通运量交通为基础，以个体机动化客运交通方式作为中长距离客运交通的补充。 |
| 300~500万人 | 应确定大运量城市轨道的骨干地位，中运量及多层次普通运量公交为主体，引导个体化交通方式的合理使用。 |
| 100~300万人 | 宜以大、中运量公共交通为城市公共交通的骨干，多层次普通运量公交为主体，引导个体化交通方式的合理使用。 |
| 50~100万人 | 客运交通体系宜以中运量公共交通为主干，普通运量交通为基础，构建由竞争力的公共交通服务网络。          |
| 50万以下  | 客运交通系统应以步行和自行车交通为主体，普通运量公交为基础，鼓励城市公共交通承担中长距离出行。    |

规划人口规模500万以上的特大城市，公交出行站机动化出行比例不低于70%，轨道交通站公交出行不低于50%。轨道交通是城市公交系统的主体，并以干线为主，中运量及多层次普通运量交通提供多样化公交服务。引导个体机动化交通方式补充承担中长距离出行。通勤半径控制在15km~20km。规划人口超过1000万的城市，通勤圈半径超出干线有效覆盖范围，应预留快线网络规划条件，应预留快线网络规划条件，引导空间有序拓展。

规划人口规模300万~500万，公交出行占机动化不低于60%，轨道交通占公共交通比例为30%~40%。轨道交通发挥骨干作用，中运量及普通层次占公交出行比例大于50%，承担主体功能。

规划人口规模50万~100万，步行、自行车出行站客运交通比例不低于60%。公交分担率达到20%以上。

规划人口规模50万一下城市，步行、自行车站客运交通出行比例不宜低于70%，通过普通运量公交提供均等化的基本出行服务。


### 4.2.2 干线道路承担的机动化交通周转量

| 规划人口规模（万人） | <50   | 50~100 | 100~300 | >300  |
| ---------------------- | ----- | ------ | ------- | ----- |
| 周转量（车·千米）比例% | 45~55 | 50~70  | 60~75   | 70~80 |
| 干线道路里程比例（%） | 10~20 | 10~20  | 15~20   | 15~25 |

### 4.2.3 不同规模城市干线道路的最高等级

| 规划人口规模（万人） | 最高等级干线公路 |
| -------------------- | --------------------- |
| >200                 | I级快速路或II级快速路 |
| 100~200              | II级快速路或I级主干路 |
| 50~100               | I级主干路         |
| 20~50                | II级主干路        |
| <20                  | III级主干路       |

带形城市可参考上一档规划人口规模的城市选择。当中心城区长度超过30Km时，宜规划I级快速路；超过20km时，宜规划II级快速路。

### 4.2.4 不同规模人口规模城市的干线道路网络密度

城市建设用地内部的城市干线道路的间距不宜超过1.5km。

| 规划人口规模（万人） | 干线道路网络密度（km/km2） |
| -------------------- | -------------------------- |
| >200                 | 1.5~1.9                    |
| 100~200              | 1.4~1.9                    |
| 50~100               | 1.3~1.8                    |
| 20~50                | 1.3~1.7                    |
| <20                  | 1.5~2.2                    |

# 5. 信息

## 5.1 静态信息和动态信息

| 静态信息 | 基本信息 | 交通网络信息、现状和规划土地使用信息、交通调查信息（居民出行调查，各类专项调查）、人口及岗位信息 |
| -------- | -------- | ------------------------------------------------------------------------------------------------ |
|          | 扩展信息 | 城市基础地理信息、公共设施信息、建筑信息、各类空间性规划和相关规划信息 |
| 动态信息 | 基本信息 | 道路交通量、道路行程车速、道路交通客流量、公共汽电车客流量          |
|          | 扩展信息 | 交通枢纽客流信息、货运交通信息、停车场信息、非机动车和行人信息、交通事件信息、交通环境信息 |

## 5.2 交通信息集成的维度和层次

| 维度类别 | 维度       | 基本层次                                     | 扩展层次                       |
| -------- | ------------ | ------------------------------------------------ | ---------------------------------- |
| 基本维度 | 日期       | 日、月、年                                  | 季度、周、工作日、周末、节假日 |
|          | 时段       | 早高峰、晚高峰、全天                   | 每15分钟、每小时、日间、夜间 |
|          | 区域       | 行政区、特征交通区（如市中心区、外围区、郊区等） | 街道、组团、城市规划分区等 |
|          | 道路等级 | 快速路、主干路、次干路                | 支路                             |
|          | 公交类型 | 轨道交通、公共汽电车干线             | 一般公交线路、特殊公交、辅助公交等 |
| 扩展维度 | 特定分析对象 | 境界线、出入口、查核线、通道（走廊）等 | 特殊交通产生吸引点等     |
|          | 环境       | 天气情况                                     | 空气质量等                    |
|          | 交通事件 | 交通事故                                     | 施工、交通管制等           |