---
title: 四、出行分布预测
author: ZhiYuan Wang
date: '2020-01-15'
slug: 四-出行分布预测
categories:
  - TransCAD
tags:
  - 学习总结
---

# 1. 基本原理与方法

出行生成预测：得到了未来年各小区出行的产生量与吸引量，需要进一步分析各校区之间的出行交换量。

出行分布预测：在已知分布矩阵各行、各列之和的条件下，求矩阵中每个元素具体数值的问题。

在数据上无解，需要补充额外条件

1. 补充历史信息：将现状出行分布矩阵（OD调查得到）乘以一定的增长系数，得到未来出行分布矩阵——增长系数法；
2. 模拟出行者的目的地选择行为并以此构造相应的分布预测模型，包括重力模型、介入机会模型、最大熵模型等。

## 1.1 增长系数法

基本假设：未来的出行分布量是现在出行分布量的基础上，乘以相应的增长系数得到的。

TransCAD中使用Fratar法，收敛速度快。

增长系数法的缺点：

1. 要求有完整的现状出行分布矩阵，而得到这种基础数据的成本很高；
2. 对几年出行矩阵精度依赖性较大；
3. 如果基年矩阵中有零元素，那么预测矩阵中对应的部分也为零；
4. 无法预测与未来年新增加小区相关的出行分布量。

## 1.2 重力模型

基本假设：出行分布是群体出行决策的结果，两小区之间的出行分布量的大小，受两小区出行生成量与两小区之间出行距离（或广义费用）的共同影响。

$$q_{ij}=\alpha O_i D_j f(c_{ij})$$

$C_{ij}$为两分区间的阻抗；$f(c_{ij})$为阻抗函数。

- 无约束重力模型：直接计算不满足行列和为OD量的约束条件，不能直接用于出行分布预测；
- 有约束重力模型：使用增长系数法对无约束重力模型初始计算结果迭代。

模型标定：

需要根据现状出行分布矩阵和阻抗矩阵估计阻抗函数中的参数。

优点：

1. 可解释性强；
2. 敏感反应交通供给变化对出行影响，适用于中长期需求预测；
3. 不需要完整基年OD矩阵，如果有可信赖的模型参数，甚至不需要基年OD矩阵；
4. 特定交通小区（如新开发区）之间分布量为零时，也能进行预测；

缺点：难以准确预测小区内出行分布量。

# 2. 增长系数法在TransCAD中应用

## 2.1 数据准备

-　现状年出行OD矩阵
-　未来年出行发生量和吸引量表。

## 2.2 操作

1. 绘图Planing-Trip Distribution-Growth Factor Method
2. Production Field选O；Attraction Field选D，点OK；

# 3. 重力模型在TransCAD中应用

**以幂函数型阻抗函数为例**

## 2.1 数据准备

- 小区地理文件
- 现状出行分布矩阵
- 现状小区阻抗矩阵

## 2.2 标定重力模型

1. Planing-Trip Distribution-Gravity Calibration；
2. Matrix File选择OD_Base；
3. 下方Impedance Matrix File（阻抗矩阵）选择Impedance；
4. Function下勾选Inverse Power，新数据视图下b为阻抗函数参数。

## 2.3 运行重力模型

需要：

- 一个未来年小区间阻抗矩阵；
- 一个未来年出行产生量和吸引量表；
- 重力模型阻抗函数的参数。

Planing-Trip Distribution-Gravity。
