---
title: 三、出行生成预测
author: 王致远
date: '2020-01-15'
slug: 三-出行生成预测
categories:
  - TransCAD
tags:
  - 学习总结
---

# 1. 出行的基本概念

## 1.1 出行的三个属性

1. 每次出行有起讫点；
2. 每次出行有一定目的；
3. 每次出行使用一种或多种交通方式；

## 1.2 出行生成的表达

国内交通规划工作中对出行生成的定义：

- 出行产生量：各类出行的全部起点数之和，或称出发量；
- 出行吸引量：各类出行的全部讫点数之和，或称到达量。

- PA矩阵：Production  Attraction
- OD矩阵：Orignation Destination

TransCAD中有PA矩阵向OD矩阵转换的功能。

# 2. 预测方法

## 2.1 建立模型

### 选择因变量和自变量

- 因变量：出行生成量（包括产生量或吸引量）；
- 自变量：影响出行生成的各种因素（人口数量、经济指标、用地面积）；

### 分析每个自变量和因变量关系

画散点图

### 确定模型形式

一般用多元线性回归模型

## 2.2 参数估计

使用最小二乘法：残差的平方和最小

## 2.3 模型检验

1. 初步经验检验：模型是否符合基本常识；
2. 统计检验：显著性检验、相关性检验；
3. 判定预测效果：把非样本期内的因变量实际值与同期预测值比较；
4. 实施预测；

## 2.4 注意事项

在实际规划中，常将交通小区作为回归分析的样本单位；

1. 当各小区之间社会经济或地域属性差异较大，且这些差异难以定量表示，可分类建立回归分析模型；
2. 有些小区缺乏某些相关变量信息，分析时需要将其排除；

## 2.5 结果整理

所有小区的出行产生总量要等于出行吸引总量。

可靠性高的一方对另一方进行矫正。一般认为出行产生量的预测更为可靠。

# 3. 回归分析在TransCAD中应用

## 3.1 数据准备

每个小区一个样本，字段如下：

- ZoneID：小区编号；
- P_Base：现状年出行产生量；
- A_Base：现状年出行吸引量；
- People_Base：现状年人口数量；
- GDP_Base：现状年经济产值；
- People_Fur：未来年人口数量；
- GDP_Fur：未来年经济产值；
- P_Fur：未来年出行产生量（为空，待预测）；
- A_Fur：未来年出行吸引量（为空，待预测）；

## 3.2 估计回归模型参数

1. 打开数据文件；
2. 统计-模型估计；
3. Dependent选择因变量P_Base；
4. Independent选择自变量：People_Base和GDP_Base；
5. 点击ok，保存模型文件，可看Show Report，模型的标准误差、相关系数、t值、F值、R方；
6. 用相似方法估计A_Base的参数；

## 3.3 运行回归分析模型

1. 统计-Model Evaluation-打开Pro.mod；
2. Results in 后选P_Fur;
3. 将Forecasted Variable选为People_Fur和GDP_Fur；
4. 同样的方法填充A_Fur；

## 3.4 平衡产生量和吸引量

1. 绘图Planing-Balance-Vector Balancing；
2. Vector 1 Field选择P_Fur;
3. Vector 2 Field选择A_Fur；

## 3.5 出行生成预测结果分析

1. 打开TAZ.dbd;
2. 将平衡后的Balance.bin链接到地图；
  1. From选择地图图层；
  2. To Table选择数据框；
3. 点击Chart Theme；选择P_Fur和A_Fur为字段，柱状图；





