---
title: 铁路客运站点综合交通规划
author: 王致远
date: '2020-01-08'
slug: 铁路客运站点综合交通规划
categories:
  - 交通
tags:
  - 学习总结
---

## 11.4.1 铁路客运站点综合交通规划主要内容

铁路客运站点综合交通规划应从功能定位、场站布局、交通组织、用地布局等方面开展，主要内容包括：

功能定位及发展战略：根据铁路客运站点在城市总体规划和综合交通系统中的地位，确定铁路客运站点在城市发展中的定位，在综合交通系统中的定位以及所在片区的地位。根据城市社会经济发展目标与城市发展目标，制定铁路客运站点发展目标与发展策略。

综合交通场站布局：依据铁路客运站点功能定位，总体发展目标和发展战略，提出铁路客运站点规划布局原则和要求，合理布局各种交通方式的位置，打造高效、一体化的交通系统。

铁路客运站交通组织：分析铁路客运站内部各种交通方式车流、人流特征，确定交通组织流线，实现人车分流，减少交叉干扰；对外完善客运站城市其他组团及周边城镇、大型集散地等之间的交通衔接关系。体现“以人为本，以流为主”的核心要求，为旅客提供方便、舒适的乘车环境和快捷便利的“零换乘”或“最短时空换乘”条件。

周边用地布局规划：准确把握铁路客运站点对城市空间布局、土地利用的影响，合理确定站点周边地区总体结构。引入“TOD”模式，鼓励铁路客运站点地区综合开发，布置商业、商务、文化、旅游等功能，优化用地布局，完善城市功能，实现铁路客运站点周边地区交通运行与土地利用的统筹协调。

## 11.4.2 铁路客运站点综合交通规划主要原则和理念

编制铁路客运站点综合交通枢纽规划必须遵循以下基本原则：

1. 遵守国家政策、法规及相关规定，执行规划编制办法和合理运用技术标准；

2. 积极借鉴先进的铁路客运站点综合交通规划理念，采用定性与定量相结合的规划方法和技术手段，保持规划的前瞻性、系统性和操控性；

3. 应贯彻落实优先发展城市公共交通的战略，优化交通模式与土地使用的关系，统筹各交通方式协调发展；

4. 应遵循定量分析与定性分析相结合的原则，在交通需求分析的基础上，科学判断铁路客运站点的发展规模，合理制定规划方案；

5. 编制铁路客运站点综合交通规划，应当以批准的城市总体规划、分区规划和详细规划为依据；密切与综合交通规划等相关规划的协调与衔接，广泛吸纳各方意见。

在此基础上铁路客运站点综合交通枢纽规划还需引入先进的规划理念：对铁路客运场站的布设、设计等一体化整合；场站内换乘应当以人为本，保证旅客换乘方便、便捷、舒适；在保证客流集散便捷的前提下应对车站周围空间进行综合开发等。
