---
title: 城市轨道交通快线
author: 王致远
date: '2020-12-21'
slug: 城市轨道交通快线
categories:
  - 交通
tags: []
output:
  blogdown::html_page:
    toc: true
---

# 1. 快线与市域铁路、城际铁路

国标《城市轨道交通线网规划标准》（GB/T50546-2018）中明确了**市域城镇连绵地区或部分城市城区的快线承担以通勤出行为主的服务功能。快线主要服务于城市通勤圈范围。**

市域铁路主要服务于中心城区与其他组团之间、组团式城镇之间的客流联系，是具有快速、高密度、公交化的客运专线铁路。

团标《市域铁路设计规范》（TCRS C0101-2017）中将市域铁路分为100km/h，120km/h，140km/h，160km/h四个速度等级。旅行速度与《城市轨道交通线网规划标准》规定的快线A和快线B旅行速度一致，按照旅行速度划分市域铁路和快线是同一线网层次。

快线A和快线B没有对系统制式进行规定，可以使城市轨道交通制式，也可以是铁路制式，市域铁路可视为快线网的组成部分，二者在空间上应统筹布局线路走廊和换乘枢纽，统筹配置资源。

城际铁路主要服务于相邻城市间或城市群区域的旅客运输，在行标《城际铁路设计规范》（TB 10623-2014）中将设计速度分为200km/h，160km/h，120km/h三级。当设计速度选择后两级时，城际铁路具有服务于其沿线市域城镇的功能。

# 2. 快线与干线

## 2.1 旅行速度区分

- 快线A：>65
- 快线B：45~60
- 干线A：30~40
- 干线B：20~30

## 2.2 客流区分

- 快线宜布局在中客流及以上等级客流走廊，客流密度不宜小于10万人·km/(km·d)。
- 干线A宜布局在大客流及以上等级客流走廊。
- 干线B宜布局在大、中客流走廊。

## 2.3 长度区分

- 线路长度大于50km时，宜选用快线A，最大不超过100km；
- 30~50km宜选用快线B，最大不超过60km；
- 干线宜布局在中心城区内，长度为15~30km；

# 3. 多网融合

多网融合可以高效利用交通走廊，充分发挥系统效率，支撑市域城镇可持续发展。

# 4. 多速度目标走廊规划建设

多速度目标走廊规划的必要性：城市主要功能结构一般由城市功能轴线、城市中心、副中心等组成，这些地区城市功能及就业人口自高度聚集，进出客流高度集中。当城市功能轴线较长时，走廊内长、中、短出行需求会同时存在，沿线主要功能区之间的出行时间也往往难以满足国家标准规定要求，需要重点研究快线与普线公用走廊的方案，以满足多速度目标、多客流需求，保障城市功能高效运转。

快线与普线公用走廊时，快线与普线两条线路可以独立设置；当同时满足快线、普线两个层次的运输能力要求时，也可采用共线方案。

同理，在都市圈、市域城镇发展轴线上，需要研究快线与城际铁路公用走廊的条件和方案。

在市域快线走廊内，应结合客流特征需求研究快线A和快线B两个速度等级同时存在的可能性，以及两个速度等级系统共线的技术方案。

# 5. 快线进城组织模式

快线客流一般具有向心客流特征，客流重心主要位于承担市域服务职能的市级中心、副中心、城市客运枢纽等地区。快线进入城区后，应衔接这些主要功能中心，并在此地区形成与普线网的换乘枢纽或车站，不仅有利于城市中心、副中心与外围组团、卫星城之间的客流直达联系，也扩大了快线客流集散的服务范围，大大缩短居民在途出行时间。

快线应优先采用贯穿式和半径线式布局模式，该模式客流直达性好、换乘少，对于促进市域城镇一体化发展较为有利；当快线进出城区中心较为困难时，可选择采用切线式布局模式，将快线与若干条普线相交形成换乘车站，快线客流通过换乘普线进入城区中心，出行效率比贯穿式差一些。快线应避免采用端点衔接式布局模式，该模式无视快线客流特征需求，不符合市域城镇交通一体化发展要求。

# 6. 客流

《城市轨道交通线网规划标准》明确快线客流密度不宜小于10万人8\*km/(km\*d)。