---
title: 五、方式划分预测
author: 王致远
date: '2020-01-15'
slug: 五-方式划分预测
categories:
  - TransCAD
tags:
  - 学习总结
---

方式划分是四阶段的第三阶段，目的是将各小区间的出行分布量划分为各种交通方式的分布量。

在TransCAD中用Logit模型。

# 1. 基本原理与方法

## 1.1 基本概念

方式划分模型的基础：

1. 个人在每次选择中总选择效用值最大的选择枝；
2. 个人关于每个选择枝的效用值由个人自身的特性和选择枝的特性共同决定；

## 1.2 影响交通方式选择的因素

1. 出行者及出行特性
  - 出行者的职业、年龄、收入；
  - 家庭车辆拥有情况；
  - 出行目的、时段；
2. 交通方式特性
  - 费用；
  - 出行时间
  - 舒适度、安全性
  
## 1.3 Logit模型

Logit模型是较常用的非集计模型。

$$p_{ij}^k=\frac{exp(V_{ij}^k)}{\sum{exp(V_{ij}^k)}}$$

$p_{ij}^k$为第k种出行方式的分担率；$V_{ij}^k$为第ij小区第k中出行方式的效用值。

最简单的效用函数

$$V_{ij}^k=\alpha T_{ij}^k+\beta F_{ij}^k$$

$T_{ij}^k$为ij小区第k种出行方式旅行时间；$F_{ij}^k$为ij小区第k种出行方式货币费用。$\alpha$$\beta$为待估计参数。

# 2. Logit模型在TransCAD中的应用

## 2.1 数据准备

两组矩阵：

- 出行费用矩阵
  - CarCost
  - BusFare
- 出行时间矩阵
  - CarTime
  - BusTime

交通方式离散选择表

- 第一列ID值
- 第二列出行起点
- 第三列出行重点
- 第四列出行方式

OD_Base全方式出行矩阵

## 2.2 创建出行方式表

1. 打开CostMatrix和TimeMatrix以及TAZ.dbd；
2. 选择绘图Planning-Mode Split-Specify a Multinomial Logit Model；
3. 点击Specify Alternatives右侧的Add，添加Bus和Car；
4. 点击Specify Parameters右侧Add，添加Cost和Time；OK；
5. Fill MNL Model Table在Number of Altemnatives后选2；
6. 在Specify Utility for后先选Car；在Change Information下的Prameter下选Time，下方勾选矩阵，在列表框中分别选Time Matrix和CarTime；

## 2.3 Logit模型参数估计

1. 打开CostMarix和TimeMatrix，ModelTab.bin和Choice.bin；
2. 选择Planning-Mode Split-Multinomial Logit Estimation；
3. ID Field选IT；Choice Field选Choice；Origin Field选ORIGN；Destination Field选DEST；点OK；
4. 参数值显示在出行方式表ModelTab.bin；

## 2.4 应用Logit模型

1. 打开CostMatrix、TimeMatrix、ModelTab、TAZ；
2. 选择Planning-Mode Split-Multinomial Logit Application；
3. ID Field选ID，点OK；
4. 预测的分担率矩阵保存；

## 2.5 将分担率矩阵转换为分方式矩阵

1. 打开OD_Base全方式矩阵和分担率矩阵；
2. 在OD_Base右键，新建两个子矩阵TripsCar和TripsBus；
3. 在新子矩阵里，右键-填充-Cell by Cell-multiply matrix得到分方式矩阵；
