---
title: 二、交通调查数据处理与分析
author: 王致远
date: '2020-01-14'
slug: 二-交通调查数据处理与分析
categories:
  - TransCAD
tags:
  - 学习总结
output:
  blogdown::html_page:
    toc: true
---

# 1. 交通调查的对象

1. 社会经济基础资料
2. 交通需求
3. 交通设施
4. 交通流量

# 2. 交通小区

不可能对每个交通源进行单独研究，要将分散的交通源按一定原则就近合并成若干个交通小区。交通小区在形式上表现为一个区域，但在逻辑上表现为一个点，这个点可称为小区的质心。

通常小范围的分区约为3000~5000人，大范围的城市分区约为5000~10000人。

交通小区要有同质性，区内的土地利用、经济、社会等特性应尽量一致。

## 2.1 交通小区划分

文件-新建-Geographic File-面空间数据-添加字段ZoneID,修改数据类型，储存为dbd文件。

## 2.2 编辑面类型地理文件

- 加号，在地图窗口绘制一条闭合的边界线，添加一个新面；
- 斜杠圆，删除；
- 白箭头，拖动柄编辑；
- 绿灯，保存编辑；
- 红灯，取消编辑；

## 2.3 为小区图层输入属性数据

工具栏上i按钮，除ZoneID外，ID和Area为自动分配字段。

## 2.4 设置小区显示样式

鼠标右键-图层-Style

顶部菜单，图例按钮，可显示图例，并贴附于地图。

## 2.5 保存

保存为地图，可保留设置的地图显示样式，还可组织地理文件。

**一个地图中可以包含任意多个图层（地理文件）。**

# 3. 社会经济基础资料

1. 人口调查：人口数量、年龄分布、职业构成、迁移情况、增长状况；
2. 经济调查：国民生产总值、各产业产值、人均收入、投资状况、产业结构；
3. 土地利用调查：用地布局、开发状况、建筑密度、住户数量、就业岗位数、就学岗位数、商品销售额。
4. 车辆保有量：载货汽车、载客汽车和私人汽车、非机动车。

## 3.1 新建和编辑数据表文件

文件-新建-Table-Fixed-format binary- 添加字段-保存为bin文件；

编辑-添加记录-输入要增加的数据记录条数

## 3.2 将数据表连接到地图

打开地图数据和经济表-数据视图-加入-Joining from选地图-to选经济标

## 3.3 创建基于小区的专题地图

彩色专题图、点密度专题图、等级符号专题图

### 3.3.1 制作GDP分布色彩专题图

工具栏上-Color Theme MapWizard-Field选择GDP

### 3.3.2 制作人口分布点密度专题图

工具栏上-Dot density Theme MapWizard-Field选择People

# 4. 交通需求调查：OD调查

OD调查是交通规划中的最基础调查项目，包含抽取样本、实施调查、样本放大、统计分析、数据处理，是从总体到样本，再从样本到总体的过程。

包括：

1. 出行主体信息；
2. 出行信息；

多采用家访调查法

分析结果：

1. 各分区的出行产生、吸引量；
2. 出行分布量，即各分区之间的出行量；
3. 出行时间和距离分布等；

表现形式：

- OD表
- 期望线图
- 统计图
- 相关曲线：时间分布曲线、出行距离分布曲线

## 4.1 建立和编辑矩阵文件

新建-Matrix File-Name取名-IDs are in，选择ZoneID

## 4.2 从其他数据导入矩阵文件

- 打开xls文件，选择工作簿，另存为一个bin文件，有O/D/Trips三列；
- 选择矩阵-导入-选择行/列ID分别为O和D-选择字段为Trips

## 4.3 制造期望线

工具-地图分析-欲行线

想改变期望线外观，点Scaled-symbol Theme Wizard

# 5. 交通设施调查

交通网络的长度、密度、能力、级配

交通网络拓扑结构与技术参数信息，包含：

1. 路段及其连接关系
2. 路段的等级、长度、宽度、车道、分隔方式、设计车速；
3. 交叉口的类型、位置；
4. 公交/轨道线网布局、站点设施、车辆配置、公交场站设置；

## 5.1 新建线类型的地理文件

- 一定要勾选 Create a Table for endpoint data；
- 建立四个字段，Type（路段类型），Speed（设计车速），Time（行驶时间），Capacity（通行能力）；

## 5.2 编辑线类型地理文件

- 在根据网络地图编辑线图层时，不要依次输入整条“道路”，而是应该分段输入“路段”，即遇到一个交叉口，就双击一次鼠标，在单击开始下一条路段的输入。如果一次输入整条道路，很可能路网不连通。
- 可在图层对话框，将隐藏的节点显示出来。

## 5.3 检查路网连通性

检查是否有虚接的线段或不连通的节点。

工具-地图编辑-检查线层连通性-设置阈值50米；

## 5.4 为路段图层输入属性数据

快速路、主干道、次干道、支路

### 批量选择某一类型的路段

1. 蓝色手指按钮，按住Shift键，批量选择同一类型的多个路段；
2. 点击DataView；
3. 顶部下拉，选择Selection;
4. 选择某一字段的列，点击fill；
5. 用公事计算路段设计车速；

```
if Type=1 then 80 else if Type=2 then 60 else if Type=3 then 40
```

# 6. 交通量调查

## 6.1 调查目的

- 评价现状交通网络运行状况；
- 标定交通分配模型中的关键参数；
- 为设计未来交通网络规划方案提供依据；
- 校核OD调查成果的精度；
- 通过路段交通量反推出行分布量；

## 6.2 调查内容

- 机动车、非机动车流量调查；
- 公交客流调查；
- 行人流量调查；
- 核查线流量调查；

## 6.3 交通量数据处理与分析

分别为每条道路分别输入两个方向的流量

在路段属性表中添加分别以AB和BA开头的字段，TransCAD将自动对其进行分配并分方向使用这两个字段中的数值；

### 制作流量专题地图

点击Scaled-Symbol Theme，选择BA_Flow

### 制作流量专题图的快捷工具

绘图Planing-Planing Utilities-Create Flow Map，选择Flow和V/Cziduan 

### 制作交叉口流量流向图

- 工具栏上InterSection Diagram按钮
- Forward Flow 选AB_FLOW
- Display Flow 选BA_Flow;
- 勾选Display Flow Labels；
